#+TITLE: Organic Japanese lesson notes
My follow-along notes from the Organic Japanese course on Youtube: [[https://www.youtube.com/playlist?list=PLg9uYxuZf8x_A-vcqqyOFZu06WlhnypWj]]

# TODO: Replace examples with tables
# ∅
* Lesson 1: The core Japanese sentence
Every Japanese sentence is fundamentally the same, they have the same core.

Every sentence is formed of two elements, (visualised as a train) they are the /carriage/ and /engine/.

In all languages there are only two kinds of sentence:
- A is B: Sakura is Japanese
- A does B: Sakura Walks

Sakura ga nihonjin da - Sakira is Japanese
Sakura ga aruku - Sakura walks

Going back to the train metaphor:
#+BEGIN_EXAMPLE
 /Carriage/      /Engine/
[Sakura *が*] [Nihonjin *だ*]
#+END_EXAMPLE

There is a third form of the Japanese sentence core sentence:
#+BEGIN_EXAMPLE
/Carriage/  /Engine/
[Pen *が*] [aka *い*] = Pen is red
#+END_EXAMPLE
# TODO: In which lesson?
This is similar, but not identical to an adjective. This will be discussed more later.

To recap, all of these sentences begin with the subject, they are connected with が, and the three /engines/ of the Japanese core sentence are:
- う - verb          - A does B
- だ - noun          - A is B
- い - /"adjective"/ - A is B

* Lesson 2
** The invisible が carriage
Last lesson we covered the が /carriage/. Part of the reason so many people struggle with Japanese is that, although we can always see the /engine/ of the sentence, we cannot always see the が carriage. Remember, the core of the Japanese sentence is formed of the が carriage and an engine.

The closest English equivalent to this invisible が carriage is 'it'. Here is an example English sentence:
#+BEGIN_QUOTE
The ball rolled down the hill. When the ball got to the bottom the ball hit a sharp stone and the ball was punctured and all the air came out of the ball.
#+END_QUOTE

This is not a sentence we would ever say in English, once we have established that we are talking about 'the ball' we would instead refer to the ball with it:
#+BEGIN_QUOTE
The ball rolled downm the hill. When it got to the bottom it hit a sharp stone and it was punctured and all the air came out of it.
#+END_QUOTE

If we were to completely omit /it/ the sentence would still be easy to understand, we don't /need/ to use this it marker each time, but English grammar *demands* it. Japanese does not, hence the 'invisible' が carriage.

'It' by itself doesn't really mean anything, we know what it means from context. If a child comes downstairs in the middle of the night and says /'Got really hungry'/, /'Came for something to eat'/ we understand that the child means /'I got really hungry'/ not /'The dog got really hungry'/. In English this isn't a proper sentence, but in Japanese it is.

All of the little pronouns I/it/we/he/they can all be replaced by the invisible が carriage; the *∅ pronoun*. It is important to remember that the carriage *is* still there.

One might say: ドリーだ meaning /'I am Dolly'/. The full sentence being: ∅がドリーだ.

By default 'I' is the default value of this /∅ pronoun/. However, if someone were introducing their daughter and said ドリーだ we would understand from context that ∅ meant this/she.

If I say 土曜日だ /'It is Saturday'/ it is clear that ∅ means /today/.

Each of these sentences are complete grammatical sentences with a subject marked by が and an engine, but in each of these cases the が carriage is just invisible. It *is* still there. This may seem to be arbitrary, or over-complicated but it saves a lot of grief later on to model sentences this way. Without this information as sentences become more complex they're going to seem increasingly vague and hard to understand.

** The を carriage
This carriage is formed of a noun and the particle を. The を particle marks the object of the sentence. The thing that some verb (the engine) is being done to (が marks the thing doing the verb). It is not part of the core sentence which is always formed of the が carriage and an engine.
#+BEGIN_EXAMPLE
/carriage/ /carriage/ /engine/
[わたしが]  [ケーキを]  [たべる]
    I        cake       eat
#+END_EXAMPLE

The core sentence here is 'I eat'. The extra carriage, the を carriage is telling us more about the engine. /What/ are we eating? We are eating cake.

Once again, we would often see this said as: ケーキをたべる. This is just another case with the invisible が carriage. We *cannot* have a sentence without a が, we *cannot* have a sentence without a doer.

When we are saying ケーキをたべる, what we are really saying is ∅がケーキをたべる. And the default value for ∅ is わたし: /I/.

* Lesson 3
** は particle secrets
The は particle can never be a part of the core Japanese sentence. It is neither the carriage we are saying something about, nor the engine, what we are saying about it. It isn't a carriage /outside/ of the core sentence either like the を particle is. The は particle is not part of the logical structure of the sentence.

は is a non-logical particle. In our train metaphor the は particle is a /flag/. It simply marks something as the topic of the sentence, but doesn't say anything about it.

An exact translation of the は particle would be 'As for x'. わたしは therefore means 'As for me', *not* 'I am' (わたしが).

A commonly mistranslated sentence is:
#+BEGIN_QUOTE
わたしは日本人だ - I am Japanese
#+END_QUOTE

If we look back at our train however we can see that something is missing:
#+BEGIN_EXAMPLE
  /flag/     /engine/
[わたし*は*] [日本人*だ*]
#+END_EXAMPLE

There is no が carriage. We don't know who the subject actually is. One may ask 'well why don't we just treat the は particle as if it is a carriage'. In this example it is obvious that the topic marked by は is the same as the subject marked by が, but there are many more cases where this is not true, leading to much confusion down the road. Let's look at a similar sentence. You are at a restaurant, the waitress is asking what you would like:
#+BEGIN_QUOTE
わたしはうなぎだ ー +I am an eel+
#+END_QUOTE

Treating は as 'I am' doesn't work. As we now know the default value of the ∅ pronoun is 'I', but in this context it's clear that we're talking instead about /what/ we want to eat. わたしはうなぎだ therefore means 'As for me, eel'.

** The に particle
The に particle marks the target (indirect object) of an engine. Along with the が and を we have a sort of /trio/ of logical /A does B/ sentences.

- が tells us who does the doing
- を tells us what it is done to
- に tells us what the ultimate target of that doing

#+BEGIN_QUOTE
わたしがぼーるをなげる - I threw the ball
#+END_QUOTE
The *core* sentence is 'I threw', and the extra carriage (を) tells us what we threw, the ball. We can add another carriage to tell us more about the engine:
#+BEGIN_QUOTE
わたしがぼーるをさくらになげる - I threw the ball at/to Sakura
#+END_QUOTE
Sakura is the destination, the target. It is important to note here that the logical particles tell us what is happened. The order of the words doesn't really matter the way it does in English.
#+BEGIN_QUOTE
わたしにさくらがぼーるをなげる - Sakura threw the ball at/to me.
#+END_QUOTE
#+BEGIN_QUOTE
ぼーるがわたしにさくらをなげる - The ball throws Sakura at me
#+END_QUOTE
Obviously this final example doesn't make any sense (although we might want to say something non-sensical like this in a fantasy novel or something) but we can say whatever we like in Japanese so long as we use the right logical particles.

Now let's introduce は:
#+BEGIN_EXAMPLE
  /flag/    /carriage/ /carriage/  /carriage/ /engine/
[わたし*は*]  [∅*が*]   [さくら*に*] [ぼーる*を*] [なげる]
#+END_EXAMPLE
As we know, even if the が carriage is invisible (or silent) this means 'As for me, (I) threw the ball at Sakura'. Now let's give the は /flag/ to the ball:
#+BEGIN_EXAMPLE
  /flag/      /carriage/ /carriage/   /carriage/ /engine/
[ぼーる*は*] [わたし*が*] [さくら*に*]  [∅*を*]    [なげる]
As for the ball, I threw *it* (the ball) at Sakura.
#+END_EXAMPLE
Note, this time the を carriage has become invisible, because what we're throwing is now marked by the は particle, ∅ here has taken the value of 'it'. Even without は we might already know what 'it' was that was thrown from context. The important thing to understand here is that as we change the logical particles from one noun to another we change the meaning of the sentence, but when we change the non-logical particle は from one noun to another it makes no difference to the logic of the sentence. It may make some difference to the emphasis, but it makes no difference to who is doing what or what they're doing it to.

* Lesson 4: Japanese past, present and future tenses
Up until now we've only been using one tense and that is the one presented by the plain dictionary form of verbs. To use natural sounding Japanese we need 3 tenses. In Japanese these are not the same past, present and future tenses we're familiar with from English.

The tense we have been using thus far is *not* the present tense. It is the /non-past/ tense. This non-past tense is actually very similar to the English non-past tense. What is the /English/ non-past tense? It is again the plain dictionary form of a verb. Eat, run, walk etc. It is unnatural in English to say 'I eat cake', to mean 'I am eating cake'. It is natural however to use the non-past tense to say 'Sometimes I eat cake' or, in the explictily future tense 'I will eat cake'. Japanese is just the same as English in this way. It is rare we use this form for talking about things actually happening right now, except in cases like literary descriptions.

Most of the time the Japanese non-past tense refers to future events. In fact, just as ∅ defaults to 'I', the non-past tense defaults to the future.
#+BEGIN_QUOTE
さくらが歩く - Sakura will walk
#+END_QUOTE
#+BEGIN_QUOTE
犬がたべる - dog will eat
#+END_QUOTE
The way we have been using this tense up until now, 'Sakura walks', is possible, but isn't the most natural way.

If we want to say something more natural like 'Sakura is walking' we must use the verb 'to be'[fn::In English the verb 'to be' is irregular and has multiple forms be/is/are/am: To /be/ walking, Sakura /is/ walking, not Sakura /be/ walking.], or in Japanese いる.
#+BEGIN_QUOTE
さくらが歩いている - Sakura is walking
#+END_QUOTE
#+BEGIN_QUOTE
犬がたべている - dog is eating
#+END_QUOTE
There is something here however that we haven't yet seen. In our train metaphor this is a secondary engine, here たべて which could be an engine in of itself, is helping (modifying) the main いる engine. Our core sentence is still the same, we have a が carriage and an engine, いる i.e. さくらがいる - Sakura is (existing). The secondary engine modifies いる telling us more about what state she is currently existing in, she is in the eating state. As we go further into Japanese we will see this secondary engine structure again and again.
#+BEGIN_EXAMPLE
/carriage/ /engine/ /engine/
 [犬*が*]   [たべて]  [いる] - dog is eating
#+END_EXAMPLE

Also, just as in English we don't say 'The dog is eat', we use a special form of the verb /eat/ => /eating/. In Japanese this is the て form. This is covered in the next lesson.

For the past tense of verbs instead of adding て to verbs we add た.
#+BEGIN_QUOTE
犬がたべた - The dog ate
#+END_QUOTE
The way in which we do this is exactly the same as the way in which we attach て and will be covered in the next lesson.

If we want to make it clear that we are talking about a future event we can add a time expression. By prefixing a sentence with あした (tomorrow), we can make it clear that what we will be doing, we will be doing tomorrow.
#+BEGIN_QUOTE
あした[∅が]ケーキをたべる - Tomorrow I will eat cake
#+END_QUOTE
Note how we simply preface the sentence with 'tomorrow', just like we would in English. This is the case with all /relative-time nouns/, yesterday, tomorrow, the day after tomorrow, next week, next month, next year.

For /non-relative/, i.e. /absolute/ time expressions we must use the に particle:
#+BEGIN_QUOTE
火曜日*に*[∅が]ケーキをたべる - On Tuesday I will eat cake
#+END_QUOTE
We must attach に in all the same places we would attach on/in/at in English. On Tuesday, in March, at 12 o'clock. Foruntately in Japanese we only need to use the one particle.


* Lesson 5: Japanese verb groups and て form
Japanese verbs fall into three groups: /Ichidan/, /Godan/, and /irregular/

The first group are /ichidan/ (lit: one level) verbs. Morphing these verbs is easy, we simply remove the る and add our new ending. Ichidan verbs can only end in either いる or える.

The second group is by far the largest, the /godan/ (lit: five level) verbs. This groups contains verbs that end in all of the possible verb endings: う つ る ー ぬ ぶ む ー く ぐ ー す. Each of these ending groups has its own way of being morphed, though although they're 'five level' verbs, two of the groups use the same method so we only need to learn 4 methods. Confusingly this means that godan verbs can end in いる or える, most of these will still be /ichidan/ verbs, and fortunately even if a verb is morphed incorrectly, you will probably still be understood.
- う つ る -> って
- ぬ ぶ む -> んで
- く/ぐ -> いて/いで (Note: this is the combined group)
- す -> して

There are only two irregular verbs, くる and する. いく, is partly irregular, but not completely.
- くる -> きて
- する -> して
- いく -> いって (+いいて+)
These are the only exceptions
* Lesson 6: Japanese "adjectives"
Japanese adjectives are not the same as English adjectives. As we have learned Japanese sentences come in three kinds, depending on the type of engine they have. As a reminder they are:
- う - verb - A does B
- だ - noun - A is B
- い - "adjective" - A is B

The truth is that all three of these types of engines can be used like adjectives.

Let's start with the first one, the one we refer to as an adjective in English, the い engine:
#+BEGIN_QUOTE
ぺんがあかい - Pen is red
#+END_QUOTE
An important note, あかい does not mean 'red', it means *is red*. あか means red.

If we swap the order of ぺんが and あかい then we can take this い engine, and now use it not as the primary engine, but as a secondary engine. This would not be a complete sentence however without a new engine, for example, a new (primary) い engine.
#+BEGIN_QUOTE
あかいぺんがちいさい - Red pen is small
#+END_QUOTE
This is simple enough, let's take a look at verbs.

Any う (verb) engine, in any tense can be used like an adjective:
#+BEGIN_QUOTE
しょうじょがうたった - Girl sang
#+END_QUOTE
#+BEGIN_QUOTE
うたったしょうじょが - The girl who sang (Note: this sentence is not yet complete, it lacks a primary engine).
#+END_QUOTE
#+BEGIN_QUOTE
うたったしょうじょがねている - The girl who sang is sleeping
#+END_QUOTE
# NOTE: There are some more examples given here but I'm not sure it's necessary to write them all down

Next, the noun engine:
#+BEGIN_QUOTE
いぬがやんちゃだ - The dog is naughty
#+END_QUOTE
We can turn やんちゃ into an adjective too, but there is one important thing to note. Just as we have to add だ to a noun, here we must add な to the noun. な is the connective form of だ. Don't be fooled by 'な-adjectives', they're simply nouns!
#+BEGIN_QUOTE
やんちゃないぬが - The dog who is naughty (Note: this sentence is not yet complete, it lacks a primary engine).
#+END_QUOTE
#+BEGIN_QUOTE
やんちゃないぬがねている - The dog who is naughty is sleeping
#+END_QUOTE

An important note is that we cannot do this with /all/ nouns, only nouns which are frequently used in an adjectival way. This group of nouns is what the are referred to as 'な-adjectives'. We can use all nouns as adjectives, but for the rest we need to use a different technique and for that we will have to learn about the の particle.

** The の carriage
The の particle, or the /possessive particle/ functions just like the English /'s/.
#+BEGIN_QUOTE
さくらのはな - Sakura's nose
#+END_QUOTE
#+BEGIN_QUOTE
わたしのはな - Me's (my) nose
#+END_QUOTE
Luckly in Japanese we don't have to worry about his/her/my/their, we just use の.

Because this is the /possessive particle/ we can use this in another slightly different way. あか has an /adjectival/ form in あかい, but not all colours have this form. The Japanese for pink, ピンクいる (lit: pink-colour) doesn't have an adjectival form in ピンクいろい, nor can we use it as a secondary engine with な. So what are we to do? Well we can use the の particle:
#+BEGIN_QUOTE
ピンクいる*の*どれすが - The pink dress (literally: The dress belonging to the class of pink things)
#+END_QUOTE
#+BEGIN_QUOTE
うさぎ*の*OSCAR - Oscar the rabbit (literally: Oscar belonging to the class of rabbit)
#+END_QUOTE

Just as before, there's no need to worry about misusing の and な, no-one listening is going to misunderstand what you're saying and it's a very typical beginner mistake to make.

Using these techniques we can make all kinds of sentences that can become very complex, especially with verbal adjectives in which we can use whole sentences in an adjectival manner.
* Lesson 7: Negative verbs and adjective "conjugations"
The fundamental basis of negatives is the adjective ない. This adjective means 'non-exist'. The word for exist (for any inanimate thing) is ある. If we want to say that something exists:
#+BEGIN_QUOTE
ぺんがある
#+END_QUOTE
But if we want to say that something doesn't exist we say:
#+BEGIN_QUOTE
ぺんがない
#+END_QUOTE
Now, why do we use a verb for being, and an adjective for non-being? This is something that happens all throughout Japanese, when we do something we use a verb, but when we don't do something we attach ない and are therefore using an adjective as the engine of the sentence. This has a very logical reason, when we *do* something, an action is taking place, and so we use a verb, but when we *don't do* it we are describing a state of non-action, so that's an adjective.

Above we have said 'There is no pen', how do we say 'This is not a pen'?
#+BEGIN_QUOTE
これわぺんがある - As for this, it's a pen
#+END_QUOTE
#+BEGIN_QUOTE
これわぺんではない - As for this, as for being a pen, it's not. (Note: で is the て-form of だ)
#+END_QUOTE

Now let's look at negative verbs. To make a verb negative we must attach ない to the あ-stem of the verb. How do we do this?

** The Japanese stem system
Note: these stems apply to Godan verbs. For Ichidan verbs we simply drop the る and add ない. Remember, all ichidan verbs end in る but not all る ending verbs are ichidan verbs.
#+BEGIN_QUOTE
たべる ー> たべない
#+END_QUOTE

Here is the kana-grid, presented on its side. Every verb ends in one of the う-row kana. (う-row kana that aren't used as verb endings have been removed).

| あ | い | *う* | え | お |
| か | き | *く* | け | こ |
| さ | し | *す* | せ | そ |
| た | ち | *つ* | て | と |
| な | に | *ぬ* | ね | の |
| ば | び | *ぶ* | べ | ぼ |
| ま | み | *む* | め | も |
| ら | り | *る* | れ | ろ |

As we can see there are four other ways in which the verb could end. These are the verb stems. For now we're only looking at the あ-stem as this is the one we need for the negative.

To from the あ-stem we simply shift the final kana from the う-row to the あ-row. There is one only exception and this is the only exception in the entire stem system. This exception is that う itself does not become あ but わ. This is because, take for example a verb like かう, かあ would not be as easy to say as かわ. Every other う-row kana is simply changed to its あ-row equivalent.

| _*わ*_ | い | *う* | え | お |
| _か_   | き | *く* | け | こ |
| _さ_   | し | *す* | せ | そ |
| _た_   | ち | *つ* | て | と |
| _な_   | に | *ぬ* | ね | の |
| _ば_   | び | *ぶ* | べ | ぼ |
| _ま_   | み | *む* | め | も |
| _ら_   | り | *る* | れ | ろ |

So to form the negative form of a verb convert it to the あ-stem and add ない.
#+BEGIN_QUOTE
かう ー> かわない
#+END_QUOTE
#+BEGIN_QUOTE
はなす ー> はなさない
#+END_QUOTE

** Negative adjectives (and adjective "conjugations")
The adjective stem is simple, just drop the い and add く. This is how we make the て form, あかい ー> あかくて, and it's also the way we make the negative, あかい ー> あかくない.

If we want to put an adjective into the past tense we drop the い and add かった.
#+BEGIN_QUOTE
こわい ー> こわかった - Was scary
#+END_QUOTE

Because ない is also an adjective, the past tense of it is just なかった.
# I need to find a font that is uniform width for Japanese and Latin
| Non-past             | Past                     |          |
|----------------------+--------------------------+----------|
| さくらがはしる       | さくらがはしった         | Positive |
| さくらがはし*ら*ない | さくらがはし*ら*なかった | Negative |

Now as we know さくらがはしる is not very natural Japanese, instead we would say さくらがはしっている. For this, all we need to do is put the いる into the past tense:
#+BEGIN_QUOTE
さくらがはしっている -> さくらがはしっていた - Sakura was running
#+END_QUOTE

** The only exceptions
There are only two real exceptions to what has been covered in this lesson. They are the helper verb ます which makes words formal by adding it to the い-stem of a verb. When we put ます into the negative it does not become まさない as we would expect, but becomes ません, because it is formal it is a bit old-fashioned and uses the old Japanese negative せん instead of ない.

The only other exception is いい (is good), which has an older form, which is still widely used in よい. When we morph いい it becomes よい again:
#+BEGIN_QUOTE
いい ー> よくない - Not-good
#+END_QUOTE
#+BEGIN_QUOTE
いい ー> よかった - Was-good
#+END_QUOTE

Note: よかった is a common phrase: ∅がよかった - /It was good (That went well, it turned out great etc.)/
