#+TITLE: Organic Japanese lesson notes
My follow-along notes from the Organic Japanese course on Youtube: [[https://www.youtube.com/playlist?list=PLg9uYxuZf8x_A-vcqqyOFZu06WlhnypWj]]

# TODO: Replace examples with tables
# ∅
* Lesson 1: The core Japanese sentence
Every Japanese sentence is fundamentally the same, they have the same core.

Every sentence is formed of two elements, (visualised as a train) they are the /carriage/ and /engine/.

In all languages there are only two kinds of sentence:
- A is B: Sakura is Japanese
- A does B: Sakura Walks

Sakura ga nihonjin da - Sakira is Japanese
Sakura ga aruku - Sakura walks

Going back to the train metaphor:
#+BEGIN_EXAMPLE
 /Carriage/      /Engine/
[Sakura *が*] [Nihonjin *だ*]
#+END_EXAMPLE

There is a third form of the Japanese sentence core sentence:
#+BEGIN_EXAMPLE
/Carriage/  /Engine/
[Pen *が*] [aka *い*] = Pen is red
#+END_EXAMPLE
# TODO: In which lesson?
This is similar, but not identical to an adjective. This will be discussed more later.

To recap, all of these sentences begin with the subject, they are connected with が, and the three /engines/ of the Japanese core sentence are:
- う - verb          - A does B
- だ - noun          - A is B
- い - /"adjective"/ - A is B

* Lesson 2
** The invisible が carriage
Last lesson we covered the が /carriage/. Part of the reason so many people struggle with Japanese is that, although we can always see the /engine/ of the sentence, we cannot always see the が carriage. Remember, the core of the Japanese sentence is formed of the が carriage and an engine.

The closest English equivalent to this invisible が carriage is 'it'. Here is an example English sentence:
#+BEGIN_QUOTE
The ball rolled down the hill. When the ball got to the bottom the ball hit a sharp stone and the ball was punctured and all the air came out of the ball.
#+END_QUOTE

This is not a sentence we would ever say in English, once we have established that we are talking about 'the ball' we would instead refer to the ball with it:
#+BEGIN_QUOTE
The ball rolled downm the hill. When it got to the bottom it hit a sharp stone and it was punctured and all the air came out of it.
#+END_QUOTE

If we were to completely omit /it/ the sentence would still be easy to understand, we don't /need/ to use this it marker each time, but English grammar *demands* it. Japanese does not, hence the 'invisible' が carriage.

'It' by itself doesn't really mean anything, we know what it means from context. If a child comes downstairs in the middle of the night and says /'Got really hungry'/, /'Came for something to eat'/ we understand that the child means /'I got really hungry'/ not /'The dog got really hungry'/. In English this isn't a proper sentence, but in Japanese it is.

All of the little pronouns I/it/we/he/they can all be replaced by the invisible が carriage; the *∅ pronoun*. It is important to remember that the carriage *is* still there.

One might say: ドリーだ meaning /'I am Dolly'/. The full sentence being: ∅がドリーだ.

By default 'I' is the default value of this /∅ pronoun/. However, if someone were introducing their daughter and said ドリーだ we would understand from context that ∅ meant this/she.

If I say 土曜日だ /'It is Saturday'/ it is clear that ∅ means /today/.

Each of these sentences are complete grammatical sentences with a subject marked by が and an engine, but in each of these cases the が carriage is just invisible. It *is* still there. This may seem to be arbitrary, or over-complicated but it saves a lot of grief later on to model sentences this way. Without this information as sentences become more complex they're going to seem increasingly vague and hard to understand.

** The を carriage
This carriage is formed of a noun and the particle を. The を particle marks the object of the sentence. The thing that some verb (the engine) is being done to (が marks the thing doing the verb). It is not part of the core sentence which is always formed of the が carriage and an engine.
#+BEGIN_EXAMPLE
/carriage/ /carriage/ /engine/
[わたしが]  [ケーキを]  [たべる]
    I        cake       eat
#+END_EXAMPLE

The core sentence here is 'I eat'. The extra carriage, the を carriage is telling us more about the engine. /What/ are we eating? We are eating cake.

Once again, we would often see this said as: ケーキをたべる. This is just another case with the invisible が carriage. We *cannot* have a sentence without a が, we *cannot* have a sentence without a doer.

When we are saying ケーキをたべる, what we are really saying is ∅がケーキをたべる. And the default value for ∅ is わたし: /I/.

* Lesson 3
** は particle secrets
The は particle can never be a part of the core Japanese sentence. It is neither the carriage we are saying something about, nor the engine, what we are saying about it. It isn't a carriage /outside/ of the core sentence either like the を particle is. The は particle is not part of the logical structure of the sentence.

は is a non-logical particle. In our train metaphor the は particle is a /flag/. It simply marks something as the topic of the sentence, but doesn't say anything about it.

An exact translation of the は particle would be 'As for x'. わたしは therefore means 'As for me', *not* 'I am' (わたしが).

A commonly mistranslated sentence is:
#+BEGIN_QUOTE
わたしは日本人だ - I am Japanese
#+END_QUOTE

If we look back at our train however we can see that something is missing:
#+BEGIN_EXAMPLE
  /flag/     /engine/
[わたし*は*] [日本人*だ*]
#+END_EXAMPLE

There is no が carriage. We don't know who the subject actually is. One may ask 'well why don't we just treat the は particle as if it is a carriage'. In this example it is obvious that the topic marked by は is the same as the subject marked by が, but there are many more cases where this is not true, leading to much confusion down the road. Let's look at a similar sentence. You are at a restaurant, the waitress is asking what you would like:
#+BEGIN_QUOTE
わたしはうなぎだ ー +I am an eel+
#+END_QUOTE

Treating は as 'I am' doesn't work. As we now know the default value of the ∅ pronoun is 'I', but in this context it's clear that we're talking instead about /what/ we want to eat. わたしはうなぎだ therefore means 'As for me, eel'.

** The に particle
The に particle marks the target (indirect object) of an engine. Along with the が and を we have a sort of /trio/ of logical /A does B/ sentences.

- が tells us who does the doing
- を tells us what it is done to
- に tells us what the ultimate target of that doing

#+BEGIN_QUOTE
わたしがぼーるをなげる - I threw the ball
#+END_QUOTE
The *core* sentence is 'I threw', and the extra carriage (を) tells us what we threw, the ball. We can add another carriage to tell us more about the engine:
#+BEGIN_QUOTE
わたしがぼーるをさくらになげる - I threw the ball at/to Sakura
#+END_QUOTE
Sakura is the destination, the target. It is important to note here that the logical particles tell us what is happened. The order of the words doesn't really matter the way it does in English.
#+BEGIN_QUOTE
わたしにさくらがぼーるをなげる - Sakura threw the ball at/to me.
#+END_QUOTE
#+BEGIN_QUOTE
ぼーるがわたしにさくらをなげる - The ball throws Sakura at me
#+END_QUOTE
Obviously this final example doesn't make any sense (although we might want to say something non-sensical like this in a fantasy novel or something) but we can say whatever we like in Japanese so long as we use the right logical particles.

Now let's introduce は:
#+BEGIN_EXAMPLE
  /flag/    /carriage/ /carriage/  /carriage/ /engine/
[わたし*は*]  [∅*が*]   [さくら*に*] [ぼーる*を*] [なげる]
#+END_EXAMPLE
As we know, even if the が carriage is invisible (or silent) this means 'As for me, (I) threw the ball at Sakura'. Now let's give the は /flag/ to the ball:
#+BEGIN_EXAMPLE
  /flag/      /carriage/ /carriage/   /carriage/ /engine/
[ぼーる*は*] [わたし*が*] [さくら*に*]  [∅*を*]    [なげる]
As for the ball, I threw *it* (the ball) at Sakura.
#+END_EXAMPLE
Note, this time the を carriage has become invisible, because what we're throwing is now marked by the は particle, ∅ here has taken the value of 'it'. Even without は we might already know what 'it' was that was thrown from context. The important thing to understand here is that as we change the logical particles from one noun to another we change the meaning of the sentence, but when we change the non-logical particle は from one noun to another it makes no difference to the logic of the sentence. It may make some difference to the emphasis, but it makes no difference to who is doing what or what they're doing it to.

* Lesson 4: Japanese past, present and future tenses
Up until now we've only been using one tense and that is the one presented by the plain dictionary form of verbs. To use natural sounding Japanese we need 3 tenses. In Japanese these are not the same past, present and future tenses we're familiar with from English.

The tense we have been using thus far is *not* the present tense. It is the /non-past/ tense. This non-past tense is actually very similar to the English non-past tense. What is the /English/ non-past tense? It is again the plain dictionary form of a verb. Eat, run, walk etc. It is unnatural in English to say 'I eat cake', to mean 'I am eating cake'. It is natural however to use the non-past tense to say 'Sometimes I eat cake' or, in the explictily future tense 'I will eat cake'. Japanese is just the same as English in this way. It is rare we use this form for talking about things actually happening right now, except in cases like literary descriptions.

Most of the time the Japanese non-past tense refers to future events. In fact, just as ∅ defaults to 'I', the non-past tense defaults to the future.
#+BEGIN_QUOTE
さくらが歩く - Sakura will walk
#+END_QUOTE
#+BEGIN_QUOTE
犬がたべる - dog will eat
#+END_QUOTE
The way we have been using this tense up until now, 'Sakura walks', is possible, but isn't the most natural way.

If we want to say something more natural like 'Sakura is walking' we must use the verb 'to be'[fn::In English the verb 'to be' is irregular and has multiple forms be/is/are/am: To /be/ walking, Sakura /is/ walking, not Sakura /be/ walking.], or in Japanese いる.
#+BEGIN_QUOTE
さくらが歩いている - Sakura is walking
#+END_QUOTE
#+BEGIN_QUOTE
犬がたべている - dog is eating
#+END_QUOTE
There is something here however that we haven't yet seen. In our train metaphor this is a secondary engine, here たべて which could be an engine in of itself, is helping (modifying) the main いる engine. Our core sentence is still the same, we have a が carriage and an engine, いる i.e. さくらがいる - Sakura is (existing). The secondary engine modifies いる telling us more about what state she is currently existing in, she is in the eating state. As we go further into Japanese we will see this secondary engine structure again and again.
#+BEGIN_EXAMPLE
/carriage/ /engine/ /engine/
 [犬*が*]   [たべて]  [いる] - dog is eating
#+END_EXAMPLE

Also, just as in English we don't say 'The dog is eat', we use a special form of the verb /eat/ => /eating/. In Japanese this is the て form. This is covered in the next lesson.

For the past tense of verbs instead of adding て to verbs we add た.
#+BEGIN_QUOTE
犬がたべた - The dog ate
#+END_QUOTE
The way in which we do this is exactly the same as the way in which we attach て and will be covered in the next lesson.

If we want to make it clear that we are talking about a future event we can add a time expression. By prefixing a sentence with あした (tomorrow), we can make it clear that what we will be doing, we will be doing tomorrow.
#+BEGIN_QUOTE
あした[∅が]ケーキをたべる - Tomorrow I will eat cake
#+END_QUOTE
Note how we simply preface the sentence with 'tomorrow', just like we would in English. This is the case with all /relative-time nouns/, yesterday, tomorrow, the day after tomorrow, next week, next month, next year.

For /non-relative/, i.e. /absolute/ time expressions we must use the に particle:
#+BEGIN_QUOTE
火曜日*に*[∅が]ケーキをたべる - On Tuesday I will eat cake
#+END_QUOTE
We must attach に in all the same places we would attach on/in/at in English. On Tuesday, in March, at 12 o'clock. Foruntately in Japanese we only need to use the one particle.


* Lesson 5: Japanese verb groups and て form
Japanese verbs fall into three groups: /Ichidan/, /Godan/, and /irregular/

The first group are /ichidan/ (lit: one level) verbs. Morphing these verbs is easy, we simply remove the る and add our new ending. Ichidan verbs can only end in either いる or える.

The second group is by far the largest, the /godan/ (lit: five level) verbs. This groups contains verbs that end in all of the possible verb endings: う つ る ー ぬ ぶ む ー く ぐ ー す. Each of these ending groups has its own way of being morphed, though although they're 'five level' verbs, two of the groups use the same method so we only need to learn 4 methods. Confusingly this means that godan verbs can end in いる or える, most of these will still be /ichidan/ verbs, and fortunately even if a verb is morphed incorrectly, you will probably still be understood.
- う つ る -> って
- ぬ ぶ む -> んで
- く/ぐ -> いて/いで (Note: this is the combined group)
- す -> して

There are only two irregular verbs, くる and する. いく, is partly irregular, but not completely.
- くる -> きて
- する -> して
- いく -> いって (+いいて+)
These are the only exceptions
