#+TITLE: Organic Japanese lesson notes
#+SUBTITLE: My follow-along notes from the Organic Japanese course on Youtube: [[https://www.youtube.com/playlist?list=PLg9uYxuZf8x_A-vcqqyOFZu06WlhnypWj]]

# ∅
* Lesson 1: The core Japanese sentence
Every Japanese sentence is fundamentally the same, they have the same core.

Every sentence is formed of two elements, (visualised as a train) they are the /carriage/ and /engine/.

In all languages there are only two kinds of sentence:
- A is B: Sakura is Japanese
- A does B: Sakura Walks

Sakura ga nihonjin da - Sakira is Japanese
Sakura ga aruku - Sakura walks

Going back to the train metaphor:
#+BEGIN_EXAMPLE
 /Carriage/      /Engine/
[Sakura *が*] [Nihonjin *だ*]
#+END_EXAMPLE

There is a third form of the Japanese sentence core sentence:
#+BEGIN_EXAMPLE
/Carriage/  /Engine/
[Pen *が*] [aka *い*] = Pen is red
#+END_EXAMPLE
# TODO: In which lesson?
This is similar, but not identical to an adjective. This will be discussed more later.

To recap, all of these sentences begin with the subject, they are connected with が, and the three /engines/ of the Japanese core sentence are:
#+BEGIN_EXAMPLE
- う - verb          - A does B
- だ - noun          - A is B
- い - /"adjective"/ - A is B
  #+END_EXAMPLE

* Lesson 2: Core secrets
** The invisible が carriage
Last lesson we covered the が /carriage/. Part of the reason so many people struggle with Japanese is that, although we can always see the /engine/ of the sentence, we cannot always see the が carriage. Remember, the core of the Japanese sentence is formed of the が carriage and an engine.

The closest English equivalent to this invisible が carriage is 'it'. Here is an example English sentence:

#+BEGIN_QUOTE
The ball rolled down the hill. When the ball got to the bottom the ball hit a sharp stone and the ball was punctured and all the air came out of the ball.
#+END_QUOTE

This is not a sentence we would ever say in English, once we have established that we are talking about 'the ball' we would instead refer to the ball with it:

#+BEGIN_QUOTE
The ball rolled downm the hill. When it got to the bottom it hit a sharp stone and it was punctured and all the air came out of it.
#+END_QUOTE

If we were to completely omit /it/ the sentence would still be easy to understand, we don't /need/ to use this it marker each time, but English grammar *demands* it. Japanese does not, hence the 'invisible' が carriage.

'It' by itself doesn't really mean anything, we know what it means from context. If a child comes downstairs in the middle of the night and says /'Got really hungry'/, /'Came for something to eat'/ we understand that the child means /'I got really hungry'/ not /'The dog got really hungry'/. In English this isn't a proper sentence, but in Japanese it is.

All of the little pronouns I/it/we/he/they can all be replaced by the invisible が carriage; the ∅ pronoun. It is important to remember that the carriage *is* still there.

One might say: ドリーだ meaning /'I am Dolly'/. The full sentence being: ∅がドリーだ.

By default 'I' is the default value of this *∅ pronoun*. However, if someone were introducing their daughter and said ドリーだ we would understand from context that ∅ meant this/she.

If I say 土曜日だ /'It is Saturday'/ it is clear that ∅ means /today/.

Each of these sentences are complete grammatical sentences with a subject marked by が and an engine, but in each of these cases the が carriage is just invisible. It *is* still there. This may seem to be arbitrary, or over-complicated but it saves a lot of grief later on to model sentences this way. Without this information as sentences become more complex they're going to seem increasingly vague and hard to understand.

** The を carriage
This carriage is formed of a noun and the particle を. The を particle marks the object of the sentence. The thing that some verb (the engine) is being done to (が marks the thing doing the verb). It is not part of the core sentence which is always formed of the が carriage and an engine.

#+BEGIN_EXAMPLE
/carriage/ /carriage/ /engine/
[わたしが]  [ケーキを]  [たべる]
     I        cake      eat
#+END_EXAMPLE

The core sentence here is 'I eat'. The extra carriage, the を carriage is telling us more about the engine. /What/ are we eating? We are eating cake.

Once again, we would often see this said as: ケーキをたべる. This is just another case with the invisible が carriage. We *cannot* have a sentence without a が, we *cannot* have a sentence without a doer.

When we are saying ケーキをたべる, what we are really saying is ∅がケーキをたべる. And the default value for ∅ is わたし: /I/.
