My follow-along notes from the Organic Japanese course on Youtube: [[https://www.youtube.com/playlist?list=PLg9uYxuZf8x_A-vcqqyOFZu06WlhnypWj]]

# TODO: Replace examples with tables
# ∅
* Lesson 1: The core Japanese sentence
Every Japanese sentence is fundamentally the same, they have the same core.

Every sentence is formed of two elements, (visualised as a train) they are the /carriage/ and /engine/.

In all languages there are only two kinds of sentence:
- A *is* B: Sakura is Japanese
- A *does* B: Sakura Walks

#+BEGIN_QUOTE
Sakura ga nihonjin da - Sakura is Japanese
#+END_QUOTE
#+BEGIN_QUOTE
Sakura ga aruku - Sakura walks
#+END_QUOTE

Going back to the train metaphor:
| Carriage    | Engine        |
| Sakura *が* | Nihonjin *だ* |

| Carriage | Engine   |
| Pen *が* | Aka *い* |

To recap, all of these sentences begin with the subject, they are connected with が, and the three /engines/ of the Japanese core sentence are:
- う - verb          - A does B
- だ - noun          - A is B
- い - /"adjective"/ - A is B

* Lesson 2: Invisible が and the を-particle
** The invisible が carriage
Part of the reason so many people struggle with Japanese is that, although we can always see the /engine/ of the sentence, we cannot always see the が carriage. Remember, the core of the Japanese sentence is formed of the が carriage and an engine.

The closest English equivalent to this invisible が carriage is 'it'. Here is an example English sentence:
#+BEGIN_QUOTE
The ball rolled down the hill. When the ball got to the bottom the ball hit a sharp stone and the ball was punctured and all the air came out of the ball.
#+END_QUOTE

This is not a sentence we would ever say in English, once we have established that we are talking about 'the ball' we would instead refer to the ball by 'it':
#+BEGIN_QUOTE
The ball rolled down the hill. When it got to the bottom it hit a sharp stone and it was punctured and all the air came out of it.
#+END_QUOTE

If we were to completely omit 'it' the sentence would still be easy to understand, we don't *need* to use this it marker each time, but English grammar *demands* it. Japanese does not, hence the 'invisible' が carriage.

'It' by itself doesn't really mean anything, we know what it means from context. If a child comes downstairs in the middle of the night and says /'Got really hungry'/, /'Came for something to eat'/ we understand that the child means /'I got really hungry'/ not /'The dog got really hungry'/. In English this isn't a proper sentence, but in Japanese it is.

All of the little pronouns I/it/we/he/they can all be replaced by the invisible が carriage; the /∅ pronoun/. It is important to remember that the carriage *is still there*.

One might say: 「ドリーだ」 meaning /'I am Dolly'/. The full sentence being: 「∅がドリーだ」.

By default 'I' is the default value of this /∅ pronoun/. However, if someone were introducing their daughter and said 「ドリーだ」 we would understand from context that ∅ meant this/she.

If I say 「土曜日だ」 - /'It is Saturday'/ it is clear that 「∅が」 is /today/.

Each of these sentences are complete grammatical sentences with a subject marked by が and an engine, but in each of these cases the が carriage is just invisible. It *is* still there. This may seem to be arbitrary, or over-complicated but it saves a lot of grief later on to model sentences this way. Without this information as sentences become more complex they're going to seem increasingly vague and hard to understand.

** The を-particle
This carriage is formed of a noun and the particle を. The を particle marks the object of the sentence. The thing that some verb (the engine) is being done to (が marks the thing doing the verb). It is not part of the core sentence which is always formed of the が carriage and an engine.

| Carriage   | Carriage   | Engine   |
| わたし*が* | ケエキ*を* | たべ*る* |
| I          | cake       | eat      |

The core sentence here is 'I eat'. The extra carriage, the を carriage is telling us more about the engine. /What/ are we eating? We are eating cake.

Once again, we would often see this said as 「ケーキをたべる」. This is just another case of the invisible が carriage. We *cannot* have a sentence without a が - we *cannot* have a sentence without a doer.

When we are saying 「ケーキをたべる」, what we are really saying is 「∅がケーキをたべる」. And the default value for ∅ is 「わたし」 - 'I'.

* Lesson 3: は-particle and に-particle
** は particle
The は-particle can never be a part of the core Japanese sentence. It is neither the carriage we are saying something about, nor the engine i.e. what we are saying about it. It isn't a carriage /outside/ of the core sentence either like the を-particle is. The は-particle is not part of the logical structure of the sentence.

は is a non-logical particle. In our train metaphor the は-particle is a /flag/. It simply marks something as the topic of the sentence, but doesn't say anything about it.

An exact translation of the は particle would be 'As for /x/'. 「わたしは」 therefore means 'As for me', *not* 'I am' (わたしが).

A commonly mistranslated sentence is:
#+BEGIN_QUOTE
わたしは日本人だ - I am Japanese
#+END_QUOTE

If we look back at our train however we can see that something is missing:
| Flag       | Engine   |
| わたし*は* | 日本人だ |

There is no が carriage. We don't know who the subject actually is. One may ask /'well why don't we just treat the は particle as if it is a carriage'/. In this example it is obvious that the topic marked by は is the same as the subject marked by が, but there are many more cases where this is not true, leading to much confusion down the road. Let's look at a similar sentence. You are at a restaurant, the waitress is asking what you would like:
#+BEGIN_QUOTE
わたしはうなぎだ - +I am an eel+
#+END_QUOTE

Treating は as 'I am' doesn't work. As we now know the default value of the ∅ pronoun is 'I', but in this context it's clear that we're talking instead about /what/ we want to eat. 「わたしはうなぎだ」 therefore means 'As for me, eel'.

** The に particle
The に-particle marks the target (indirect object) of an engine. Along with the が and を we have a sort of /trio/ of logical /A does B/ sentences:
- が tells us who does the doing
- を tells us what it is done to
- に tells us what the ultimate target of that doing

#+BEGIN_QUOTE
わたしがぼーるをなげる - I threw the ball
#+END_QUOTE
The *core* sentence is 'I threw', and the extra carriage (を) tells us what we threw i.e. the ball.

We can add another carriage to tell us more about the engine:
#+BEGIN_QUOTE
わたしがぼーるをさくら*に*なげる - I threw the ball at/to Sakura
#+END_QUOTE
Sakura is the destination, the target. It is important to note here that the logical particles tell us what happened. The order of the words doesn't really matter the way it does in English.
#+BEGIN_QUOTE
わたし*に*さくらがぼーるをなげる - Sakura threw the ball at/to me.
#+END_QUOTE
#+BEGIN_QUOTE
ぼーるがわたし*に*さくらをなげる - The ball throws Sakura at me
#+END_QUOTE
Obviously this final example doesn't make any sense (although we might want to say something nonsensical like this in a fantasy novel or something) but we can say whatever we like in Japanese so long as we use the right logical particles.

Now let's introduce は:
| flag       | carriage |   | carriage   |   | carriage   |   | engine   |
| わたし*は* | ∅*が*    |   | さくら*に* |   | ぼーる*を* |   | なげ*る* |
As we know, even if the が carriage is invisible (or silent) this means 'As for me, (I) threw the ball at Sakura'. Now let's give the は /flag/ to the ball:
| flag       | carriage   | carriage   | carriage | engine   |
| ぼーる*は* | わたし*が* | さくら*に* | ∅*を*    | なげ*る* |
As for the ball, I threw it (the ball) at Sakura.

This time the を carriage has become invisible, because what we're throwing is now marked by the は particle, ∅ here has taken the value of 'it'. Even without は we might already know what 'it' was that was thrown from context. The important thing to understand here is that as we change the logical particles from one noun to another we change the meaning of the sentence, but when we change the non-logical particle は from one noun to another it makes no difference to the logic of the sentence. It may make some difference to the emphasis, but it makes no difference to who is doing what or what they're doing it to.

* Lesson 4: Japanese past, present and future tenses
Up until now we've only been using one tense and that is the one presented by the plain dictionary form of verbs. To use natural sounding Japanese we need 3 tenses. In Japanese these are not the same past, present and future tenses we're familiar with from English.

The tense we have been using thus far is *not* the present tense. It is the /non-past/ tense. This non-past tense is actually very similar to the English non-past tense. What is the /English/ non-past tense? It is again the plain dictionary form of a verb. Eat, run, walk etc. It is unnatural in English to say 'I eat cake', to mean 'I am eating cake'. It is natural however to use the non-past tense to say 'Sometimes I eat cake' or, in the explicitly future tense 'I will eat cake'. Japanese is just the same as English in this way. It is rare we use this form for talking about things actually happening right now, except in cases like literary descriptions.

Most of the time the Japanese non-past tense refers to future events. In fact, just as ∅ defaults to 'I', the non-past tense defaults to the future.
#+BEGIN_QUOTE
さくらが歩く - Sakura will walk
#+END_QUOTE
#+BEGIN_QUOTE
犬がたべる - Dog will eat
#+END_QUOTE
The way we have been using this tense up until now i.e. /'Sakura walks'/, is possible, but isn't the most natural way.

If we want to say something more natural like /'Sakura is walking'/ we must use the verb /'to be'/[fn::In English the verb 'to be' is irregular and has multiple forms be/is/are/am: To /be/ walking, Sakura /is/ walking, not Sakura /be/ walking.], or in Japanese 「いる」:
#+BEGIN_QUOTE
さくらが歩いている - Sakura is walking
#+END_QUOTE
#+BEGIN_QUOTE
犬がたべている - Dog is eating
#+END_QUOTE
There is something here however that we haven't yet seen. In our train metaphor this is a /secondary engine/, here 「たべて」 which could be an engine in of itself, is helping (modifying) the main 「いる」 engine. Our core sentence is still the same, we have a が carriage and an engine, 「いる」 i.e. 「さくらがいる」 - Sakura is (existing). The secondary engine modifies 「いる」 telling us more about what state she is currently existing in, she is in the eating state. As we go further into Japanese we will see this secondary engine structure again and again.
| carriage | secondary-engine | engine |
| 犬*が*   | たべて           | い*る* |

Also, just as in English we don't say 'The dog is eat', we use a special form of the verb /eat/ => /eating/. In Japanese this is the て form. This is covered in the next lesson.

For the past tense of verbs instead of adding て to verbs we add た.
#+BEGIN_QUOTE
犬がたべた - The dog ate
#+END_QUOTE
The way in which we do this is exactly the same as the way in which we attach て and will be covered in the next lesson.

If we want to make it clear that we are talking about a future event we can add a time expression. By prefixing a sentence with あした (tomorrow), we can make it clear that what we will be doing, we will be doing tomorrow.
#+BEGIN_QUOTE
あした∅がケーキをたべる - Tomorrow I will eat cake
#+END_QUOTE
Note how we simply preface the sentence with 'tomorrow', just like we would in English. This is the case with all /relative-time nouns/, 'yesterday', 'tomorrow', 'the day after tomorrow', 'next week', next month', 'next year'.

For /non-relative/, i.e. /absolute/ time expressions we must use the に-particle:
#+BEGIN_QUOTE
火曜日*に*∅がケーキをたべる - On Tuesday I will eat cake
#+END_QUOTE
We must attach に in all the same places we would attach on/in/at in English. 'On Tuesday', 'in March', 'at 12 o'clock'. Fortunately in Japanese we only need to use the one particle.

* Lesson 5: Japanese verb groups and て-form
Japanese verbs fall into three groups: /Ichidan/, /Godan/, and /irregular/

The first group are /ichidan/ (lit: one level) verbs. Morphing these verbs is easy, we simply remove the る and add our new ending. Ichidan verbs can only end in either いる or える.

The second group is by far the largest, the /godan/ (lit: five level) verbs. This group contains verbs that end in all of the possible verb endings: う つ る ー ぬ ぶ む ー く ぐ ー す. Each of these ending groups has its own way of being morphed, though although they're 'five level' verbs, two of the groups use the same method so we only need to learn 4 methods. Confusingly this means that godan verbs can end in いる or える, most of these will still be /ichidan/ verbs, and fortunately even if a verb is morphed incorrectly, you will probably still be understood.
- う つ る -> って
- ぬ ぶ む -> んで
- く/ぐ -> いて/いで (Note: this is the combined group)
- す -> して

There are only two irregular verbs, くる and する. いく, is partly irregular, but not completely.
- くる -> きて
- する -> して
- いく -> いって (+いいて+)
These are the only exceptions
* Lesson 6: Japanese "adjectives"
** い-adjectives, verb adjectives, and な-adjectives
Japanese adjectives are not the same as English adjectives. As we have learned Japanese sentences come in three kinds, depending on the type of engine they have. As a reminder they are:
- う - verb - A *does* B
- だ - noun - A *is* B
- い - "adjective" - A *is* B

The truth is that all three of these types of engines can be used like adjectives.

Let's start with the first one, the one we refer to as an adjective in English, the い-engine:
#+BEGIN_QUOTE
ぺんがあかい - Pen is red
#+END_QUOTE
An important note, 「あかい」 does not mean 'red', it means 'is red'. 「あか」 means red.

If we swap the order of 「ぺんが」 and 「あかい」 then we can take this い-engine, and now use it not as the primary engine, but as a secondary engine. This would not be a complete sentence however without a new engine, for example, a new (primary) い engine.
#+BEGIN_QUOTE
あかいぺんがちいさい - Red pen is small
#+END_QUOTE
This is simple enough, let's take a look at verbs.

Any う (verb) engine, in any tense can be used like an adjective:
#+BEGIN_QUOTE
しょうじょがうたった - Girl sang
#+END_QUOTE
#+BEGIN_QUOTE
うたったしょうじょが - The girl who sang (Note: this sentence is not yet complete, it lacks a primary engine).
#+END_QUOTE
#+BEGIN_QUOTE
うたったしょうじょがねている - The girl who sang is sleeping
#+END_QUOTE
# NOTE: There are some more examples given here but I'm not sure it's necessary to write them all down

Next, the noun engine:
#+BEGIN_QUOTE
いぬがやんちゃだ - The dog is naughty
#+END_QUOTE
We can turn 「やんちゃ」 into an adjective too, but there is one important thing to note. Just as we have to add だ to a noun, here we must add な to the noun. な is the connective form of だ. Don't be fooled by 'な-adjectives', they're simply nouns!
#+BEGIN_QUOTE
やんちゃないぬが - The dog who is naughty (Note: this sentence is not yet complete, it lacks a primary engine).
#+END_QUOTE
#+BEGIN_QUOTE
やんちゃないぬがねている - The dog who is naughty is sleeping
#+END_QUOTE

An important note is that we cannot do this with /all/ nouns, only nouns which are frequently used in an adjectival way. This group of nouns is what the are referred to as 'な-adjectives'. We can use all nouns as adjectives, but for the rest we need to use a different technique and for that we will have to learn about the の particle.

** The の-particle
The の particle, or the /possessive particle/ functions just like the English /'s/.
#+BEGIN_QUOTE
さくら*の*はな - Sakura's nose
#+END_QUOTE
#+BEGIN_QUOTE
わたし*の*はな - Me's (my) nose
#+END_QUOTE
Luckily in Japanese we don't have to worry about his/her/my/their, we just use の.

Because this is the /possessive particle/ we can use this in another slightly different way. 「あか」 has an /adjectival/ form in 「あかい」, but not all colours have this form. The Japanese for pink, 「ピンクいる」 (lit: pink-colour) doesn't have an adjectival form in 「ピンクいろい」, nor can we use it as a secondary engine with な. So what are we to do? Well we can use the の-particle:
#+BEGIN_QUOTE
ピンクいる*の*どれすが - The pink dress (literally: The dress belonging to the class of pink things)
#+END_QUOTE
#+BEGIN_QUOTE
うさぎ*の*OSCAR - Oscar the rabbit (literally: Oscar belonging to the class of rabbit)
#+END_QUOTE

Just as before, there's no need to worry about misusing の and な, no-one listening is going to misunderstand what you're saying and it's a very typical beginner mistake to make.

Using these techniques we can make all kinds of sentences that can become very complex, especially with verbal adjectives in which we can use whole sentences in an adjectival manner.

* Lesson 7: Negatives and adjective "conjugations"
** Negative nouns
The fundamental basis of negatives is the adjective 「ない」. This adjective means 'non-exist'. The word for exist (for any inanimate thing) is ある. If we want to say that something exists:
#+BEGIN_QUOTE
ぺんがある
#+END_QUOTE
But if we want to say that something doesn't exist we say:
#+BEGIN_QUOTE
ぺんがない
#+END_QUOTE
Now, why do we use a verb for being, and an adjective for non-being? This is something that happens all throughout Japanese, when we do something we use a verb, but when we don't do something we attach ない and are therefore using an adjective as the engine of the sentence. This has a very logical reason, when we *do* something, an action is taking place, and so we use a verb, but when we *don't do* it we are describing a state of non-action, so that's an adjective.

Above we have said 'There is no pen', how do we say 'This is not a pen'?
#+BEGIN_QUOTE
これはぺんがある - As for this, it's a pen
#+END_QUOTE
#+BEGIN_QUOTE
これはぺんではない - As for this, as for being a pen, it's not. (Note: で is the て-form of だ)
#+END_QUOTE

** Negative verbs and the Japanese stem system
Now let's look at negative verbs. To make a verb negative we must attach 「ない」 to the あ-stem of the verb. How do we do this?

Note: these stems apply to Godan verbs. For Ichidan verbs we simply drop the る and add 「ない」. Remember, all ichidan verbs end in る but not all る ending verbs are ichidan verbs.
#+BEGIN_QUOTE
たべる ー> たべない
#+END_QUOTE

Here is the kana-grid, presented on its side. Every verb ends in one of the う-row kana. (う-row kana that aren't used as verb endings have been removed).

| あ | い | *う* | え | お |
| か | き | *く* | け | こ |
| さ | し | *す* | せ | そ |
| た | ち | *つ* | て | と |
| な | に | *ぬ* | ね | の |
| ば | び | *ぶ* | べ | ぼ |
| ま | み | *む* | め | も |
| ら | り | *る* | れ | ろ |

As we can see there are four other ways in which the verb could end. These are the verb stems. For now we're only looking at the あ-stem as this is the one we need for the negative.

To from the あ-stem we simply shift the final kana from the う-row to the あ-row. There is one only exception and this is the only exception in the entire stem system. This exception is that う itself does not become あ but わ. This is because, take for example a verb like 「かう」, 「かあ」 would not be as easy to say as 「かわ」. Every other う-row kana is simply changed to its あ-row equivalent.
| **わ** | い | *う* | え | お |
| *か*   | き | *く* | け | こ |
| *さ*   | し | *す* | せ | そ |
| *た*   | ち | *つ* | て | と |
| *な*   | に | *ぬ* | ね | の |
| *ば*   | び | *ぶ* | べ | ぼ |
| *ま*   | み | *む* | め | も |
| *ら*   | り | *る* | れ | ろ |

So to form the negative form of a verb convert it to the あ-stem and add ない.
#+BEGIN_QUOTE
かう ー> かわない
#+END_QUOTE
#+BEGIN_QUOTE
はなす ー> はなさない
#+END_QUOTE

** Negative adjectives and adjective "conjugations"
The adjective stem is simple, just drop the い and add く. This is how we make the て form, 「あかい」 ー> 「あかくて」, and it's also the way we make the negative, 「あかい」 ー> 「あかくない」.

If we want to put an adjective into the past tense we drop the い and add かった.
#+BEGIN_QUOTE
こわい ー> こわかった - Was scary
#+END_QUOTE

Because 「ない」 is also an adjective, the past tense of it is just 「なかった」.
| Non-past             | Past                     |          |
|----------------------+--------------------------+----------|
| さくらがはしる       | さくらがはしった         | Positive |
| さくらがはし*ら*ない | さくらがはし*ら*なかった | Negative |

Now as we know 「さくらがはしる」 is not very natural Japanese, instead we would say 「さくらがはしっている」. For this, all we need to do is put the 「いる」 into the past tense:
#+BEGIN_QUOTE
さくらがはしっている -> さくらがはしっていた - Sakura was running
#+END_QUOTE

** The only exceptions
There are only two real exceptions to what has been covered in this lesson. They are the helper verb 「ます」 which makes words formal by adding it to the い-stem of a verb. When we put 「ます」 into the negative it does not become 「まさない」 as we would expect, but becomes 「ません」, because it is formal it is a bit old-fashioned and uses the old Japanese negative 「せん」 instead of 「ない」.

The only other exception is いい (is good), which has an older form, which is still widely used in よい. When we morph いい it becomes よい again:
#+BEGIN_QUOTE
いい ー> よくない - Not-good
#+END_QUOTE
#+BEGIN_QUOTE
いい ー> よかった - Was-good
#+END_QUOTE
- Note: 「よかった」 is a common phrase: 「∅がよかった」 - /It was good (That went well, it turned out great etc.)/

* Lesson 8: Location, purpose and transformation (に and へ particles).
We already know that in a logical sentence the に-particle marks the ultimate target of an action. If we are going somewhere, or sending something somewhere, or putting something somewhere, we use に.
#+BEGIN_QUOTE
∅がみせ*に*いく - (I) will go to the shop
#+END_QUOTE
We can also mark a more subtle kind of target:
#+BEGIN_QUOTE
∅がみせ*に*たまごをかい*に*いく - (I) will go to the shop to buy eggs
#+END_QUOTE
- Note: かい is the い stem of かう, to buy.

If we recall, the logical particles (が, に, を) can only mark nouns. The い stem of a verb is the equivalent noun form of it. Just as in English 'I like swimming', /swimming/ is a noun, 'I go to the shop for the purpose of buying eggs', this /buying/ is also a noun.

に gives us the target of an action in the literal sense, and also the target in a volitional sense, i.e. the aim of our action.

As well as identifying a place we will go to, に can also specify a place we are currently at:
#+BEGIN_QUOTE
∅がみせ*に*いる - (I am) at the shop
#+END_QUOTE
This に is still marking a target, just not a future target. In order for something to be somewhere it must've gotten there, and so に specifies the target of some past action. We can also use this for inanimate objects:
#+BEGIN_QUOTE
ほんは∅がテーベルのうえ*に*ある - As for the book, (it) exists (is) on-at the table.
#+END_QUOTE
- Note: うえ is a noun, meaning the on/top of something.

Finally, に can also mark a transformation. If /a/ becomes /b/, then に also marks /b/, the thing a is becoming.
# I think the actual sentence is missing here
#+BEGIN_QUOTE
さくらは∅がかえる*に*なった - Sakura became a frog
#+END_QUOTE
Of course this example is a bit of a joke, but there are of course various every day things that become other things. This form of expression is also used much more often in Japanese than in English.
#+BEGIN_QUOTE
ことし∅が十八さいになる - This year (I) become 18 years old
#+END_QUOTE
#+BEGIN_QUOTE
あとで∅がくもりになる - Later (it (the weather) will) become cloudy
#+END_QUOTE

For adjectives things work slightly differently:
#+BEGIN_QUOTE
さくらがうつくしい - Sakura is beautiful
#+END_QUOTE
If we want to say 'Sakura became beautiful' we can't use に because うつくしい isn't a noun, (referring back to our metaphor), it's not a carriage, it's an engine. All we need to do is turn the adjective into its stem by removing い and adding く refering back to lesson 7:

#+BEGIN_EXAMPLE
The adjective stem is simple, just drop the い and add く. This is how we make the て form, 「あかい」 ー> 「あかくて」, and it's also the way we make the negative, 「あかい」 ー> 「あかくない」.
#+END_EXAMPLE
#+BEGIN_QUOTE
さくらがうつくしくなった - Sakura became beautiful
#+END_QUOTE

** The へ car
Note: when used as a particle へ is pronounced え.

This is a very simple particle, it duplicates a single use of に. When we say /a is going to b/ we can freely substitute に with へ. This is *all* is can do, it cannot even mark the case where something /is/, only where it is /going/.
* Lesson 8b: Japanese particles explained
A logical particle tells us how the sentence logically holds together. It tells us who does what to whom with what, when and where.

は is a non-logical particle, it simply identifies the topic, but doesn't say anything about it. Other particles like と are /alogical/, they aren't simply markers. In the case of と the particle 'ands' two nouns together. It is therefore doing something in the sentence, in our train metaphor it is joining a noun-carriage to another carriage, inheriting its logical particle, but has no function of its own.
#+BEGIN_QUOTE
さくら*と*メイリー*が*あるいていた - Sakura *and* Mary were walking
#+END_QUOTE

Logical particles *always* attach to a noun. If we see a logical particle attached to anything else then we know that that word is functionally a noun.

The noun and the particle attached to it are an inseparable pair. We must view the two together, they are a question and an answer which form a fundamental unit of the Japanese sentence.

There cannot be a sentence without が, even if sometimes you can't see it. が can work in A is B sentences, descriptive sentences. The other particles can *only* work in A does B sentences, that is sentences with a verb engine.
- が - Who (or what) did it?
- を - Whom was it done to?
- に - Where did they go?/Where are they?
- へ - What direction?
- で - Where was it done? With what was it done?
#+BEGIN_QUOTE
∅がこうえん*に*いる - I am in the park
#+END_QUOTE
#+BEGIN_QUOTE
∅がこうえん*で*あそんでいる - I am playing in the park
#+END_QUOTE
Remember, 「あそんで」 is the て form of 「あそぶ」 and is a secondary engine, modifying 「いる」. /I am/ -> /I am playing/.
#+BEGIN_QUOTE
∅がこうえん*に*いく - I go to the park
#+END_QUOTE
#+BEGIN_QUOTE
∅がバス*で*こうえんいいく - I go to the park by bus
#+END_QUOTE
If we say 'I went by bus' or 'I ate with chopsticks' we use で for the thing we did it with, the means by which we performed the action.
* Lesson 9: 'Ego-centrism' and expressing desire
** Ego-centrism
English is an /ego-centric/ language. Japanese is a more /animist/ language. What this means is that English always wants a person, preferably /I/, but if not I then someone else, or perhaps it will settle for an animal, but always wanting an animate being to be acting. Japanese is not this way:
#+BEGIN_QUOTE
わたしはコーヒがすきだ
#+END_QUOTE
A textbook would translate this as 'I like coffee'. 'I like coffee' very well might be the English equivalent for this simple phrase, but it is not what this sentence means, and it is not what this structure of sentence means.

The が is marking the coffee. The coffee is the actor in this sentence, not I. It's not 'I like coffee', I am not /liking/ it. But 'As for me, coffee is likeable/pleasing'.

The English 'I like coffee' is an /A does B/ sentence. The Japanese is an /A is B/ sentence.

すき is a *noun*. An adjectival noun, but still a noun. It is not a verb like in English.

If this sentence were 1-1 with the common English meaning given, then every single part of it would be miss-described by the particles.
- は does not mark an actor
- が does not mark an object
- だ does not mark a verb

#+BEGIN_QUOTE
わたしはほんがわかる
#+END_QUOTE

** Expressing desire
#+BEGIN_QUOTE
わたしは(optional)こねこがほしい - As for me, a kitten is wanted
#+END_QUOTE
「ほしい」 is often translated in English as 'want', but again, it is not a verb, it is an adjective. Again, /I/ is not the actor of the sentence, it is the cat, and it is the cat that is wanted, not 'I want a cat'.

In Japanese the way that wanting to *do* something is expressed is different to the way that wanting to *have* something is expressed.

The way this is done is with the い-stem again. To express that we want to do something, we must add the /helper adjective/ 「たい」 to the い-stem of the verb. 「たい」 doesn't mean 'want' in the English sense, it can't, again, because *want* is a verb, and 「たい」 is an *adjective*.
#+BEGIN_QUOTE
(わたしは)クレープガたべたい
#+END_QUOTE
The common English translation for this is 'I want to eat crepes', but as we see the pattern is just the same as in the other cases, the desire-ability of the crepes is not a verb, it is an adjective.

There is no truly good translation of this into English. We shouldn't be thinking in terms of 'awkward English' or 'natural English' when it comes to constructing and understanding these sentences. We should be thinking in terms of Japanese. The 'awkward' translations of the Japanese are only there to give a *grasp* of the structure of Japanese.

Now, what if we took this sentence, 「わたしはクレープガたべたい and removed the optional parts so that we just had 「たべたい? In this case, the meaning of the sentence would be what the common English translation is. ∅ defaults to I, and so the translation is 'I eat-wanting am' -> 'I am wanting to eat' -> 'I want to eat'. Because there is no eat-inducing subject here, the want to eat is attributed directly to I.

So what is 「たい」? Is it an adjective describing the /condition of something/ making you want to do something, or is it an adjective describing /my desire/? Well, it can be either. This is very common throughout Japanese. 「こわい」 can mean scared or scary:
#+BEGIN_QUOTE
おばけがこわい - Ghosts are scary
#+END_QUOTE
#+BEGIN_QUOTE
∅がこわい - I am scared
#+END_QUOTE
This isn't confusing because が tells us what to do.

** A final note to help keep things clear
We cannot use these adjectives of desire (or any emotion) about anyone other than ourselves. If we say 「たべたい」 and there is no context to give the subject, then we must be talking about ourselves, and never the person we are speaking to or anyone else. Japanese simply doesn't allow us to use 「たい」 or 「こわい」 or 「ほしい」 or anything else about anyone other than ourselves.

If we wanted to say that someone else wants something then, because Japanese is such a logical language it doesn't allow us to say something that we cannot know for sure. One thing that we cannot know for sure is someone's inner feelings. We might think that Sakura wants to eat cake, but we can't know for sure. So if I want to talk about her desire to eat cake, we can't just use 「たい」. We need to add to 「たい」 (or 「こわい」, or 「ほしい」 or anything else) the helper verb がる.

To do this we take the い off of the adjective and add the helper verb 「がる」.
- たがる
- こわかる
- ほしがる

「がる」 means 'to show signs of', 'to look as if it's the case'.
#+BEGIN_QUOTE
さくらがケーキをほしがる - Sakura is showing signs of wanting cake
#+END_QUOTE
Even if Sakura has actually told me she wants cake, we must still use 「がる」. All I know is what she's said, I still don't know her feelings absolutely.

Why do we use a verb for other people and an adjective for ourselves? I can't describe someone-else's feelings because I don't know about them, I can only describe their actions, and their actions are a verb.
* Lesson 10: Japanese "conjugation" and potential form
What textbooks typically refer to as "conjugations" are really just /helper-verbs/ attached to the four verb stems.

We have already looked at the helper-adjectives 「ない」 and 「たい」, as well as the helper-verb 「がる」. Now for the potential helper-verb which attaches to the え-stem of a verb.
| あ | い | *う* | *え* | お |
| か | き | *く* | *け* | こ |
| さ | し | *す* | *せ* | そ |
| た | ち | *つ* | *て* | と |
| な | に | *ぬ* | *ね* | の |
| ば | び | *ぶ* | *べ* | ぼ |
| ま | み | *む* | *め* | も |
| ら | り | *る* | *れ* | ろ |

The potential helper verb has two forms, for godan verbs 「る」, and for ichidan verbs 「られる」.

There are only two exceptions, 「くる」 and 「する」.
#+BEGIN_QUOTE
くる -> こられる
#+END_QUOTE
#+BEGIN_QUOTE
する ー> できる
#+END_QUOTE

There is only one difficult spot with the potential form, and it is similar to the issue from the previous lesson.
#+BEGIN_QUOTE
わたしは(optional)ほんがよめる - As for me, the book is readable
#+END_QUOTE
A common translation of this would be 'I can read the book', however again the が is on the book, not on I. If we wanted to say 'I can read the book', the book would need to be marked by を as it is the target of our reading, and 'I' would have to be marked by が as I is the actor.
#+BEGIN_QUOTE
わたしがほんをよめる - I can read the book
#+END_QUOTE
This is perfectly fine, but it's not what is usually done. Remember, Japanese is not /ego-centric/.

As we're using a helper-verb, the past, non-past, negative-past and negative-non-past conjugation rules are the same as regular verbs, for 「あるける」 (can walk):
- あるける - non-past
- あるけた - past
- あるけない - negative-non-past
- あるけなっかた - negative-past
* Lesson 11: Compound sentences, くれる, あげる, and more て form uses
#+BEGIN_QUOTE
ある 日 アリスは 川の そばに いた。
#+END_QUOTE
そば is a noun meaning 'beside', so 川のそば means beside the river.

ある means 'a certain', so ある日 means 'on a certain day'. Notice that here we're using a verb as an adjective, as we have described in previous lessons. 本がある (a book exists) -> ある本が (an existing/a certain book). Note also that this is the same as how we use might use Today, Yesterday, Tomorrow etc. but not how we might use 'On Saturday'.
#+BEGIN_QUOTE
On a certain day, alice was beside a river.
#+END_QUOTE

#+BEGIN_QUOTE
おねえちゃんは つまらない 本を よんで いて あそんで くれなかった。
#+END_QUOTE
よむ (read) -> よんでいる (reading) -> よんでい*て* - We have put the いる into the て form, why have we done this?
#+BEGIN_QUOTE
おねえちゃんは つまらない 本を よんで いる - Big sister is reading an uninteresting book.
#+END_QUOTE
This by itself is a complete clause (sentence), by turning the engine of the sentence (いる) into the て form we're saying that something else is going to follow this clause, i.e. 'and'.
#+BEGIN_QUOTE
おねえちゃんは つまらない 本を よんで いて - Big sister is reading an uninteresting book and...
#+END_QUOTE
#+BEGIN_QUOTE
あそんで くれなかった
#+END_QUOTE
あそぶ is to play. This has also been put into the て form. Here we have another use of the て form, let's examine. くれる means to 'give downwards' i.e. as Japanese is so polite we place ourselves below others, so someone else is giving us something. あげる to contrast is to 'give upwards' i.e. to give to someone else. What is being given? In this case the thing being given is what is attached to it via the て form, i.e. 'playing'. Specifically, she is not giving the act of playing to Alice. In Japanese we frequently use 'give' for actions, for doing something for our benefit as well as for literally 'giving' nouns. If someone does something for our benefit, we turn that action to the て form, and attach it to くれる. If we do something for someone else's benefit, we turn that action to the て form, and attach it to あげる.
#+BEGIN_QUOTE
Big sister is reading an uninteresting book and didn't play with Alice (didn't play for Alice's benefit).
#+END_QUOTE

Note again our two clauses:
#+BEGIN_QUOTE
おねえちゃんは つまらない 本を よんで いて
#+END_QUOTE
#+BEGIN_QUOTE
あそんで くれなかった
#+END_QUOTE
For the first clause we do not know what in what tense the action is taking place. In English we would place the tense marker on both clauses, in Japanese we only do this at the end. よんで いて could mean 'is reading' and it could mean 'was reading'. Because くれなかった is in the past tense, then the entire sentence is in the past tense.
* Lesson 12: と quotation particle and compound verbs and compound nouns
#+BEGIN_QUOTE
「おもしろい ことが ない」 と アリスは 言った
#+END_QUOTE
- もの - thing concrete
- こと - thing abstract

#+BEGIN_QUOTE
「おもしろい ことが ない」- No interesting (abstract) thing exists (Nothing interesting is going on here)
#+END_QUOTE
#+BEGIN_QUOTE
アリスは 言った - Alice said
#+END_QUOTE
The intesting thing to note is the particle between these two, the と particle. There are two と particles, one means 'and', and one marks a quotation. When we quote someone as saying something or as thinking something we use this と particle. We also use these square brackets which are the equivalent of English quotation marks, but in speech we cannot see these, so we also use と (and clearly use と in writing regardless also).
#+BEGIN_QUOTE
「おもしろい ことが ない」 と アリスは 言った - Nothing interesting is happening said Alice
#+END_QUOTE

#+BEGIN_QUOTE
そのとき、白い ウサギが とおり すぎた。
#+END_QUOTE
- そのとき - That time, in this sentence it is used to mean 'just at that moment' (just as Alice said that)
- とおる - pass through
- すぎる - exceed, go beyond

とおりすぎる is doing something very interesting. It is attaching the い stem of one verb, to another verb to give it extra meaning. We will see this a lot throughout Japanese. Connecting とおる and すぎる, 'pass through' and 'go beyond' means 'passing by'.
#+BEGIN_QUOTE
そのとき、白い ウサギが とおり すぎた。 - At that moment a white rabbit passed by
#+END_QUOTE

#+BEGIN_QUOTE
ふつうの ウサギでは なくて、 チョッキを きて いる ウサギ だった。
#+END_QUOTE
#+BEGIN_QUOTE
ふつうの ウサギでは なくて - Not an ordinary rabbit
#+END_QUOTE
# TODO: Add a note here about では
#+BEGIN_QUOTE
チョッキを きて いる ウサギ だった。- It was a rabbit that was wearing a vest (it was a wearing a vest rabbit)
#+END_QUOTE


#+BEGIN_QUOTE
ウサギは かいちゅうどけいを 見て 「おそい!おおい!」と言って、はしり だした。
#+END_QUOTE
- かいちゅうどけい is the combination of かいちゅう (inside pocket) and どけい (watch) meaning pocketwatch. An interesting note here is that とけい becomes どけい (I may write up a full explanation of why anothe time).

#+BEGIN_QUOTE
「おそい!おおい!」と
#+END_QUOTE
What と does structurally, is it takes whatever it marks which could be a whole paragraph, or just two short words like this, or anything with all sorts of grammar going on, it takes whatever it marks as a quotation and turns it into a single noun. Going forward we will find that this is used not only to mark things people say and people think, but to mark all sorts of things. This と structure can therefore make a quotation act as a modifier to whatever follows, in this cast it is modifying 言う (to say), or to think or feel, but could be many things.

Note: As there must be a ∅ somewhere the rabbit is either saying 'it's late' or 'I'm late'.
Note also, we don't need to use ウサギは again as it is already marked in the first half of the sentence.
#+BEGIN_QUOTE
はしり だした - Run + Take out = Broke into a run (started to run). In this sense だした means modifies the verb to mean the action 'erupted'.
#+END_QUOTE
#+BEGIN_QUOTE
ウサギは かいちゅうどけいを 見て 「おそい!おおい!」と言って、はしり だした。 - The rabbit looked at his watch and said 'I'm late! I'm late' and broke out into a run.
#+END_QUOTE
Note: all the uses of て-form to mark 'and'.
#+BEGIN_QUOTE
「ちょっと まって ください」 と アリスは よんだ。
#+END_QUOTE
#+BEGIN_QUOTE
「ちょっと まって ください」 と - Please wait a little
#+END_QUOTE
#+BEGIN_QUOTE
「ちょっと まって ください」 と アリスは よんだ。
#+END_QUOTE
よんだ is the て-form of よぶ (to shout/call).
Note: Both よむ and よぶ conjugate to よんだ in the て form, fortunately it's not likely that we'll get these two verbs mixed up.
#+BEGIN_QUOTE
「ちょっと まって ください」 と アリスは よんだ。 - Please wait a minute called Alice
#+END_QUOTE

#+BEGIN_QUOTE
でも ウサギは ピョンピョンと はしり つづけた。
#+END_QUOTE
- でも - but
- はしる + つづける = Continued running (running continued).
- ピョンピョン - The sound of a small thing jumping along

Once again we're using the quotation particle と to describe the way in which it run, it ran in the way it sounds, it ran like a small thing jumping along (note there are no quotation marks around this).
* Lesson 13: Passive "conjugation" - Not passive and not a conjugation
The real name for the 'passive conjugation' is the /Receptive helper verb/.

The receptive helper verb is れる for godan verbs and られる for ichidan verbs, and attaches to the あ-stem of another verb.
| *あ* | い | *う* | え | お |
| *か* | き | *く* | け | こ |
| *さ* | し | *す* | せ | そ |
| *た* | ち | *つ* | て | と |
| *な* | に | *ぬ* | ね | の |
| *ば* | び | *ぶ* | べ | ぼ |
| *ま* | み | *む* | め | も |
| *ら* | り | *る* | れ | ろ |
Remember! う becomes わ, not あ.

The receptive helper verb means /receive/ or /get/, we're receiving/getting the action that the helper verb is attached to
#+BEGIN_QUOTE
さくらがしか*ら*れた - Sakura scolded-got - Sakura got scolded/Sakura received a scolding
#+END_QUOTE

Note, the receptive helper verb and the modified verb have different actors. The sentence is not Sakura scolds, someone else (we don't know who) is scolding Sakura, but Sakura is the one in the act of receiving the scolding. This is not the same with all helper verbs.

The receiver is not always a person:
#+BEGIN_QUOTE
水がの*ま*れた - Water got drunk
#+END_QUOTE
Even if we add a doer of the drinking, the water is still the actor of the sentence.
#+BEGIN_QUOTE
水がいぬにの*ま*れた - Water got drunk by (a) dog
#+END_QUOTE
いぬに is modifying のむ.

Why is the dog being marked by に? Let's look at a larger sentence:
#+BEGIN_QUOTE
さくらは だれかに かばんが ぬす*ま* れた - As for Sakura, someone-by bag stolen-got - As for Sakura, (her) bag got stolen by someone
#+END_QUOTE

Who is the actor? It's not Sakura, she's marked by は. It's not the 'someone' as they're marked by に. The bag is the actor of the sentence, the bag /did/ 'got'.

What is に doing here? に marks the ultimate target of an action. So what is the target of getting stolen? To whome is the stolen item going? It is the 'someone' who stole it.

Note: Cure Dolly uses a /push-pull/ analogy here, which I think is unnecessary.

** The nuisance receptive
#+BEGIN_QUOTE
さくらが だれかに かばんを ぬす*ま* れた
#+END_QUOTE
Here the core of the sentence is now 'Sakura got'. What did she get? She got the unfortunate (nuisance) action of だれかに かばんを ぬすむ, someone stealing (her) bag. /Sakura got her bag stolen by someone/ *not* /Sakura's bag got stolen by someone/.
* Lesson 14: Adverbs and も-particle
#+BEGIN_QUOTE
アリスは とび 上がって、 ウサギの 後を 追った。
#+END_QUOTE
- とび上がって = とぶ (jump/fly) + 上がる (rise up) = Jump up
- 後を追った = 後 (after) + 追う (follow) = Follow after/follow behind

Note how we are following ウサギの後 - /the rabbit's after/behind/. We are following the back of the rabbit.
#+BEGIN_QUOTE
アリスは とび 上がって、 ウサギの 後を 追った。 - Alice jumped up and followed after the rabbit
#+END_QUOTE

---

#+BEGIN_QUOTE
しゃべる ウサギを 見た ことが ない。
#+END_QUOTE
Here しゃべる is being used as an adjective just as any verb can be. しゃべるウサギ - Talkative/talking rabbit.

見た is the passed tense of 見る to see. It is modifying こと, an abstract thing, meaning 'The fact of having seen'. 見たことがない means 'The fact of having seen doesn't exist'.

The talking rabbit is the object of the engine of the sentence, 'The fact of having seen'. So: 'The fact of having seen a talking rabbit doesn't exist' -> (Alice) had never seen a talking rabbit. This is another example of the un-egocentric nature of Japanese; Alice is not the actor of this sentence, it is the 'thing' that does not exist.

---

#+BEGIN_QUOTE
ウサギは 早く 走って、 急に ウサギの 穴に とび 込んだ。
#+END_QUOTE
#+BEGIN_QUOTE
ウサギは 早く 走って、
#+END_QUOTE
- 早い - fast/early
- 走る - run
早い is an adjective. If we want to say the rabbit is fast we simply say ウサギが早い. But if we want to say that the rabbit's *movement* is fast we must use an adverb. In Japanese we can turn any adjective into an adverb by simply removing the い and replacing it with く. 早い -> 早く.

Note again how our verb 走る has been converted to the て form signifying an 'and'.

#+BEGIN_QUOTE
急に ウサギの 穴に とび 込んだ。
#+END_QUOTE
- ウサギの 穴に - Here we aren't saying 'The rabbit's hole' but 'a hole of the variety rabbit'.
- とび 込む = とぶ (jump) + こむ (Squeeze (?) into) = Jump into

急に is another way of forming an adverb. 急 is a noun meaning 'suddenly'. We can form an adjective from a noun by adding に.

#+BEGIN_QUOTE
ウサギは 早く 走って、 急に ウサギの 穴に とび 込んだ。- The rabbit ran quickly and jumped into a rabbit hole.
#+END_QUOTE

** The も flag
#+BEGIN_QUOTE
アリス*も* ウサギの 穴に とび こんだ。 - Alice also jumped into the rabbit hole.
#+END_QUOTE

も is another non-logical topic-marking particle. も marks the topic of the sentence in the same way that は does. The difference is that while は can mark the topic of the sentence and *can* also change the topic of the sentence, も decalares the topic of the sentence but can *only* change the topic of the sentence. We cannot use も unless we are changing the topic of the sentence. Up until this point the topic of our conversation has been the rabbit, now we are switching to talk about Alice.

When we change topic with も we're saying that the comment about the previous topic (the rabbit and that it jumped) is the same as our new topic (Alice). When we change the topic with は we are doing the opposite, we are drawing a distinction between the two.

---

#+BEGIN_QUOTE
穴の 中は たて穴 だった。 アリスは すぐ下に 落さた。- The inside of the hole was a vertical hole. Alice fell straight (directly) down the hole.
#+END_QUOTE

#+BEGIN_QUOTE
でも、 おどろいたことに ゆっくり ゆっくり 落さた。 - But, the surprising thing was that she slowly slowly fell/ But, surprisingly she fell slowly.
#+END_QUOTE
- おどろいたこと doesn't mean 'A surprised thing', it means 'the surprising thing' (surprisingly). The に attached is again to turn it into an adverb. So: 'She fell surprisingly'. Of course, it isn't surprising that she fell, but it is suprising that she fell ゆっくり ゆっくり (slowly slowly).
- ゆっくり is slightly unusual in that it is fundamentall a noun, but we can use it as an adjective without adding に to it. We will see ゆっくり very often.

* Lesson 15: Transitivity
/Transitive/ and /intransitive/ aren't as big of a misnomer as some of the things we've seen so far, but a better pair of terms would be /Self-move/ and /Other-move/.

In japanese, a move-word 動詞 (どうし) is a word that denotes an action of a movement. So a self-move verb is a verb that moves itself. If I 'stand-up' that's a self-move action. But throwing a ball is an 'other-move' action, one is not throwing themselves, they are throwing a ball. It's as simple as that.

Japanese has a lot of pairs of words, these could be called forms, or just closely related words, that give the self-move and other-move variations of the verb. For example:
- 出る (でる) - leave, exit, come out - Self-move
- 出す (だす) - take out, bring out - Other-move

Most of the time we can tell which is a self-move word and which is an other-move word by following a few simple rules.

The first thing to know is that there is a root word for self-move and a root word for other-mode:
- ある - Be - Self-move
- する - Do - Other-move

Knowing this there are three laws of move-word pairs.
1. す and せる (え-stem) ending verbs are other-move
2. あ-stem + る (aru) ending verbs are self-move
3. え-stem + る (eru) flip self/other-move either way

Honorary members of the す family:
- む -> める is always other-move
- ぶ -> べる is always other-move
- つ -> てる is always other-move

The only wildcards left are:
- く/ぐ -> ける/げる
- う ー> える
- Some る-ending verbs not covered by the first two laws

Is there anything we can do to simplify this: える version have the opposite of the standard word.

* Lesson 16: て-みる, 'try doing', や-particle, から-particle, exclusive-'and'
#+BEGIN_QUOTE
落ちる 間に ひもが たっぷり あって まわりを ゆっくり 見まわせた。
#+END_QUOTE
- 落ちる - fall
- 間に - during
- ひま - spare time
- たっぷり - in plenty
- まわり - surroundings
- 見まわす - look around

| verb working as adjective for 間 |        |           | adverbial noun not needing に |             |
| Secondary-*う* engine            | noun   | core      | adverb                        | *う*-engine |
| 落ち*る*                         | 間*に* | ひま*が*  | たっぷり                      | あって      |
| fall                             | during | free time | plentifully                   | existed-and |

#+BEGIN_QUOTE
まわりを ゆっくり 見まわせた。
#+END_QUOTE
- 回る - Go around (self-move)
- 回す - Send/Make go around (other-move)
- まわり - Noun form of 回る meaning 'surroundings', not the act of going around

# It may be worth using screenshots of the videos
|       | い-stem info |                | い-stem info          | まわる + potential helper + past tense |
| core  | object       | adverbial noun | secondary-*う* engine | *う*-engine                            |
| ∅*が* | まわり*を*   | ゆっくり       | 見                    | まわせた                               |
| Alice | surroundings | leisurely      | lookage-              | around-send-could                      |

#+BEGIN_QUOTE
落ちる 間に ひもが たっぷり あって まわりを ゆっくり 見まわせた。- While (she was) falling a lot of spare time existed, and (she) could look leisurely around her surroundings.
#+END_QUOTE

---

#+BEGIN_QUOTE
まずは、下を 見てみた けど、暗すぎて 何も 見えなかった。
#+END_QUOTE
- まず - first
- 下 - down
- 暗い - dark
- すぎる - exceed
- 何も - even-anything

見てみた: When we add みる to the て-form of another verb we're saying to 'try' doing something. We're literally saying 'do it and see'. 食べてみろ = Try eating (it) and see. やってみろ = do and see (give it a try). 見てみた = Take a look and see.

#+BEGIN_QUOTE
まずは、下を 見てみた
#+END_QUOTE
| Relative time expression | core  | object | secondary-*う* engine | *う*-engine |
| まず*は*                 | ∅*が* | 下を   | 見て                  | 見た        |
| first of all             | Alice | down   | look-                 | tried       |

#+BEGIN_QUOTE
暗すぎ*て* - (it was) dark exceeded-and - It was too dark and therefore
#+END_QUOTE

#+BEGIN_QUOTE
何も 見えなかった - even anything as for (it) did-not-do-see-able - It was too dark to see anything
#+END_QUOTE

---

#+BEGIN_QUOTE
その後、穴の まわりを 見て、目に 止まるのは ぎっしり ならんだ とだな や 本だな だった。
#+END_QUOTE

#+BEGIN_QUOTE
その後、穴の まわりを 見て - After that she looked at the surroundings of the hole and...
#+END_QUOTE

#+BEGIN_QUOTE
目に 止まるのは - Eye-at as for stopped-thing - The thing that stopped her eye - The thing that caught her eye
#+END_QUOTE

# There are some notes here about the use of の but I feel relatively familiar with that already.

#+BEGIN_QUOTE
その後、穴の まわりを 見て、目に 止まるのは - After that she looked at the surroundings of the hole and the thing that caught her eye was...
#+END_QUOTE

#+BEGIN_QUOTE
ぎっしり ならんだ とだな や 本だな だった。- tightly lined-up cupboards-and bookshelves-was
#+END_QUOTE

*The や-particle*

When putting to clauses together we use the て-form as an equivalent to 'and'. When putting two things together we can use the と (exclusive 'and') and や (non-exclusive 'and') particles.

---

#+BEGIN_QUOTE
たなの 一つから びんを 取り下した。- (She) shelve's one-from jar take-lowered - From one of the shelves she took down a jar.
#+END_QUOTE

* Lesson 17: Form Japanese: です/ます + volitional
ます is a (helper) verb that attaches to the い stem of another verb. It doesn't change the meaning of the verb in anyway, it just makes it formal. ます is highly irregular:
- The past tense is normal, it ends just like any す verb - ました
- The past tense is not ませない, it is ません - This is the only verb that does this in modern Japanese
- The negative past is ませんでした

です is the formal version of だ and works exactly the same aside from one quirk, unlike with だ which we do not attach to adjectives, we do attach です in formal speech. It doesn't mean or do anything, but it's done all the same.

A useful note, we can use ません and ないです interchangeably:
- さくらが話しません
- さくらが話しないです

*The volitional form*

The volitional form is one of the few uses of the お-stem. The godan volitional helper is just う, attached to the お stem it simply lengths the お sound. The ichidan form is to as usual remove the る, and add よう.

The volitional form of ます and です are ましょう and でしょう.

| あ | い | *う* | え | *お* |
| か | き | *く* | け | *こ* |
| さ | し | *す* | せ | *そ* |
| た | ち | *つ* | て | *と* |
| な | に | *ぬ* | ね | *の* |
| ば | び | *ぶ* | べ | *ぼ* |
| ま | み | *む* | め | *も* |
| ら | り | *る* | れ | *ろ* |

Volition means will, the volitional form expresses or invokes the will of the speaker. The most usual use of it is setting the will of a group of people in a particular direction. いきましょう = Let's go.

There are many uses of the volitional form in combination with various particles but they will be covered in due time. One of note for now is the volitional copula だろう / でしょう which when added to any ordinary sentence adds the extra meaning of /probably/, i.e. it adds doubt/conjecture.
- 赤いでしょう - Probably red
- さくらがくるでしょう - Sakura's probably coming.

* Lesson 18: Trying to do something; って = は? として、 と言う/という、 と する、 おう と する、 っていう
** Try - と する
#+BEGIN_QUOTE
山にのぼろうとする - Try to climb the mountain
#+END_QUOTE
- のぼる = Climb
- Note: に is normal here because we are climbing to the /target/ of the summit.

Why does this mean 'try'? A precise translation may be derived from のぼろう - have the will to climb, and する to do. I have the will to climb the mountain, and I will do it, (but I may not have the ability). Hence, /try/.

** How we regard something - と する

See again how we're using the と quotation particle once again. と is encapsulating, not the words or thoughts of someone, but the meaning of 「山にのぼろう」 and putting that meaning into action (する).

Another example:
#+BEGIN_QUOTE
ホッとする
#+END_QUOTE
- ホッ is the sound effect for a sigh of relief

We aren't saying here that someone breathed a sigh of relief. What we're saying is that they /enacted what was expressed by the sound effect/ i.e. They were relieved. In 山にのぼろうとする we're enacting the feeling of setting out to climb the mountain.

#+BEGIN_QUOTE
∅が さくらを *日本人と* する - We Sakura "Japanese person" enact - We assume/take Sakura to be Japanese
#+END_QUOTE
We are thinking/acting according what is expressed by the quote.

Compare this with:
#+BEGIN_QUOTE
∅が さくらを *日本人に* する - We turned Sakura into a Japanese person
#+END_QUOTE

#+BEGIN_QUOTE
かばんを *まくらと* する - Use bag as a pillow
#+END_QUOTE
Not literally: turn bag into a pillow.

** See something in the light of being something - と して
The closest equivalent to this in English is 'as'. i.e. 'My opinion /as/ a private person'.
#+BEGIN_QUOTE
会長*として* - As President...
#+END_QUOTE

We can also use it as 'for':
#+BEGIN_QUOTE
アメリカジン*として*小さい - She's small for an American. (As an American, she's small).
#+END_QUOTE

** As a quotation -  と言う/という
The most basic thing that can follow と is 言う in which case it can be used as a literal quotation of something that's been said (as we've already seen) but can also be used as a way of saying how something is said or what it's called:
#+BEGIN_QUOTE
ふしぎの国のアリスという本 - The book called 「ふしぎの国のアリス」
#+END_QUOTE
- Note: という is usually written in Kana when it precedes something

という can be reduced down as far as just って. という -> っていう -> って:
#+BEGIN_QUOTE
ふしぎの国のアリスっていう本 - The book called 「ふしぎの国のアリス」
#+END_QUOTE
#+BEGIN_QUOTE
ふしぎの国のアリスって本 - The book called 「ふしぎの国のアリス」
#+END_QUOTE

** って as は
Remember the は particle is the topic marking particle:
#+BEGIN_QUOTE
さくらは ∅が 日本人だ - As for Sakura, (she) is a Japanese person
#+END_QUOTE
#+BEGIN_QUOTE
さくらって ∅が 日本人だ - Speaking of Sakura, (she) is a Japanese person
#+END_QUOTE
This is a very casual use, we can't use という in place of は but we can use って. The point is that this is still very logical.

* Lesson 19: Causative + 'causative passive'
The /causative helper verb/ indicates that we are causing someone to do the verb to which is is attached.

The /receptive helper verb/ indicates receiving the action to which it is attached.

The causative and the receptive both attach to the あ-stem of a verb.
- Causative: せる/させる
- Receptive: れる/られる

| *わ* | い | *う* | え | お |
| *か* | き | *く* | け | こ |
| *さ* | し | *す* | せ | そ |
| *た* | ち | *つ* | て | と |
| *な* | に | *ぬ* | ね | の |
| *ば* | び | *ぶ* | べ | ぼ |
| *ま* | み | *む* | め | も |
| *ら* | り | *る* | れ | ろ |

# TODO: Is this true for all helper verbs?
It is important to understand that the verb and the helper verb always have different subjects
#+BEGIN_QUOTE
水が 犬に 飲む れた - The water got drunk by the dog (receptive)
#+END_QUOTE
- Core action: verb れる (get/receive), actor 水 (water)
  + Secondary action: verb 飲む (drink), actor 犬 (dog)
    - Implicit sub-clause: 犬が 飲んだ

#+BEGIN_QUOTE
さくらが だれかに かばんを ぬすま れた - Sakura got her bag stolen by someone (receptive)
#+END_QUOTE
- Core action: verb れる (get/receive), actor さくら
  + Secondary action: object かばん (bag), actor だれか (someone)
    - Implicit sub-clause: だれかが かばんを ぬすんだ

#+BEGIN_QUOTE
∅が 犬を 食べ させた - I caused the dog to eat (causative)
#+END_QUOTE
- Core action: verb させる (cause), actor ∅ (I)
  + Secondary action: verb たべる (eat), actor 犬 (dog)
    - Implicit sub-clause: 犬が 食べた

せる/させる can mean to /compel/make/force/, or it can mean to /allow/. But it can also mean neither of those. The best way to translate it is with the rather non-native sounding 'cause'. 'I caused the dog to eat' doesn't mean 'I forced the dog to eat', it just means that I did something that had the result of the dog eating, whether that be intentional, accidental, or forceful.

Sometimes the person or thing we are causing to do something can be marked by を and sometimes it can be marked by に. Remember the particles are always consistent. If we are forcing someone to do something, then we're treating them like an object (を), if we're treating them as a target, then this is more mutual and goes with /allowing/ over /compelling/ and so に.

That said the use of を and に is not the main indicator of if we mean allowing or compelling. There is no precise English analogy with the causative helper verb, so trying to determine if it means exactly cause or exactly allow is misguided, remember, it can mean neither. It's sort of a sliding scale between the two, more subtle. Beyond that, when the action that is being compelled has itself an を marked object we can see that in the sub(ordinate) sentence the meat is the object of the dog's action, and the dog is the thing that is being caused to do the action:
#+BEGIN_QUOTE
∅が犬に にくを 食べ させた - I caused the dog to eat meat
#+END_QUOTE
- Core action: verb させる (cause), actor ∅ (I)
  + Secondary action: verb たべる (eat), actor 犬 (dog)
    - Implicit sub-clause: 犬が にくを 食べた

に expresses relation to core clause. を expresses relation to sub clause.

In these types of sentences Japanese does not allow us to use the を particle twice. If we could use を twice then in some sentences we might end up with some doubt as to which を marks the object associated with 食べる and which を marks the object associated with せる/させる.

** Causative receptive (causative passive)
Causative-receptive (what most call the causative passive) means to get made to do. Remembering that helper verbs are ichidan verbs, to add the receptive helper verb to the causative helper verb we simple remove the る and add られる:
- せる/させる - る + られる = せられる/させられる

We now have three verbs in a sentence:
#+BEGIN_QUOTE
わたしは ∅が ブロコリを 食べ(1) させ^2 られた^2 - I got^3 compelled^2 to eat^1 broccoli
#+END_QUOTE
- Core action: verb られる (get), actor ∅ (I)
  + Secondary action: verb させる (compel), actor unspecified
    - Tertiary action: verb 食べる (eat), actor ∅ (I)

Note: The first and third actor are always the same. The second actor always different.
* Lesson 20: Sore/Sono/Sonna/Sou etc. Directional Words
# TODO: Re-title this?
こ そ あ ど words initially simply mark physical locations, but then expands out to more subtle and metaphorical uses. This is common because all languages use physical metaphors to express abstract concepts.

The most basic meaning:
| ここ           | そこ                              | あそこ     | どこ   |
| Here (near me) | There (near you/a little way off) | Over there | Where? |
- Often ここ means the speaker's place and そこ means the listener's place
- Often あそこ means away from both the speaker and the listener

** れ-group (nouns)
The れ group act as nouns.

| これ | それ | あそれ             | どれ         |
| This | That | That (other there) | Which thing? |

These can get confused with the の-group as in English we use the same word for both of these types of words.

** の-group (adjectivals)
The の group act as adjectives.

| これ                 | それ                  | あそれ                       | どれ           |
| This-something       | That-something        | That-something (other there) |                |
| described as near me | described as near you | described as over there      | how-described? |

れ means a being, it refers to a thing. の is used to make adjectivals and descriptors:
#+BEGIN_QUOTE
これは (∅が) ペンだ - As for here-thing (it) pen-is - The thing here is a pen
#+END_QUOTE
#+BEGIN_QUOTE
この ペンは (∅が) 赤い - Here's pen as for (it) red-is - The pen that is here is red
#+END_QUOTE

** な-group (real adjectives)
The な-group act as real adjectives

| こな      | そな      | あそな    | どな       |
| Like this | Like that | Like that | Like what? |

The な used for adjectival nouns descriptive of a thing's qualities. Distance is often conceptual, no physical. i.e. How far the thing is from what we're talking about or the present-circumstance.
#+BEGIN_QUOTE
こんあ食べ物 = Food like this
#+END_QUOTE
#+BEGIN_QUOTE
そんあことがひどい - A thing like that is cruel
#+END_QUOTE

These are essentially comparing-adjectives. Saying that something is like something either in physical space or in a conceptual way.

** う/あ-group
Lengthening the final sound of こ/そ/あ/ど is talking about the way something is/happens.

#+BEGIN_QUOTE
∅がそうです - It (the fact/situation) is that way = That's right
#+END_QUOTE
#+BEGIN_QUOTE
そうせる - Do like that
#+END_QUOTE
#+BEGIN_QUOTE
こうせる - Do like this
#+END_QUOTE
#+BEGIN_QUOTE
どうせる - Do it like how?
#+END_QUOTE

#+BEGIN_QUOTE
どうすればいい - In what way if I act will be good?
#+END_QUOTE
- すれば is the conditional form of する

#+BEGIN_QUOTE
そういうこと - That way say matter (condition/thing) - Thus-described matter - That kind of thing
#+END_QUOTE
#+BEGIN_QUOTE
どういうこと - What way said matter (condition/thing) - What is going on here?
#+END_QUOTE
The いう here is not referring to the fact we've said anything. The いう refers to the description of the thing.
* Lesson 21: Te oku/te aru
#+BEGIN_QUOTE
その びんいは ラベルが 貼って あって 「オレンジ•マーマレード」と 書いて あった
#+END_QUOTE
#+BEGIN_QUOTE
その びんいは ラベルが 貼って あって - A label was pasted to the bottle
#+END_QUOTE
貼って ある is something not yet covered. We've used the て-form of a verb + いる meaning to be in the state of doing that verb. て ある also means to be in the state of that verb, however there is a difference:
#+BEGIN_QUOTE
窓が開いている - The window is open
#+END_QUOTE
#+BEGIN_QUOTE
窓が開けてある - The window is open
#+END_QUOTE
What is the difference? いる simply means is open, however ある carries another implication. Notice the use of the other-move verb in ある and the self-move verb in いる. 開けてある therefore signals that the window is open *because* someone opened it.

Notice how we're using いる, the verb for animate objects to describe the openness of an inanimate object. Because we have used the self-move verb the inanimate object is an honorary 'willed being' with a state of its own. In the example with ある the state has been caused externally, and so the window maintains its inanimateness.

#+BEGIN_QUOTE
その びんいは ラベルが 貼って あって - The jar existed in the state of having a label stuck to it and...
#+END_QUOTE

#+BEGIN_QUOTE
「オレンジ•マーマレード」と 書いて あった - (it) was in the state of having 'Orange marmalade' written on it
#+END_QUOTE

** ておく
/Skipping ahead a little/ Alice realises that the marmalade jar is in fact empty. What is she to do with it? She doesn't want to drop it, what will she do?
#+BEGIN_QUOTE
[アリスが びんを] うまく とだなの 一つく 通りすがりに 置いて* おいた* - She skilfully in passing put the jar into one of the cupboards
#+END_QUOTE
- * Same word used twice, helper usually written in kana alone
- うまく - skilfully
- とだな - cupboard
- 通りすがり - in passing
- 置く - place/put

The second おく here (ておく) is in a sense the second half of てある:
#+BEGIN_QUOTE
窓が開けてある - Exist in the state of having been made open
#+END_QUOTE
#+BEGIN_QUOTE
窓を開けてあく - Open the window so that it remains in the state of openness. Establish the window as being in the state of openness
#+END_QUOTE
In many cases this is used to mean 'doing something in advance' but it is not the only meaning, as we see here. What is literally means is putting the action in place.
* Lesson 22: Te-wa, te-mo - Topic/comment magic
#+BEGIN_QUOTE
でも、びんは 空っぽ だった - But the jar was empty
#+END_QUOTE
---
#+BEGIN_QUOTE
アリスは 空っぽの びん*でも*、下へ 落としては 悪いと 思った
#+END_QUOTE
The で here is the て form of だ and it is attached to も, the inclusive /and/ particle and the reverse subject particle of は:
#+BEGIN_QUOTE
∅が 空っぽの びんでも - It empty jar-is as-much-as
#+END_QUOTE
- も = as-much-as i.e. 'even though'
The て-form + topic-marker combination forms a complete logical clause that is subordinate to (requiring comment from) the following clause
#+BEGIN_QUOTE
∅が 空っぽの びんでも - Even though it was an empty jar...
#+END_QUOTE

  # TODO: There is a も-combinations video suggested here that I may want to add if it doesn't come up later in the playlist
This is a new usage of も, there are many similar usages of this particle:
- いちま円もかかた掛かる - He took as much as 10,000 yen
- ケエキを食べてもいい - Is it alright if I eat this cake? lit. If I go as far as to eat the cake is that alright?

#+BEGIN_QUOTE
下へ 落としては 悪いと 思った
#+END_QUOTE
落としては now we have て from + は topic marker. While も is the additive, including particle, は is the subtractive, excluding particle. So, while も means 'as much as', は means 'as little as'. We tend to use でも in positive contexts, and では in negative contexts. Often this ては gets contracted into just ちゃ.

We can use ては as the connector between two clauses, and it implies that the second clause is unwanted:
#+BEGIN_QUOTE
雨が 降っ*ては* ： ∅が こうえんい 行けない - Rain falls and (negative comment expected) : we park-to can-go-not
#+END_QUOTE
This is much the same as how も is followed by a comment, here we follow は with a comment explaining why the rain falling is a bad thing.
#+BEGIN_QUOTE
∅が いもうとと けんかし*ては* ： ははに しかられた - I sister-with quarrelled-and (negative result) : mother-by scolded-got
#+END_QUOTE

ても on the other hand doesn't indicate a positive result or a negative result, it indicates a contrasting result:
#+BEGIN_QUOTE
雨が 降っ*ても* ： ∅が こうえんい 行く - Even though it's raining we can still go to the park
#+END_QUOTE

This is where でも itself, rightly translated as 'but', comes from; でも wraps up whatever came before it literally meaning 'as much as [that] is [so]...'. でも is the all purpose ても contrast marker.

#+BEGIN_QUOTE
アリスは 空っぽの びんでも、下へ 落としては 悪い*と* 思った
#+END_QUOTE
と bundles the entire thing into a quotation, of Alice's thoughts (思て). The full sentence therefore is: 'Empty jar-is-even-though, downward drop (negative expectation) is bad, Alice thought.' - 'Alice thought that even though the jar is empty, dropping it would be bad'.
# There are some more notes about the structure of this sentence, but I think they are unnecessary.

* Extra: も particle combinations
も is the additive particle, and can also be used to mean 'as much as' in several expressions. In English 'as much as' can also be said as 'even'. The same is true in Japanese.
- 誰もない - Not even someone
- 何もない - Not even something
- 少しもない - Not even a little

What about でも? The で here is not the particle で, it is the て-form of だ. As we know だ (the copula) couples together two nouns. What is it coupling? It is couple the sentence that came before it and the ∅ pronoun (it). So 誰でも doesn't mean 'everyone', it means anyone.
- 誰でも - Anyone - 誰でもできろ - Even if it's anyone, they can do it - Anyone can do it
- 何でも - Anything - 何でもいい - Even if it's anything, it's good - Anything is good
- どうでも - However (Whatever way) - どうでもいい - Whatever way is fine

#+BEGIN_QUOTE
かもしれません - Perhaps
#+END_QUOTE
- か - Makes a question of whatever came before
- も - Even/As much as
- 知れ - Potential form of know
- ない/ません - Can't know (don't have the potential to know)
#+BEGIN_QUOTE
かもしれません - As to whether that is true or not I can can't go as far as to know
#+END_QUOTE
* Lesson 23: だって, だから, それ から
だって is usually translated as 'because' and 'but' and 'even' and 'somebody said'. The reason for these myriad definitions is that だって isn't really a word.

だって is simply the copula だ, and って. This is not the て-form of だ, it is the same って as the contraction of the quotation particle という.

Firstly, /somebody said/:
#+BEGIN_QUOTE
*(∅が) 明日は* (∅が) 晴れだ *って(という)* - *(Someone/weather forecast/people)* as for tomorrow (it) fine will-be *says*
#+END_QUOTE

---

/But:/
#+BEGIN_QUOTE
1. さくらがきれいだね - Sakura's pretty isn't she
2. だって 頭が 弱い - But she's not very smary (lit: head is weak)
#+END_QUOTE
Note: This usage usually has a childish, or somewhat argumentative tone.

Why does this mean 'but'? What're we're doing is taking the thing that was just said and adding だ to it. Then quoting what they just said: だって - You say that (Sakura is pretty), and the implication is that something contradictory will follow.

# There is some explanation here of standalone phrases like ですね but I don't think it's necessary

---

#+BEGIN_QUOTE
(...)だから - From that (what you/I just said) - Therefore; as above.
#+END_QUOTE


---

/Because:/ Just as we can use だって as 'You say a thing is so, but...' We can also use だって as 'You say a thing is so, this is because (some explanation)'.

What both of these phrases are saying is 'You have said something, and I don't dispute it, but here's something we can add to it that undermines the narrative that you're trying to put forward'. This is the same in both cases, it's only the translation to English that mandates a distinction.

---

/Even:/
When we say だって to mean even we're not using だ in the same was as だから or in the other sense we've just spoken about, i.e. we aren't using it to refer back to the previous statement. We are usually attaching it to something in particular within the statement we're making.
#+BEGIN_QUOTE
1. さくらができる - Sakura can do that
2. わたしだって - Say (it) is me - I can do that
#+END_QUOTE
This has a different implication to わたしもできる which just means 'I can do that too', わたしだって, because it is associated with the phrases above carries the /tone/ of '/even/ I can do that'.

#+BEGIN_QUOTE
わたしだってホトケーキがつくられる - Even I can make hot cakes
#+END_QUOTE
In this example we aren't saying anything contradictory to someone else but it still has the implication of /even/.
* Lesson 24: Hearsay and guesses: ~そうだ, ~そうです
** Likeness
そう is a /helper noun/ that can mean either 'likeness', or 'hearsay'.

そう is the same そう as in the こう/そう/ああ/どう (in this way/in that way/in /that/ way/in what way) group we learned about in lesson 20. そう can be used with any of the three engines: う (verbs), い (adjectives) or だ (nouns). Simply remove the final kana and add そう for 'seems like' meaning. In the case of だ the engine must be an adjectival noun (な-adjective).

Remember that each of the three engines can be moved behind other cars to turn them into adjectives.

Once そう has been attached to an engine, the engine becomes a new adjectival noun.

#+BEGIN_QUOTE
元気だ -> 元気そう - Is healthy -> Seems healthy
#+END_QUOTE

#+BEGIN_QUOTE
元気な学生 -> 元気そう学生 - Healthy student -> Healthy looking student
#+END_QUOTE

-----

#+BEGIN_QUOTE
おもしろい -> おもしろそうだ - Is interesting -> Seems interesting
#+END_QUOTE
- Note: Logically だ must always be used with そう, but colloquially it is often left off.

Remember, in Japanese we can only say things that we actually know for ourselves, so unless we have read/tasted/experienced/whatever that thing which the other person is describing, we must say そう as we cannot *know* that is is the way that they say.

-----

For verbs, in the case of ichidan we just remove る as usual, and in the case of godan we use the い-stem of the verb. The い-stem of a verb is what we might call the 'pure-stem' of a verb. In Japanese this is called 「連用形」(れんようけい) which means 'connective-use form'.

# There are some notes here about the correctness of this 'connective-use form' label

#+BEGIN_QUOTE
泣きそうだ - Seems about to cry
#+END_QUOTE
- Note: Again; logically だ must always be used with そう, but colloquially it is often left off.

** Hearsay
The そう used for likeness is a /suffix/, it is joined to other words in order to form a new word. Whatever the word was to start with, once そう is attached, it becomes an adjectival noun. This is not what happens with hearsay.

When talking about hearsay we use そうだ/そうです after the entire, complete sentence. Back to the train metaphor, the entire logical sentence becomes the main car at the core of a new sentence being pulled by a だ-engine.

#+BEGIN_QUOTE
さくらが日本人だ -> さくらが日本人だそうだ - Sakura is Japanese -> Sakura is Japanese I hear
#+END_QUOTE
So simply put そうだ at the end of any full statement.

* Lesson 25: らしい vs そうです
らしい is a /helper adjective/. Adjectives that end in しい we can consider a sub-class of adjectives that on the whole express subjectivities. That is to say, they are adjectives not describing an inherent property of something, but a (possible) human perspective on it:
- かなしい - Sad
- うれしい - Happy
- むずかしい - Difficult
- やさしい - Easy

Like そう, らしい can be attached either to an individual word or to a complete logical clause/sentence. We don't need to change anything about the word, just attach らしい to it.

As with そう, if we attach らしい to a single word, we are talking about our (subjective) impression of that action or state.

And again as with そう, if we attach らしい to a sentence we're indicating that the statement itself is subjective, i.e. a deduction/hearsay/conjecture.

There is a difference however:
#+BEGIN_QUOTE
あの動物はウサギだ*そうだ* - I heard that animal is a rabbit
#+END_QUOTE
#+BEGIN_QUOTE
あの動物はウサギだ*らしい* - It seems that animal is a rabbit
#+END_QUOTE
These two /can/ mean the same thing, but not always. そう is specific to 'I heard', whereas らしい means that from the available evidence, which /could/ be what somebody said, or could be something else, it /seems/ to be a rabbit.

When it comes to the difference between そう and らしい with respect to a single word, the main difference is that we can't apply そうだ to a regular noun. We can only apply it to an adjectival noun. らしい can be applied to any noun, adjectival or otherwise.

らしい has the ability to liken one thing to another:
#+BEGIN_QUOTE
あの動物はウサギだ*らしい* - That animal is rabbit like
#+END_QUOTE
らしい is not-necessarily conjecturing that something is something else, we may merely be saying that it is like that thing.
#+BEGIN_QUOTE
男らしい男 - Manly man
#+END_QUOTE
#+BEGIN_QUOTE
さくら先生は先生らしくない - Sakura-sensei is not like (does not have the qualities of) a teacher
#+END_QUOTE
#+BEGIN_QUOTE
それはさくらしくない - That wasn't like (you) Sakura
#+END_QUOTE

** っぽい
#+BEGIN_QUOTE
こどもっぽい - Childish
#+END_QUOTE
っぽい works very much like らしい and is also a /helper adjective/ but is much more casual than らしい.

っぽい cannot be used on the end of a completed clause, it can only be attached to a word.

らしい tends to imply that the quality is something that the thing ought to have, っぽい often tends to imply the opposite. This is not an absolute rule, just a tendency.
#+BEGIN_QUOTE
こどもらしい - Childlike
#+END_QUOTE
#+BEGIN_QUOTE
こどもっぽい - Childish
#+END_QUOTE
* Lesson 26: Similes - のように、 のような、 みたい
「ようだ」 forms the far end of a sliding scale of 'likeness' expressions:
| Objectivity        |                                | Subjectivity    |
| そうだ             | らしい                         | ようだ + みたい |
| Hearsay/conjecture | Observation/quality comparison | Pure simile     |

Each of these expressions can be placed at the end of a complete logical sentence to express that the sentence is either something we've heard or some conjecture from the information available.

When we attach them to individual words then we have this sliding scale of meaning.
- そうだ - Conjecture of what the quality of something is: 「おいしいそうだ」 - It looks delicious
- らしい - Has a much greater degree of subjectivity. 「らしい」 overlaps with 「そうだ」 in many respects but it can also do things that 「そうだ」 cannot. 「らしい」 can compare things to other things that we know they aren't: 「ウサギらしい」 - Rabbit-like (even though we know it isn't a rabbit). 「こどもらしい」 - Childlike (whether they are a child or not)
- ようだ - 「ようだ」 can be much more subjective still, going as far as a /metaphor/ or /simile/

#+BEGIN_QUOTE
山のようだ - Like a mountain
#+END_QUOTE
#+BEGIN_QUOTE
風のように走る - Runs like the wind
#+END_QUOTE

Often when 「ようだ」 is being used as a metaphor/simile it is used alongside 「まるで」:
#+BEGIN_QUOTE
日の丸 - Circle of the sun
#+END_QUOTE
- まるで (usually does not use まる kanji) - roundly/wholly

#+BEGIN_QUOTE
まるで風のように走た - Wholly like the wind ran
#+END_QUOTE
- Note: This is hyperbole. Hyperbole in this fashion is common in many languages. In English: 'I /literally/ froze to death'. We really mean: 'I /figuratively/ froze to death'; The hyperbole is to give emphasis.

We *cannot* use 「まるで」 with 「そうだ」 and we *shouldn't* use it with 「らしい」.

- のよう*だ* - Clause-end adjectival
- のよう*な* - Pre-noun adjectival
- のよう*に* - Adverb

「ようだ」 has a special usage that the other likening phrases don't have. As with the other two we can attach it to the end of a sentence with the meaning of 'seems/appears'. We can also attach it to a complete sentence for another purpose. We can use 「ようだ」 to turn an entire sentence into a simile:
#+BEGIN_QUOTE
まるで[1]ゆうれいを見た[2]か[3]のような[4]顔をした[5] - [5]Did (had) a face [1]exactly [4]as [3]if [2](she) saw a ghost - She made a face exactly as if she'd seen a ghost
#+END_QUOTE
- Note: [2] is an entire sentence being used as a simile for (her) face.
- Note: か is an as-yet uncovered particle roughly meaning 'if'. か bundles a statement into a kind of question.

We start with 「まるで」 indicating that we are going to use a simile. Then we make our completed statement. か turns our statement into a question, it gives us our 'if', she hasn't actually seen a ghost, it's a potentiality, so it's an 'if'. 「のように」 takes this and turns it into a simile 'as' i.e. 'as strong as...', 'as if...'. Finally we are describing her face we use the な connective form.

# There are some notes here about か nominalising the statement preceding it, but I don't think it's too relevant rn

# TODO: Is it か specifically or is it just the normalisati of an entire sentence in to a simile?
Using か in this way is something we can't do this with any of the other likening phrases. Even 「みたい」 which can do most of the things that 「のよう」 can do, can't do this.

「みたい」 is the less formal cousin of 「よう」 and means 'looks like...', 'looks' not necessarily referring to solely literal vision:
#+BEGIN_QUOTE
山みたいだ
#+END_QUOTE
#+BEGIN_QUOTE
山みたいな人
#+END_QUOTE
#+BEGIN_QUOTE
風みたいに走る
#+END_QUOTE
「みたい」 can also make true similes using 「まるで」 just like 「ように」. The main things to remember about 「みたい」 vs. 「ようだ」 is that 「みたい」 is less formal, and that we *can't* use it with a completed sentence. We *can* use it with a complete sentence for /conjecture/, but not to create a /simile/.

Because 「みたい」 is so casual, often the だ or 「です」 gets left off the sentence.
