# ∅
* Core sentence
  Every sentence is formed of two elements, they are the が-marked noun and the /engine/.

  In all languages there are only two kinds of sentence:
  - A *is* B i.e. Sakura is Japanese
  - A *does* B i.e. Sakura Walks

  #+BEGIN_QUOTE
  さくらが日本人だ - Sakura is Japanese
  #+END_QUOTE
  #+BEGIN_QUOTE
  さくらが歩く - Sakura walks
  #+END_QUOTE

  There are three possible engines:
  - Verb - A does B
  - だ-marked noun - A is B
  - い-"Adjective" ([[*Adjectives]]) - A is B

  The engine *always* comes at the end of the sentence (with the exception of sentence ender particles ([[*Sentence ender particles]]).

  <<Invisible が>>
  The が-marked noun is not always visible in the sentence. It is still present as part of the core of the sentence however. The closest English equivalent to this invisible が is 'it'. Take this example English sentence:
  #+BEGIN_QUOTE
  The ball rolled down the hill. When the ball got to the bottom the ball hit a sharp stone and the ball was punctured and all the air came out of the ball.
  #+END_QUOTE
  This is not a sentence we would ever say in English, once we have established that we are talking about 'the ball' we would instead refer to the ball by 'it':
  #+BEGIN_QUOTE
  The ball rolled down the hill. When it got to the bottom it hit a sharp stone and it was punctured and all the air came out of it.
  #+END_QUOTE
  If we were to completely omit 'it' the sentence would still be easy to understand, we don't *need* to use this it marker each time, but English grammar *demands* it. Japanese does not, hence the 'invisible' が carriage.

  <<∅ pronoun>>
  'It' by itself doesn't really mean anything, we know what it means from context. All of the pronouns I/it/we/he/they can be replaced by an invisible logical particle ([[*Logical particles]]) (most often が) marked /∅ pronoun/. It is important to remember that the が-marked noun *is still there*.

  #+BEGIN_QUOTE
  [∅が]さくらだ - (I) am Sakura
  #+END_QUOTE
  By default 'I' is the default value of this ∅ pronoun. However, if someone were introducing their daughter and said 「さくらだ」 we would understand from context that ∅ meant this/she.

  #+BEGIN_QUOTE
  [∅が]土曜日だ - (Today) is Saturday
  It is Saturday - (Today) is Saturday
  #+END_QUOTE
  From context it is clear that ∅ and 'it' mean 'today'.

  <<Egocentrism>> <<Animism>>
  English is an /ego-centric/ language. Japanese is a more /animist/ language. What this means is that English always wants a person, preferably /I/, but if not I then someone else, or perhaps it will settle for an animal, but always wanting an animate being to be acting. Japanese is not this way:
  #+BEGIN_QUOTE
  わたしはコーヒがすきだ
  #+END_QUOTE
  A textbook would translate this as 'I like coffee'. 'I like coffee' very well might be the English equivalent for this simple phrase, but it is not what this sentence means, and it is not what this structure of sentence means.

  The が is marking the coffee. The coffee is the actor in this sentence, not I. It's not 'I like coffee', I am not /liking/ it. But 'As for me, coffee is likeable/pleasing'.

  The English 'I like coffee' is an /A does B/ sentence. The Japanese is an /A is B/ sentence.

  すき is a *noun*. An adjectival noun ([[*Noun-adjectives]]), but still a noun. It is not a verb like in English.

  #+BEGIN_QUOTE
  わたしはほんがわかる - As for me, the book is readable
  #+END_QUOTE

  <<ほしい>>
  #+BEGIN_QUOTE
  (わたしは)こねこがほしい - (As for me) a kitten is wanted
  #+END_QUOTE
  「ほしい」 is often translated in English as 'want', but again, it is not a verb, it is an adjective. Again, /I/ is not the actor of the sentence, it is the cat, and it is the cat that is wanted, not 'I want a cat'.

   Remember: 「ほしい」 can only be used with respect to ourselves ([[がる]])

* Particles
  No particles other than が and だ can ever be part of the core sentence ([[*Core sentence]]) and only が is present in every sentence (even if invisible ([[Invisible が]]).

  # TODO Flatten this whole structure

** Logical particles
   A logical particle tells us how the sentence logically holds together. It tells us who does what to whom with what, when and where.

   All logical particles attach to nouns, they *cannot* attach to anything but nouns. If we see a logical particle attached to anything else then we know that that word is functionally a noun.

   The noun and the particle attached to it are an inseparable pair. We must view the two together, they are a question and an answer which form a fundamental unit of the Japanese sentence.

   There cannot be a sentence without が, even if sometimes you can't see it. が can work in A is B sentences, as well as A does B sentences. The other particles can *only* work in A does B sentences i.e. that is sentences with a verb engine.
   - が - Who (or what) did it?
   - を - Whom was it done to?
   - に - Where did they go?/Where are they?
   - へ - What direction?
   - で - Where was it done? With what was it done?

*** TODO が (/ga/) - Subject <<が>>
# I may need to dig out the episode to cover this particle
*** だ (/da/) - Copula <<だ>>
    For basic use of だ see /core sentence/ ([[*Core sentence]]).

    <<Copula て-form>>
    #+BEGIN_QUOTE
    ふつうの ウサギでは なかった - As for being an ordinary rabbit, (it) wasn't - (It) wasn't an ordinary rabbit
    #+END_QUOTE
    では here is the て-form of the copula だ, meaning 'as for being (an ordinary rabbit)'

*** を (/o/wo/) - (Direct) Object
    The を particle marks the object of the sentence, the /thing/ that some verb (the engine) is being done to. が marks the thing that is doing the verb.
    #+BEGIN_QUOTE
    わたし​*が*​ケエキ​*を*​たべる - I eat cake
    #+END_QUOTE
    The core sentence here is 'I eat'. The extra を particle marked noun, is telling us more about the engine (eat). /What/ are we eating? We are eating cake.

    #+BEGIN_QUOTE
    わたしがぼーる​*を*​なげる - I threw the ball
    #+END_QUOTE
    The core sentence is 'I threw', and the extra を particle marked noun tells us what we threw i.e. the ball.

*** に (/ni/) - Target (Indirect Object)
    The に-particle marks the target (indirect object) of an engine. Along with が and を:
    - が tells us who does the doing
    - を tells us what it is done to
    - に tells us what the ultimate target of that doing

    #+BEGIN_QUOTE
    わたしがぼーるをさくら​*に*​なげる - I threw the ball at/to Sakura
    #+END_QUOTE
    Sakura is the destination, the target. It is important to note here that the logical particles tell us what happened. The order of the words doesn't really matter the way it does in English.

    #+BEGIN_QUOTE
    わたし​*に*​さくらがぼーるをなげる - Sakura threw the ball at/to me.
    #+END_QUOTE
    #+BEGIN_QUOTE
    ぼーるがわたし​*に*​さくらをなげる - The ball throws Sakura at me
    #+END_QUOTE
    Obviously this final example doesn't make any sense (although we might want to say something nonsensical like this in a fantasy novel or something) but we can say whatever we like in Japanese so long as we use the right logical particles.

    If we are going somewhere, or sending something somewhere, or putting something somewhere, we use に.
    #+BEGIN_QUOTE
    [∅が]みせ​*に*​いく - (I) will go to the shop
    #+END_QUOTE

    に gives us the target of an action in the literal sense, and also the target in a volitional sense, i.e. the aim of our action.
    #+BEGIN_QUOTE
    [∅が]みせ​*に*​たまごをかい*に*いく - (I) will go to the shop to buy eggs
    #+END_QUOTE
    かい is the い stem of かう, to buy ([[*Verb stems]]). The logical particles can only mark nouns. The い-stem of a verb is the equivalent noun form of it. Just as in English 'I like swimming', /swimming/ is a noun, 'I go to the shop for the purpose of buying eggs', this /buying/ is also a noun.

    As well as identifying a place we will go to, に can also specify a place we are currently at:
    #+BEGIN_QUOTE
    ∅がみせ​*に*​いる - (I) am/is at the shop
    #+END_QUOTE
    This に is still marking a target, just not a future target. In order for something to be somewhere it must've gotten there, and so に specifies the target of some past action. We can also use this for inanimate objects:
    #+BEGIN_QUOTE
    ほんは∅がテーベルのうえ​*に*​ある - As for the book, (it) exists/is on/at the table.
    #+END_QUOTE
    This use of に also applies to times as well as places, see: /time expressions/ ([[*Time expressions]]).

    Finally, に can also mark a transformation. If /a/ becomes /b/, then に also marks /b/, the thing a is becoming.
    #+BEGIN_QUOTE
    さくらは∅がかえる*に*なった - Sakura became a frog
    #+END_QUOTE
    Of course this example is a bit of a joke, but there are of course various every day things that become other things. This form of expression is also used much more often in Japanese than in English.
    #+BEGIN_QUOTE
    ことし∅が十八さいになる - This year (I) become 18 years old
    #+END_QUOTE
    #+BEGIN_QUOTE
    あとで∅がくもりになる - Later (it (the weather) will) become cloudy
    #+END_QUOTE
    See also how to use 「なる」 with adjectives ([[Becoming an adjective]])

*** の (/no/) - Possessive
    The の particle, or the /possessive particle/ functions just like the English /'s/.
    #+BEGIN_QUOTE
    さくら​*の*​はな - Sakura's nose
    #+END_QUOTE
    #+BEGIN_QUOTE
    わたし​*の*​はな - Me's (my) nose
    #+END_QUOTE
    Luckily in Japanese we don't have to worry about his/her/my/their, we just use の.

    <<の-adjectives>>
    Because this is the /possessive particle/ we can use this in another slightly different way. 「あか」 has an /adjectival/ form in 「あかい」, but not all colours have this form. The Japanese for pink, 「ピンクいる」 (lit: pink-colour) doesn't have an adjectival form in 「ピンクいろい」, nor can we use it as a secondary engine with な. So what are we to do? Well we can use the の-particle:
    #+BEGIN_QUOTE
    ピンクいる​*の*​どれすが - The pink dress (literally: The dress belonging to the class of pink things)
    #+END_QUOTE
    #+BEGIN_QUOTE
    うさぎ​*の*​OSCAR - Oscar the rabbit (literally: Oscar belonging to the class of rabbit)
    #+END_QUOTE

*** へ (/e/) - Direction
    This is a very simple particle, it duplicates a single use of に. When we say /a is going to b/ we can freely substitute に with へ. This is *all* is can do, it cannot even mark the case where something /is/, only where it is /going/.
*** で (/de/) - Means
    #+BEGIN_QUOTE
    [∅が]こうえんにいく - I go to the park
    #+END_QUOTE
    If we say 'I went by bus' or 'I ate with chopsticks' we use で for the thing we did it with, the means by which we performed the action.
    #+BEGIN_QUOTE
    [∅が]バス​*で*​こうえんにいく - I go to the park by bus
    #+END_QUOTE

** Non-logical particles
   Non-logical particles are not part of the logical structure of a sentence. They are neither the thing we are saying something about, nor what we are saying about it. They also do not tell us more about the engine of the sentence as the other logical particles do.

*** は /wa/ topic exclusive
    The は-particle can be thought of as a /flag/. It simply marks something as the topic of the sentence, but doesn't say anything about it.

    An exact translation of the は particle would be 'As for /x/'. 「わたしは」 therefore means 'As for me', *not* 'I am' (わたしが).

    A commonly mistranslated sentence is:
    #+BEGIN_QUOTE
    わたし​*は*​日本人だ - +I am Japanese+
    #+END_QUOTE
    Referring back to the core sentence ([[*Core sentence]]) we can see that the が-marked noun so we don't actually know who or what the subject is. One may ask /'well why don't we just treat the は particle as if it is marking the subject'/. In this example it is obvious that the topic marked by は is the same as the subject marked by が, but there are many more cases where this is not true, leading to much confusion down the road. Let's look at a similar sentence. You are at a restaurant, the waitress is asking what you would like:
    #+BEGIN_QUOTE
    わたし​*は*​うなぎだ - +I am an eel+
    #+END_QUOTE
    Treating は as 'I am' doesn't work. As we now know the default value of the ∅ pronoun is 'I', but in this context it's clear that we're talking instead about /what/ we want to eat. 「わたしはうなぎだ」 therefore means 'As for me, eel'.
    #+BEGIN_QUOTE
    わたし​*は*​[∅が]日本人だ - As for me, (I) am Japanese
    #+END_QUOTE
    #+BEGIN_QUOTE
    わたし​*は*​[∅が]うなぎだ - As for me, (what I would like to order) is eel
    #+END_QUOTE

    #+BEGIN_QUOTE
    わたし​*は*​[∅が]さくらにぼーるをなける - As for me, (I) threw the ball at Sakura
    #+END_QUOTE
    #+BEGIN_QUOTE
    ぼーる​*は*​わたしがさくらに[∅を]なける - As for the ball, I threw (it) at Sakura
    #+END_QUOTE
    This time the を marked noun (not the が marked noun) has become invisible([[Invisible が]]), because what we're throwing is now marked by the は particle, ∅ here has taken the value of 'it'. Even without は we might already know what 'it' was that was thrown from context. The important thing to understand here is that as we change the logical particles from one noun to another we change the meaning of the sentence, but when we change the non-logical particle は from one noun to another it makes no difference to the logic of the sentence. It may make some difference to the emphasis, but it makes no difference to who is doing what or what they're doing it to.

*** も /mo/ topic inclusive (also)
    も is another non-logical topic-marking particle. も marks the topic of the sentence in the same way that は does. The difference is that while は can mark the topic of the sentence and *can* also change the topic of the sentence, も declares the topic of the sentence but can *only* change the topic of the sentence. We cannot use も unless we are changing the topic of the sentence.

    For context, up until this point the topic of our conversation has been the rabbit, now we are switching to talk about Alice.
    #+BEGIN_QUOTE
    アリス​*も*​ ウサギの 穴に とび こんだ。 - Alice also jumped into the rabbit hole.
    #+END_QUOTE

    When we change topic with も we're saying that the comment about the previous topic (the rabbit and that it jumped) is the same as our new topic (Alice). When we change the topic with は we are doing the opposite, we are drawing a distinction between the two.

** Alogical particles
*** と (/to/) - And
    Alogical particles aren't simply markers. The と particle 'ands' two nouns together. It is therefore doing something in the sentence, it is joining a noun to another noun and inheriting its logical particle, but the と particle has no function of its own.
    #+BEGIN_QUOTE
    さくら​*と*​メイリー​*が*​あるいていた - Sakura *and* Mary were walking
    #+END_QUOTE

*** と (/to/) - Quotation
    # TODO Is this the right place for this particle?
    #+BEGIN_QUOTE
    「おもしろい ことが ない」​*と*​ アリスは 言った - Nothing interesting is happening said Alice
    #+END_QUOTE

    #+BEGIN_QUOTE
    おもしろい ことが ない- No interesting thing (abstract thing) exists - Nothing interesting is going on here
    #+END_QUOTE
    #+BEGIN_QUOTE
    アリスは 言った - Alice said
    #+END_QUOTE
    The と particle marks a quotation. When we quote someone as saying something or as thinking something we use this と particle. We also use these square brackets which are the equivalent of English quotation marks, but in speech we cannot see these, so we also use と (and clearly use と in writing regardless also).

    What と does structurally, is it takes whatever it marks which could be a simple word or phrase, to a whole paragraph, to anything with all sorts of grammar going on, and turns what it is marking it into a single noun. This is used not only to mark things people say and people think, but to mark all sorts of things. This と structure can therefore make a quotation act as a modifier to whatever follows, in the previous example it is modifying 言う (to say), or to think or feel, but could be many things.
    # TODO put an example here

    #+BEGIN_QUOTE
    でも ウサギは ピョンピョン​*と*​ はしり つづけた。 - But as for the rabbit, (it) kept on running in a /pyonpyon/ manner
    #+END_QUOTE
    「ピョンピョン」 - The sound of a small thing jumping along (an onomatopoeia hence katakana). Once again we're using the quotation particle と to describe the way in which the rabbit ran, it ran in the way it sounds, it ran like a small thing jumping along (Note there are no quotation marks around onomatopoeia).

** TODO Sentence ender particles
* Tense
  In Japanese the tenses are not the same past, present and future tenses we're familiar with from English.

** Non-past (future) tense
   The basic, dictionary-form of verbs are in the /non-past/ tense. The Japanese non-past tense is very similar to the English non-past tense. What is the /English/ non-past tense? It is again the plain dictionary form of a verb: /eat/, /run/, /walk/ etc. It is unnatural in English to say 'I eat cake', to mean 'I am eating cake'. It is natural however to use the non-past tense to say 'Sometimes I eat cake' or, in the explicitly future tense 'I will eat cake'. Japanese is just the same as English in this way. It is rare we use this form for talking about things actually happening right now, except in cases like literary descriptions.

   Just as the ∅ pronoun ([[∅ pronoun]]) defaults to 'I', the non-past tense defaults to the future.
   #+BEGIN_QUOTE
   さくらが歩く - Sakura will walk
   #+END_QUOTE
   #+BEGIN_QUOTE
   犬がたべる - Dog will eat
   #+END_QUOTE
   'Sakura walks' is possible, but isn't the most natural way.

** Present (continuous)
   <<Present continuous>>
   In order to say something like 'Sakura is walking' we need to combine the verb 「歩く」 - /to walk/ with the verb 「いる」 -  /to be/. This is done by putting the verb into the て-form ([[*て-form]]).
   #+BEGIN_QUOTE
   さくらが歩いている - Sakura is walking
   #+END_QUOTE
   #+BEGIN_QUOTE
   犬がたべている - Dog is eating
   #+END_QUOTE
   The core sentence here is 'Sakura is existing', the て-form verb, what we shall call a /secondary engine/ which modifies the main engine. In what state is Sakura existing? She is existing in the state of eating.

   # TODO Add a link here to the expanded secondary engine write-up (if one gets written)

** Past
   <<Verb past>>
   To form the past tense of a verb we need to take the verb stem([[*Verb stems]]) and add た.
   #+BEGIN_QUOTE
   犬がたべた - The dog ate
   #+END_QUOTE

   <<Adjective past>>
   If we want to put an adjective into the past tense we drop the い and add かった.
   #+BEGIN_QUOTE
   こわい ー> こわかった - Was scary
   #+END_QUOTE

** Negatives
   Because 「ない」 is also an adjective, the past tense of it is just 「なかった」.

   | Non-past             | Past                     |          |
   |----------------------+--------------------------+----------|
   | さくらがはしる       | さくらがはしった         | Positive |
   | さくらがはし*ら*ない | さくらがはし*ら*なかった | Negative |

   As we know 「さくらがはしる」 is not very natural Japanese, instead we would say 「さくらがはしっている」. For this, all we need to do is put the 「いる」 into the past tense:
   #+BEGIN_QUOTE
   さくらがはしっている -> さくらがはしっていた - Sakura was running
   #+END_QUOTE

** Time expressions
   If we want to make it clear that we are talking about a future event we can add a time expression. By prefixing a sentence with あした (tomorrow), we can make it clear that what we will be doing, we will be doing tomorrow.
   #+BEGIN_QUOTE
   あした[∅が]ケーキをたべる - Tomorrow I will eat cake
   #+END_QUOTE
   Note how we simply preface the sentence with 'tomorrow', just like we would in English. This is the case with all /relative-time nouns/, 'yesterday', 'tomorrow', 'the day after tomorrow', 'next week', next month', 'next year'.

   For /non-relative/, i.e. /absolute/ time expressions we must use the に-particle:
   #+BEGIN_QUOTE
   火曜日​*に*​[∅が]ケーキをたべる - On Tuesday I will eat cake
   #+END_QUOTE
   We must attach に in all the same places we would attach on/in/at in English. 'On Tuesday', 'in March', 'at 12 o'clock'. Fortunately in Japanese we only need to use the one particle.

   #+BEGIN_QUOTE
   そのとき、白い ウサギが とおり すぎた。
   #+END_QUOTE
   「そのとき」 - That time. In this sentence it is used to mean 'just at that moment' (just as Alice said that)

* て-form
  The て-form of a verb is its /connective form/.

** Constructing the て-form
   Japanese verbs fall into three groups: /Ichidan/, /Godan/, and /irregular/

   The first group are /ichidan/ (lit: one level) verbs. Morphing these verbs is easy, we simply remove the る and add our new ending. Ichidan verbs can only end in either いる or える (phonetically).

   The second group is by far the largest, the /godan/ (lit: five level) verbs. This group contains verbs that end in all of the possible verb endings: う つ る - ぬ ぶ む - く ぐ - す. Each of these ending groups has its own way of being morphed, though although they're 'five level' verbs, two of the groups use the same method so we only need to learn 4 methods. Confusingly this means that godan verbs can end in いる or える, most of these will still be /ichidan/ verbs, and fortunately even if a verb is morphed incorrectly, you will probably still be understood.
   - う つ る -> って
   - ぬ ぶ む -> んで
   - く/ぐ -> いて/いで (Note: this is the combined group)
   - す -> して

   There are only two irregular verbs, くる and する. いく, is partly irregular, but not completely.
   - くる -> きて
   - する -> して
   - いく -> いって (+いいて+)
   These are the only exceptions

** て-form connecting two verbs
*** ている
    See: present continuous tense ([[Present continuous]])

*** くれる/あげる
    #+BEGIN_QUOTE
    あそんで くれなかった - (She) didn't play with Alice (didn't play for Alice's benefit).
    #+END_QUOTE
    あそぶ is to play. This has been put into the て-form. 「くれる」 means to 'give downwards' i.e. as Japanese is so polite we place ourselves below others, so someone else is giving us something. 「あげる」 to contrast is to 'give upwards' i.e. to give to someone else. What is being given? In this case the thing being given is what is attached to it via the て form, i.e. 'playing'. Specifically, (she) is not giving the act of playing to Alice. In Japanese we frequently use 'give' for actions, for doing something for our benefit as well as for literally 'giving' nouns. If someone does something for our benefit, we turn that action to the て-form, and attach it to 「くれる」. If we do something for someone else's benefit, we turn that action to the て-form, and attach it to 「あげる」.

** て-form as clause-connector
   #+BEGIN_QUOTE
   おねえちゃんは つまらない 本を よんで いて あそんで くれなかった。
   #+END_QUOTE
   「よむ」 (read) -> 「よんでいる」 (reading) -> 「よんでい​*て*​」 - We have put the 「いる」 into the て-form, why have we done this?
   #+BEGIN_QUOTE
   おねえちゃんは つまらない 本を よんで いる - Big sister is reading an uninteresting book.
   #+END_QUOTE
   This by itself is a complete clause (sentence), by turning the engine of the sentence (いる) into the て form we're saying that something else is going to follow this clause, i.e. 'and'.
   #+BEGIN_QUOTE
   おねえちゃんは つまらない 本を よんで いて - Big sister is reading an uninteresting book and...
   #+END_QUOTE

   Note the ends of the two clauses:
   #+BEGIN_QUOTE
   おねえちゃんは つまらない 本を よんで いて
   #+END_QUOTE
   #+BEGIN_QUOTE
   あそんで くれなかった
   #+END_QUOTE
   For the first clause we do not know what in what tense the action is taking place. In English we would place the tense marker on both clauses, in Japanese we only do this at the end. よんで いて could mean 'is reading' and it could mean 'was reading'. Because くれなかった is in the past tense, then the entire sentence is in the past tense.

** て-form of だ
   See: /copula て-form/ ([[Copula て-form]]).
* Negative nouns
    The fundamental basis of negatives is the adjective 「ない」. This adjective means 'non-exist'. The word for exist (for any inanimate thing) is ある. If we want to say that something exists:
    #+BEGIN_QUOTE
    ぺんがある
    #+END_QUOTE
    But if we want to say that something doesn't exist we say:
    #+BEGIN_QUOTE
    ぺんがない
    #+END_QUOTE
    Now, why do we use a verb for being, and an adjective for non-being? This is something that happens all throughout Japanese, when we do something we use a verb, but when we don't do something we attach ない and are therefore using an adjective as the engine of the sentence. This has a very logical reason, when we *do* something, an action is taking place, and so we use a verb, but when we *don't do* it we are describing a state of non-action, so that's an adjective.

    Above we have said 'There is no pen', how do we say 'This is not a pen'?
    #+BEGIN_QUOTE
    これはぺんがある - As for this, it's a pen
    #+END_QUOTE
    #+BEGIN_QUOTE
    これはぺんではない - As for this, as for being a pen, it's not. (Note: で is the て-form of だ)
    #+END_QUOTE

    # TODO Add link to jyanai secrion
* Verbs (transitive and intransitive)
  /Transitive/ and /intransitive/ are better thought of as /Self-move/ and /Other-move/.

  In japanese, a move-word 「動詞」 (どうし) is a word that denotes an action or a movement. So a self-move verb is a verb that moves itself. If I 'stand-up' that's a self-move action. But throwing a ball is an 'other-move' action, one is not throwing themselves, they are throwing a ball. It's as simple as that.

  Japanese has a lot of pairs of words, these could be called forms, or just closely related words, that give the self-move and other-move variations of the verb. For example:
  - 「出る」 (でる) - leave, exit, come out - Self-move
  - 「出す」 (だす) - take out, bring out - Other-move

  Most of the time we can tell which is a self-move word and which is an other-move word by following a few simple rules.

  The first thing to know is that there is a root word for self-move and a root word for other-mode:
  - ある (to be) - Self-move
  - する (to do) - Other-move

  Knowing this there are three laws of move-word pairs.
  1. す and せる (え-stem) ending verbs are other-move
  2. あ-stem + る (aru) ending verbs are self-move
  3. え-stem + る (eru) flip self/other-move either way

  Honorary members of the す family:
  - む -> める is always other-move
  - ぶ -> べる is always other-move
  - つ -> てる is always other-move

  The only wildcards left are:
  - く/ぐ -> ける/げる
  - う ー> える
  - Some る-ending verbs not covered by the first two laws

  Is there anything we can do to simplify this: える version have the opposite of the standard word.

* Verb stems
   Note: these stems apply to godan verbs. For ichidan verbs just drop the る.

    Every verb ends in one of the う-row kana. Here is the kana-grid (う-row kana that aren't used as verb endings have been removed), presented on its side.
    | あ | い | *う* | え | お |
    | か | き | *く* | け | こ |
    | さ | し | *す* | せ | そ |
    | た | ち | *つ* | て | と |
    | な | に | *ぬ* | ね | の |
    | ば | び | *ぶ* | べ | ぼ |
    | ま | み | *む* | め | も |
    | ら | り | *る* | れ | ろ |
    As we can see there are four other ways in which the verb could end. These are the verb stems. For now we're only looking at the あ-stem as this is the one we need for the negative.

    To form the あ-stem we simply shift the final kana from the う-row to the あ-row. There is one only exception and this is the only exception in the entire stem system. This exception is that う itself does not become あ but わ. This is because, take for example a verb like 「かう」, 「かあ」 would not be as easy to say as 「かわ」. Every other う-row kana is simply changed to its あ-row equivalent.
    | **わ** | い | *う* | え | お |
    | *か*   | き | *く* | け | こ |
    | *さ*   | し | *す* | せ | そ |
    | *た*   | ち | *つ* | て | と |
    | *な*   | に | *ぬ* | ね | の |
    | *ば*   | び | *ぶ* | べ | ぼ |
    | *ま*   | み | *む* | め | も |
    | *ら*   | り | *る* | れ | ろ |

** い-stem
   # TODO Add general discussion about what the い-stem is

   #+BEGIN_QUOTE
   そのとき、白い ウサギが とおり すぎた。 - At that moment a white rabbit passed by
   #+END_QUOTE
   「とおりすぎる」 is attaching the い-stem of one verb 「とおる」 - 'pass through', to another verb 「すぎる」 - 'exceed'/'go beyond' to give it extra meaning. We will see this a lot throughout Japanese. Connecting とおる and すぎる, 'pass through' and 'go beyond' means 'passing by'.

   #+BEGIN_QUOTE
   はしり だした - Run + Take out = Broke into a run (started to run).
   #+END_QUOTE
    In this sense だした means modifies the verb to mean the action 'erupted'.

    #+BEGIN_QUOTE
    でも ウサギは ピョンピョンと はしりつづけた。 - But as for the rabbit, (it) kept on running in a /pyonpyon/ manner
    #+END_QUOTE
    「はしりつづけた」 = 「はしる」 + 「つづける」 = Continued running (running continued).
* Negative verbs
   To make a verb negative we must attach 「ない」 to the あ-stem of the verb ([[*Verb stems]]).
   #+BEGIN_QUOTE
   かう ー> かわない
   #+END_QUOTE
   #+BEGIN_QUOTE
   はなす ー> はなさない
   #+END_QUOTE

   Remember for ichidan verbs we don't need to form a stem and just drop the る:
   #+BEGIN_QUOTE
   たべる ー> たべない
   #+END_QUOTE

* Adjectives
   Japanese adjectives are not the same as English adjectives. As we have learned Japanese sentences come in three kinds, depending on the type of engine they have. All three of these engines can be used like adjectives.
   - Verb ([[*Verb-adjectives]]) - A *does* B
   - だ-marked noun ([[*Noun-adjectives]]) - A *is* B
   - い-"Adjective" ([[*い-adjectives]]) - A *is* B

** い-adjectives
  Let's start with the first one, the one we refer to as an adjective in English, the い-engine:
  #+BEGIN_QUOTE
  ぺんがあかい - Pen is red
  #+END_QUOTE
  An important note, 「あかい」 does not mean 'red', it means 'is red'. 「あか」 means red.

  If we swap the order of 「ぺんが」 and 「あかい」 then we can take this い-engine, and now use it not as the primary engine, but as a secondary engine. This would not be a complete sentence however without a new engine, for example, a new (primary) い engine.
  #+BEGIN_QUOTE
  あかいぺんがちいさい - Red pen is small
  #+END_QUOTE

** Verb-adjectives
   Any verb in any tense can be used like an adjective:
   #+BEGIN_QUOTE
   しょうじょがうたった - Girl sang
   #+END_QUOTE
   #+BEGIN_QUOTE
   うたったしょうじょが... - The girl who sang... (Note: this sentence is not yet complete, it lacks a primary engine).
   #+END_QUOTE
   #+BEGIN_QUOTE
   うたったしょうじょがねている - The girl who sang is sleeping
   #+END_QUOTE

   #+BEGIN_QUOTE
   ある 日 アリスは 川の そばに いた。- On a certain day, alice was beside a river.
   #+END_QUOTE
   ある means 'exists' (of inanimate things) or, more accurately in English: 'a certain'. ある日 therefore means 'on a certain day'. Note also that this is the same as how we use might use Today, Yesterday, Tomorrow etc. but not how we might use 'On Saturday' ([[*Time expressions]]).

   Verbal adjectives can create very complex sentences in which we can use entire other-sentences (clauses) in an adjectival manner.
   #+BEGIN_QUOTE
   しゃべる ウサギを 見た ことが ない。
   #+END_QUOTE
   Here 「しゃべる」 is being used as an adjective just as any verb can be. 「しゃべるウサギ」 - Talkative/talking rabbit. 「見た」 is the past tense of 「見る」 to see. It is modifying 「こと」, an abstract thing, meaning 'The fact of having seen'. 「見たことがない」 means 'The fact of having seen doesn't exist'. The talking rabbit is the object of the engine of the sentence, 'The fact of having seen'. So: 'The fact of having seen a talking rabbit doesn't exist' -> (Alice) had never seen a talking rabbit. This is another example of the un-egocentric ([[Egocentrism]]) nature of Japanese; Alice is not the actor of this sentence, it is the 'thing' that does not exist.

** Noun-adjectives
  <<な-adjectives>>
  #+BEGIN_QUOTE
  いぬがやんちゃだ - The dog is naughty
  #+END_QUOTE
  We can turn 「やんちゃ」 into an adjective too, but there is one important thing to note. Just as we have to add だ to a noun to use it as an engine, here we must add な to the noun to use it as an adjective. な is in fact the connective form of だ. Don't be fooled by so-called 'な-adjectives', they're simply nouns! /Adjectival/ nouns.
  #+BEGIN_QUOTE
  やんちゃ​*な*​いぬが... - The dog who is naughty... (Note: this sentence is not yet complete, it lacks a primary engine).
  #+END_QUOTE
  #+BEGIN_QUOTE
  やんちゃ​*な*​いぬがねている - The dog who is naughty is sleeping
  #+END_QUOTE

  An important note is that we cannot do this with /all/ nouns, only nouns which are frequently used in an adjectival way. This group of nouns is what are referred to as 'な-adjectives'. We can use all nouns as adjectives, but for the rest we need to use a different technique, /の-adjectives/ ([[の-adjectives]]).
  # TODO use org's duplication function here for の-adjectives

* Adjective stem, adjective て-form, negative adjectives
  <<Negative adjectives>>
  The adjective stem is simple, just drop the い and add く. This is how we make the て form, 「あかい」 ー> 「あかくて」, and it's also the way we make the negative, 「あかい」 ー> 「あかくない」.

  # Add link here
  The only exception (besides ます) is いい (is good), which has an older form, which is still widely used in よい. When we morph いい it becomes よい again:
  #+BEGIN_QUOTE
  いい ー> よくない - Not-good
  #+END_QUOTE
  #+BEGIN_QUOTE
  いい ー> よかった - Was-good
  #+END_QUOTE
  Note: 「よかった」 is a common phrase: 「∅がよかった」 - /It was good (That went well, it turned out great etc.)/

  # TODO: Rename this section to adjectives as nouns?
  <<Becoming an adjective>>
  If we want to say 'Sakura became beautiful' we can't use に because 「うつくしい」 isn't a noun ([[*Logical particles]]), it's an engine. To use 「うつくしい」 as a noun we must convert it to its stem 「うつくしく」.
  #+BEGIN_QUOTE
  さくらがうつくしくなった - Sakura became beautiful
  #+END_QUOTE

* Adverbs
  #+BEGIN_QUOTE
  ウサギは 早く 走る
  #+END_QUOTE
  「早い」 is an adjective. If we want to say the rabbit is fast we simply say 「ウサギが早い」. But if we want to say that the rabbit's *movement* is fast we must use an adverb. In Japanese we can turn any adjective into an adverb by simply removing the い and replacing it with く. 「早い」 -> 「早く」.
* Helper adjectives
** ない - Negative
   See: /negative nouns/ ([[*Negative nouns]]), /negative verbs/ ([[*Negative verbs]]) and /negative adjectives/ ([[Negative adjectives]]).
** たい - Desire (to do something)
   :PROPERTIES:
   :Keywords: want, desire
   :END:
   For desire to have something see 「ほしい」 ([[ほしい]]).
   Remember: 「たい」 can only be used with respect to ourselves ([[がる]]).

   To express that we want to do something, we must add the /helper adjective/ 「たい」 to the い-stem of the verb ([[*Verb stems]]). 「たい」 doesn't mean 'want' in the English sense, it can't, again, because 'want' is a *verb*, and 「たい」 is an *adjective*.
   #+BEGIN_QUOTE
   (わたしは)クレープガたべたい
   #+END_QUOTE
   The common English translation for this is 'I want to eat crepes', but as the pattern is just the same as with 「ほじい」 ([[ほしい]]), the desire-ability of the crepes is not a verb, it is an adjective.

   There is no truly good translation of this into English. We shouldn't be thinking in terms of 'awkward English' or 'natural English' when it comes to constructing and understanding these sentences. We should be thinking in terms of Japanese.

   What if we took this sentence, 「わたしはクレープガたべたい and removed the optional parts so that we just had 「たべたい」? In this case, the meaning of the sentence would be what the common English translation is. ∅ defaults to 'I', and so the translation is 'I eat-wanting am' -> 'I am wanting to eat' -> 'I want to eat'. Because there is no eat-inducing subject here, the want to eat is attributed directly to I.

   # TODO Reference this section from elsewhere
   So what is 「たい」? Is it an adjective describing the /condition of something/ making you want to do something, or is it an adjective describing /my desire/? Well, it can be either. This is very common throughout Japanese. 「こわい」 can mean scared or scary:
   #+BEGIN_QUOTE
   おばけがこわい - Ghosts are scary
   #+END_QUOTE
   #+BEGIN_QUOTE
   ∅がこわい - I am scared
   #+END_QUOTE
   This isn't confusing because が tells us what to do.

   We cannot use these adjectives of desire (or any emotion) about anyone other than ourselves. If we say 「たべたい」 and there is no context to give the subject, then we must be talking about ourselves, and never the person we are speaking to or anyone else. Japanese simply doesn't allow us to use 「たい」 or 「こわい」 or 「ほしい」 or anything else about anyone other than ourselves ([[がる]]).

* Helper verbs
** がる - Seems/appears
   <<がる>>
   Because Japanese is such a logical language it doesn't allow us to say something that we cannot know for sure. One thing that we cannot know for sure is someone's inner feelings. We might think that Sakura wants to eat cake, but we can't know for sure. So if I want to talk about her desire to eat cake, we can't just use 「たい」. We need to add to 「たい」 (or 「こわい」, or 「ほしい」 or anything else) the helper verb がる.

   To do this we take the い off of the adjective and add the helper verb 「がる」.
   - たがる
   - こわかる
   - ほしがる

   「がる」 means 'to show signs of', 'to look as if it's the case'.
    #+BEGIN_QUOTE
    さくらがケーキをほしがる - Sakura is showing signs of wanting cake
    #+END_QUOTE
    Even if Sakura has actually told me she wants cake, we must still use 「がる」. All I know is what she's said, I still don't know her feelings absolutely.

    Why do we use a verb for other people and an adjective for ourselves? I can't describe someone-else's feelings because I don't know about them, I can only describe their actions, and their actions are a verb.

** る/られる - Potential (Able to do)
   :PROPERTIES:
   :Keywords: can, able
   :END:
   The potential helper verb has two forms, for godan verbs 「る」, and for ichidan verbs 「られる」.

   The potential helper-verb which attaches to the え-stem of a verb ([[*Verb stems]]):
   | あ | い | *う* | *え* | お |
   | か | き | *く* | *け* | こ |
   | さ | し | *す* | *せ* | そ |
   | た | ち | *つ* | *て* | と |
   | な | に | *ぬ* | *ね* | の |
   | ば | び | *ぶ* | *べ* | ぼ |
   | ま | み | *む* | *め* | も |
   | ら | り | *る* | *れ* | ろ |

   There are only two exceptions, 「くる」 and 「する」.
   #+BEGIN_QUOTE
   くる -> こられる
   #+END_QUOTE
   #+BEGIN_QUOTE
   する ー> できる
   #+END_QUOTE

   #+BEGIN_QUOTE
   わたしは(optional)ほんがよめる - As for me, the book is readable
   #+END_QUOTE
   A common translation of this would be 'I can read the book', however again the が is on the book, not on I. If we wanted to say 'I can read the book', the book would need to be marked by を as it is the target of our reading, and 'I' would have to be marked by が as I is the actor.
   #+BEGIN_QUOTE
   わたしがほんをよめる - I can read the book
   #+END_QUOTE
   This is perfectly fine, but it's not what is usually done. Remember, Japanese is not /ego-centric/.

   As we're using a helper-verb, the past, non-past, negative-past and negative-non-past conjugation rules are the same as regular verbs, for 「あるける」 (can walk):
   - あるける - non-past - can walk
   - あるけた - past - could walk
   - あるけない - negative-non-past - can't walk
   - あるけなっかた - negative-past - couldn't walk

** れる/られる - Receptive (passive)
   The real name for the 'passive conjugation' is the /Receptive helper verb/. The receptive helper verb is 「れる」 for godan verbs and 「られる」 for ichidan verbs, and attaches to the あ-stem of another verb ([[*Verb stems]]).
   | *あ* | い | *う* | え | お |
   | *か* | き | *く* | け | こ |
   | *さ* | し | *す* | せ | そ |
   | *た* | ち | *つ* | て | と |
   | *な* | に | *ぬ* | ね | の |
   | *ば* | び | *ぶ* | べ | ぼ |
   | *ま* | み | *む* | め | も |
   | *ら* | り | *る* | れ | ろ |
   Remember! う becomes わ, not あ.

   The receptive helper verb means /receive/ or /get/, we're receiving/getting the action that the helper verb is attached to
   #+BEGIN_QUOTE
   さくらがしかられた - Sakura scolded-got - Sakura got scolded/Sakura received a scolding
   #+END_QUOTE

   Note, the receptive helper verb and the modified verb have different actors. The sentence is not Sakura scolds, someone else (we don't know who) is scolding Sakura, but Sakura is the one in the act of receiving the scolding. This is not the same with all helper verbs.

   The receiver is not always a person:
   #+BEGIN_QUOTE
   水がのまれた - Water got drunk
   #+END_QUOTE
   Even if we add a doer of the drinking, the water is still the actor of the sentence.
   #+BEGIN_QUOTE
   水がいぬにのまれた - Water got drunk by (a) dog
   #+END_QUOTE
   Why is the dog being marked by に? Let's look at a larger sentence:
   #+BEGIN_QUOTE
   さくらは だれかに かばんが ぬす*ま* れた - As for Sakura, someone-by bag stolen-got - As for Sakura, (her) bag got stolen by someone
   #+END_QUOTE
   Who is the actor? It's not Sakura, she's marked by は. It's not the 'someone' as they're marked by に. The bag is the actor of the sentence, the bag /did/ 'got'.

   What is に doing here? に marks the ultimate target of an action. So what is the target of getting stolen? To whom is the stolen item going? It is the 'someone' who stole it.

   # TODO Investigate the nuisance receptive (lesson 13) for further notes
   #+BEGIN_QUOTE
   さくらが だれかに かばんを ぬすまれた
   #+END_QUOTE
   Here the core of the sentence is now 'Sakura got'. What did she get? She got the unfortunate nuisance action of だれかに かばんを ぬすむ, someone stealing (her) bag. /Sakura got her bag stolen by someone/ *not* /Sakura's bag got stolen by someone/.

* TODO です/ます form
   # TODO Add the bit from notes 'the only exceptions'
* TODO Adjectival nouns
  # This all needs compiling
#+BEGIN_QUOTE
穴の 中は たて穴 だった。 アリスは すぐ下に 落さた。- The inside of the hole was a vertical hole. Alice fell straight (directly) down the hole.
#+END_QUOTE

#+BEGIN_QUOTE
でも、 おどろいたことに ゆっくり ゆっくり 落さた。 - But, the surprising thing was that she slowly slowly fell/ But, surprisingly she fell slowly.
#+END_QUOTE
- おどろいたこと doesn't mean 'A surprised thing', it means 'the surprising thing' (surprisingly). The に attached is again to turn it into an adverb. So: 'She fell surprisingly'. Of course, it isn't surprising that she fell, but it is surprising that she fell ゆっくり ゆっくり (slowly slowly).
- ゆっくり is slightly unusual in that it is fundamentally a noun, but we can use it as an adjective without adding に to it. We will see ゆっくり very often.
