# ∅
* Core sentence
  Every sentence is formed of two elements, they are the が-marked noun and the /engine/.

  In all languages there are only two kinds of sentence:
  - A *is* B i.e. Sakura is Japanese
  - A *does* B i.e. Sakura Walks

  #+BEGIN_QUOTE
  さくらが日本人だ - Sakura is Japanese
  #+END_QUOTE
  #+BEGIN_QUOTE
  さくらが歩く - Sakura walks
  #+END_QUOTE

  There are three possible engines:
  - Verb - A does B
  - だ-marked noun - A is B
  - い-"Adjective" ([[*Adjectives]]) - A is B

  The engine *always* comes at the end of the sentence (with the exception of sentence ender particles ([[*Sentence ender particles]]).

  <<Invisible が>>
  The が-marked noun is not always visible in the sentence. It is still present as part of the core of the sentence however. The closest English equivalent to this invisible が is 'it'. Take this example English sentence:
  #+BEGIN_QUOTE
  The ball rolled down the hill. When the ball got to the bottom the ball hit a sharp stone and the ball was punctured and all the air came out of the ball.
  #+END_QUOTE
  This is not a sentence we would ever say in English, once we have established that we are talking about 'the ball' we would instead refer to the ball by 'it':
  #+BEGIN_QUOTE
  The ball rolled down the hill. When it got to the bottom it hit a sharp stone and it was punctured and all the air came out of it.
  #+END_QUOTE
  If we were to completely omit 'it' the sentence would still be easy to understand, we don't *need* to use this it marker each time, but English grammar *demands* it. Japanese does not, hence the 'invisible' が carriage.

  <<∅ pronoun>>
  'It' by itself doesn't really mean anything, we know what it means from context. All of the pronouns I/it/we/he/they can be replaced by an invisible logical particle ([[*Logical particles]]) (most often が) marked /∅ pronoun/. It is important to remember that the が-marked noun *is still there*.

  #+BEGIN_QUOTE
  [∅が]さくらだ - (I) am Sakura
  #+END_QUOTE
  By default 'I' is the default value of this ∅ pronoun. However, if someone were introducing their daughter and said 「さくらだ」 we would understand from context that ∅ meant this/she.

  #+BEGIN_QUOTE
  [∅が]土曜日だ - (Today) is Saturday
  It is Saturday - (Today) is Saturday
  #+END_QUOTE
  From context it is clear that ∅ and 'it' mean 'today'.

  <<Egocentrism>> <<Animism>>
  English is an /ego-centric/ language. Japanese is a more /animist/ language. What this means is that English always wants a person, preferably /I/, but if not I then someone else, or perhaps it will settle for an animal, but always wanting an animate being to be acting. Japanese is not this way:
  #+BEGIN_QUOTE
  わたしはコーヒがすきだ
  #+END_QUOTE
  A textbook would translate this as 'I like coffee'. 'I like coffee' very well might be the English equivalent for this simple phrase, but it is not what this sentence means, and it is not what this structure of sentence means.

  The が is marking the coffee. The coffee is the actor in this sentence, not I. It's not 'I like coffee', I am not /liking/ it. But 'As for me, coffee is likeable/pleasing'.

  The English 'I like coffee' is an /A does B/ sentence. The Japanese is an /A is B/ sentence.

  すき is a *noun*. An adjectival noun ([[*Noun-adjectives]]), but still a noun. It is not a verb like in English.

  #+BEGIN_QUOTE
  わたしはほんがわかる - As for me, the book is readable
  #+END_QUOTE

** Core non-logical sentence
  Japanese is very topic-comment focused.

  Just as with が, every sentence also has a は marked topic, whether we can see it or not
  - アメリカ人です
  - ∅がアメリカ人です
  - ∅は∅がアメリカ人です
  - (I) am the topic, (I) am the subject, and (I) am an American

  Just as a sentence isn't /logically complete/ without a が-marked subject (invisible or otherwise) a sentence isn't /grammatically complete/ without a は-marked topic (invisible or otherwise).

  As with が the default value of ∅ is 'I'.

  The topic is usually a noun, and the comment must be a complete logical clause.

** は vs が
  Topic-comment structure is fundamental to Japanese. Every sentence has a topic marked by は, and a comment consisting of a complete logical clause, a が marked subject and some engine. Both the topic and the subject can be invisible.

  In sentences where both the topic and the subject are the same thing, we can use one or both particles. Choice of particle depends on whether we want to emphasise that the thing at hand is the subject or the topic. For instance, if the person we are speaking to isn't aware of who/what something is, it is bast to introduce that thing with が first to explain what it is/does.

  A topic marker can only mark *old* information. This is important because old-information is unimportant information. New information is the thing we're actually trying to convey to someone. は therefore cannot mark new information.

  There is an example here (in English) about 'I fed the iguana', if we used は people would ask 'what iguana' because you hadn't mentioned it yet. The same is true in English, you would have to say 'I fed my' or 'I fed an'. Keep in mind, there are limits to this. For instance, in English it's very common to say 'I fed the dog', to someone, even if they don't know you have a dog, because it's very normal to own a dog, less so to own an Iguana.

  #+BEGIN_QUOTE
  本を買った - (I) bought a book
  #+END_QUOTE
  This is the most normal way to say 'I bought a book'. As we know the ∅ defaults to 'I' when the context isn't telling us that it's anything else. There is no emphasis, it is just a mutual 'I bought a book'. In this sentence I is the subject and the topic.
  #+BEGIN_QUOTE
  私は本を買った - What I did was buy a book (you might have bought something else or nothing at all, but /I/ bought a book)
  #+END_QUOTE
  If we choose to stress 'I' as the topic we are making わたし into the old information, and the buying of the book into the new information. は has a distinguishing function. When we use は we are either establishing or changing the topic. We know は not only changes the topic to whatever it marks, but it also implies that the comment on the new topic is different to the comment on the old topic. Even if there wasn't an old topic it still implies that the comment is different than the comment on other possible topics. This means that the sentence is implicitly an answer to the question (even if it wasn't asked) 'what did you do?'.
  #+BEGIN_QUOTE
  私が本を買った - It is I who bought the book
  #+END_QUOTE
  Here we have reversed the emphasis. The old information is now the buying of the book and the new information is /I/. Why would we say this? Perhaps someone is looking at an empty space in the bookshelf and wondering what happened. Then we would place the emphasis on it being 'I' who removed the book (by buying it). The book being gone (i.e. bought) is known information by both parties here, even if the exact reason for the books disappearance isn't known. Though, if you're in a bookstore the most likely reason is that it was bought.

  は and が can also mark particularities, as well as generalities:
  #+BEGIN_QUOTE
  花はきれいだ - More likely to mean flowers in general
  #+END_QUOTE
  Flowers are old information, we all know what flowers are, so flowers in general.
  #+BEGIN_QUOTE
  花がきれいだ - More likely to mean these particular flowers
  #+END_QUOTE
  Flowers are new information, so it must be some non-general flowers.

  These are all tendencies however. There is no structural reason for any of these differences. They come entirely from expectations.

  は also adds emphasis forwards:
  #+BEGIN_QUOTE
  おまえみたいな半人前に休みはない - For trainees like you, there are no rests - (More accurately) As for traineers like you, as for rests, there are none
  #+END_QUOTE
  The topic is 「おまえみたいな半人前に」 but the writer has chosen to deemphasise this topic, and introduce a subtopic that is やすみ, 'rests'. This places the emphases on the not existing of the tests.
  # I'd like a better example than this.
** Hidden subjects
** Active and inactive words
  As we know, almost all Japanese words divide into three kinds, nouns, verbs and adjectives, most 'other types' are structurally nouns. There is however another way of dividing words which is used in Japanese grammar, this is to divide them into static 'body words' (体言) and active 'use-words' (用言). Static words essentially boil down to nouns.

  By active words, what is meant is those words that can transform, i.e. the final kana can morph or vanish. This applies to both adjectives and verbs. As we know, verbs and adjectives cannot end in a kanji, they must end in a kana. For Godan verbs the final kana is always an う-row kana, and can become the equivalent kana from one of the other 4 rows. For Ichidan verbs the る kana is dropped. For adjectives we can change the い to く、 か or け, or we can drop the い altogether and add something else.

  Static words (nouns) on the other hand cannot be modified at all (grammatically), we just add logical particles or the copula to them. It is important to understand that when we join a logical particle and a noun together we must regard those two things as a single unit.
  # There are some more notes here on な-adjectives and how a noun + な itself could be 'properly' called a な adjective

  Once we have added the copula (だ) to a noun that unit is now an 'active' word, i.e. we *can* modify it, for instance, as we know, the copula has a て-form which is で, we have modified the final kana of the unit. This is also how we do the past tense of nouns.

  This means that all three engines are 用言, active words/units.

** TODO (Move this) ほしい

  <<ほしい>>
  #+BEGIN_QUOTE
  (わたしは)こねこがほしい - (As for me) a kitten is wanted
  #+END_QUOTE
  「ほしい」 is often translated in English as 'want', but again, it is not a verb, it is an adjective. Again, /I/ is not the actor of the sentence, it is the cat, and it is the cat that is wanted, not 'I want a cat'.

   Remember: 「ほしい」 can only be used with respect to ourselves ([[がる]])

* Particles
  No particles other than が and だ can ever be part of the core sentence ([[*Core sentence]]) and only が is present in every sentence (even if invisible ([[Invisible が]]).

  # TODO Flatten this whole structure

** Logical particles
   A logical particle tells us how the sentence logically holds together. It tells us who does what to whom with what, when and where.

   All logical particles attach to nouns, they *cannot* attach to anything but nouns. If we see a logical particle attached to anything else then we know that that word is functionally a noun.

   The noun and the particle attached to it are an inseparable pair. We must view the two together, they are a question and an answer which form a fundamental unit of the Japanese sentence.

   There cannot be a sentence without が, even if sometimes you can't see it. が can work in A is B sentences, as well as A does B sentences. The other particles can *only* (There is an exception: see [[*で in A is B sentences]]) work in A does B sentences i.e. that is sentences with a verb engine.
   - が - Who (or what) did it?
   - を - Whom was it done to?
   - に - Where did they go?/Where are they?
   - へ - What direction?
   - で - Where was it done? With what was it done?

*** TODO が (/ga/) - Subject <<が>>
# I may need to dig out the episode to cover this particle
**** が particle becomes の in subordinate clauses
     The の particle can replace the が particle in 'subordinate clauses'.

     Remember, the の particle the the possessive particle, and is the only particle that has an exact equivalent in English: /'s/.
     #+BEGIN_QUOTE
     さくら*の*ぼうし - Sakura*'s* hat
     #+END_QUOTE

     Let's look at a sentence where の can replace が.
     #+BEGIN_QUOTE
     私がたべたケーキは(∅が)おいしかった - The cake I ate was delicious
     #+END_QUOTE
     Remember, The が particle marks the thing doing/being something in the sentence. 'I' am eating the cake, so 'I' am marked by が. In this sentence, the main が is not actually visible, it is the invisible ∅-pronoun 'it' (the cake).

     This is the kind of sentence in which we can use の in place of が. We *can't* use の for the main が of a sentence, we can only use it for an /adjectival が/.

     Let's look at an English equivalent:
     #+BEGIN_QUOTE
     Sakura's shouting at the waiter upset me
     #+END_QUOTE
     'Sakura's shouting at the waiter' is a noun, and it is the thing that did the act of upsetting me. The shouting belongs to Sakura because she is the one that did it. This is very similar to the Japanese, only the Japanese doesn't turn the logical clause into a noun but into an adjective:
     #+BEGIN_QUOTE
     私のたべたケーキは(∅が)おいしかった - My eaten cake is delicious
     #+END_QUOTE

*** だ (/da/) - Copula <<だ>>
    For basic use of だ see /core sentence/ ([[*Core sentence]]).

**** Copula て-form
    The copula has a て-form, で, which is used to apply particles to the logical clause:
    #+BEGIN_QUOTE
    ふつうの ウサギ​*では* なかった - As for being an ordinary rabbit, (it) wasn't - (It) wasn't an ordinary rabbit
    #+END_QUOTE
    では here is the て-form of the copula だ, meaning 'as for being (an ordinary rabbit)'

*** を (/o/wo/) - (Direct) Object
    The を particle marks the object of the sentence, the /thing/ that some verb (the engine) is being done to. が marks the thing that is doing the verb.
    #+BEGIN_QUOTE
    わたし​*が*​ケエキ​*を*​たべる - I eat cake
    #+END_QUOTE
    The core sentence here is 'I eat'. The extra を particle marked noun, is telling us more about the engine (eat). /What/ are we eating? We are eating cake.

    #+BEGIN_QUOTE
    わたしがぼーる​*を*​なげる - I threw the ball
    #+END_QUOTE
    The core sentence is 'I threw', and the extra を particle marked noun tells us what we threw i.e. the ball.

    する nouns (verbs) can drop the を particle to form a 'true' する verb

*** に (/ni/) - Target (Indirect Object)
    The に-particle marks the target (indirect object) of an engine. Along with が and を:
    - が tells us who does the doing
    - を tells us what it is done to
    - に tells us what the ultimate target of that doing

    #+BEGIN_QUOTE
    わたしがぼーるをさくら​*に*​なげる - I threw the ball at/to Sakura
    #+END_QUOTE
    Sakura is the destination, the target. It is important to note here that the logical particles tell us what happened. The order of the words doesn't really matter the way it does in English.

    #+BEGIN_QUOTE
    わたし​*に*​さくらがぼーるをなげる - Sakura threw the ball at/to me.
    #+END_QUOTE
    #+BEGIN_QUOTE
    ぼーるがわたし​*に*​さくらをなげる - The ball throws Sakura at me
    #+END_QUOTE
    Obviously this final example doesn't make any sense (although we might want to say something nonsensical like this in a fantasy novel or something) but we can say whatever we like in Japanese so long as we use the right logical particles.

    If we are going somewhere, or sending something somewhere, or putting something somewhere, we use に.
    #+BEGIN_QUOTE
    [∅が]みせ​*に*​いく - (I) will go to the shop
    #+END_QUOTE

    に gives us the target of an action in the literal sense, and also the target in a volitional sense, i.e. the aim of our action.
    #+BEGIN_QUOTE
    [∅が]みせ​*に*​たまごをかい*に*いく - (I) will go to the shop to buy eggs
    #+END_QUOTE
    かい is the い stem of かう, to buy ([[*Verb stems]]). The logical particles can only mark nouns. The い-stem of a verb is the equivalent noun form of it. Just as in English 'I like swimming', /swimming/ is a noun, 'I go to the shop for the purpose of buying eggs', this /buying/ is also a noun.

    As well as identifying a place we will go to, に can also specify a place we are currently at:
    #+BEGIN_QUOTE
    ∅がみせ​*に*​いる - (I) am/is at the shop
    #+END_QUOTE
    This に is still marking a target, just not a future target. In order for something to be somewhere it must've gotten there, and so に specifies the target of some past action. We can also use this for inanimate objects:
    #+BEGIN_QUOTE
    ほんは∅がテーベルのうえ​*に*​ある - As for the book, (it) exists/is on/at the table.
    #+END_QUOTE
    This use of に also applies to times as well as places, see: /time expressions/ ([[*Time expressions]]).

    Finally, に can also mark a transformation. If /a/ becomes /b/, then に also marks /b/, the thing a is becoming.
    #+BEGIN_QUOTE
    さくらは∅がかえる*に*なった - Sakura became a frog
    #+END_QUOTE
    Of course this example is a bit of a joke, but there are of course various every day things that become other things. This form of expression is also used much more often in Japanese than in English.
    #+BEGIN_QUOTE
    ことし∅が十八さいになる - This year (I) become 18 years old
    #+END_QUOTE
    #+BEGIN_QUOTE
    あとで∅がくもりになる - Later (it (the weather) will) become cloudy
    #+END_QUOTE
    See also how to use 「なる」 with adjectives ([[Becoming an adjective]])

*** の (/no/) - Possessive
    The の particle, or the /possessive particle/ functions just like the English /'s/.
    #+BEGIN_QUOTE
    さくら​*の*​はな - Sakura's nose
    #+END_QUOTE
    #+BEGIN_QUOTE
    わたし​*の*​はな - Me's (my) nose
    #+END_QUOTE
    Luckily in Japanese we don't have to worry about his/her/my/their, we just use の.

    <<の-adjectives>>
    Because this is the /possessive particle/ we can use this in another slightly different way. 「あか」 has an /adjectival/ form in 「あかい」, but not all colours have this form. The Japanese for pink, 「ピンクいる」 (lit: pink-colour) doesn't have an adjectival form in 「ピンクいろい」, nor can we use it as a secondary engine with な. So what are we to do? Well we can use the の-particle:
    #+BEGIN_QUOTE
    ピンクいる​*の*​どれすが - The pink dress (literally: The dress belonging to the class of pink things)
    #+END_QUOTE
    #+BEGIN_QUOTE
    うさぎ​*の*​OSCAR - Oscar the rabbit (literally: Oscar belonging to the class of rabbit)
    #+END_QUOTE

    # TODO: As a normaliser, I don't think I have notes on this, I may have omitted writing them lesson 16
    # #+BEGIN_QUOTE
    # 目に 止まるのは - Eye-at as for stopped-thing - The thing that stopped her eye - The thing that caught her eye
    # #+END_QUOTE

  A similar example with の that isn't structurally very complicated, but is very unlike what would be said in English. This comes from the song 'the bells of notre dame':
  #+BEGIN_QUOTE
  朝のパリに響くのは鐘だよ
  #+END_QUOTE
  Where are the A and the B of this sentence? This is an A is B sentence. The は-marked topic is 「朝のパリに響くの」 so の is bundling 「朝のパリに響く」 into a single noun which we're talking about, 'Resounds in morning paris' -> 'That which resounds in morning Paris'. The A or が marked topic is that which has just been defined for us by の (the resounding thing in a parisian morning).

  Why is it being put this way? Because it /can/ be. Again, it is cumbersome in English, but not in Japanese.

*** へ (/e/) - Direction
    This is a very simple particle, it duplicates a single use of に. When we say /a is going to b/ we can freely substitute に with へ. This is *all* is can do, it cannot even mark the case where something /is/, only where it is /going/.
*** で (/de/) - Means
    #+BEGIN_QUOTE
    [∅が]こうえんにいく - I go to the park
    #+END_QUOTE
    If we say 'I went by bus' or 'I ate with chopsticks' we use で for the thing we did it with, the means by which we performed the action.
    #+BEGIN_QUOTE
    [∅が]バス​*で*​こうえんにいく - I go to the park by bus
    #+END_QUOTE

**** で in A is B sentences
  で is not absolutely restricted to 'a does b' verb sentences (though most of the time it's used in verb sentences). What で is really restricted to is clauses that modify 用言, and as we have just learned a 用言 can be a verb, can be an adjective, but can also be a noun+copula.
  # TODO Update structured notes with this information

  So what is で actually doing?

  As we know, there are three 'positional' logical particles, they are:
  - に - Where something goes to or where it is once its got there
  - え - Directional particle
  - で - The boundary or limit within which something happens

  Usually the limit described by で is a physical area, though it doesn't have to be. で tells us the boundary within which an action or (here's the new part) a state of being takes place. In other words, it can be adjectival.

  #+BEGIN_QUOTE
  世界で一番おいしいラメン - The most delicious ramen in the world
  #+END_QUOTE
  Why are using で in this case? 「世界で」 is defining the limit within which something is happening, in this case it's defining the limit within which the state of being applies. We are talking about the most delicious ramen in the world, the limit of the state of being the most delicious ramen is the world.
  #+BEGIN_QUOTE
  この町で一番おいしいラメン - The most delicious ramen in this town
  #+END_QUOTE

  # How does this relate to means tho?
  # TODO: Redo で lesson

  We could say:
  #+BEGIN_QUOTE
  世界の一番おいしいラメン - The world's most delicious ramen
  #+END_QUOTE
  But this isn't modifying the quality of おいしい (putting a limit on おいしい) in the same way that で is. It is modifying ラメン.

  We can also say:
  #+BEGIN_QUOTE
  このラメンは世界で一番おいしい - This ramen is the most delicious in the world
  #+END_QUOTE
  But we can't say:
  #+BEGIN_QUOTE
  このラメンは世界の一番おいしい - This ramen is the most delicious in the world
  #+END_QUOTE
  Because in Japanese words can only modify words that come after them, they can't modify words that come before them, の cannot modify おいしい which is an adjective, it can only modify ラメン which is another noun, and because ラメン  is on the wrong side of it, we can't use it.

  Finally, since we now know that a noun+copula functions as a 用言 (an active element) we can also say:
  #+BEGIN_QUOTE
  世界で一番有名なアンドロイド - The most famous android in the world
  #+END_QUOTE
  世界で couldn't modify 有名 on its own because 有名 is a noun, but joined with な (the connective form of the copula だ) it can.

  The same thing is happened when we say:
  #+BEGIN_QUOTE
  みんあで踊る - We all dance
  #+END_QUOTE
  #+BEGIN_QUOTE
  二人で踊る - The two of us dance
  #+END_QUOTE
  #+BEGIN_QUOTE
  一人で踊る - Dance alone
  #+END_QUOTE

** Non-logical particles
   Non-logical particles are not part of the logical structure of a sentence. They are neither the thing we are saying something about, nor what we are saying about it. They also do not tell us more about the engine of the sentence as the other logical particles do.

*** は /wa/ topic exclusive
    The は-particle can be thought of as a /flag/. It simply marks something as the topic of the sentence, but doesn't say anything about it.

    An exact translation of the は particle would be 'As for /x/'. 「わたしは」 therefore means 'As for me', *not* 'I am' (わたしが).

    A commonly mistranslated sentence is:
    #+BEGIN_QUOTE
    わたし​*は*​日本人だ - +I am Japanese+
    #+END_QUOTE
    Referring back to the core sentence ([[*Core sentence]]) we can see that the が-marked noun so we don't actually know who or what the subject is. One may ask /'well why don't we just treat the は particle as if it is marking the subject'/. In this example it is obvious that the topic marked by は is the same as the subject marked by が, but there are many more cases where this is not true, leading to much confusion down the road. Let's look at a similar sentence. You are at a restaurant, the waitress is asking what you would like:
    #+BEGIN_QUOTE
    わたし​*は*​うなぎだ - +I am an eel+
    #+END_QUOTE
    Treating は as 'I am' doesn't work. As we now know the default value of the ∅ pronoun is 'I', but in this context it's clear that we're talking instead about /what/ we want to eat. 「わたしはうなぎだ」 therefore means 'As for me, eel'.
    #+BEGIN_QUOTE
    わたし​*は*​[∅が]日本人だ - As for me, (I) am Japanese
    #+END_QUOTE
    #+BEGIN_QUOTE
    わたし​*は*​[∅が]うなぎだ - As for me, (what I would like to order) is eel
    #+END_QUOTE

    #+BEGIN_QUOTE
    わたし​*は*​[∅が]さくらにぼーるをなける - As for me, (I) threw the ball at Sakura
    #+END_QUOTE
    #+BEGIN_QUOTE
    ぼーる​*は*​わたしがさくらに[∅を]なける - As for the ball, I threw (it) at Sakura
    #+END_QUOTE
    This time the を marked noun (not the が marked noun) has become invisible([[Invisible が]]), because what we're throwing is now marked by the は particle, ∅ here has taken the value of 'it'. Even without は we might already know what 'it' was that was thrown from context. The important thing to understand here is that as we change the logical particles from one noun to another we change the meaning of the sentence, but when we change the non-logical particle は from one noun to another it makes no difference to the logic of the sentence. It may make some difference to the emphasis, but it makes no difference to who is doing what or what they're doing it to.

  Japanese is a 'topic prominent' language. Topic-comment structure is a very fundamental aspect of Japanese in a way that it isn't in English. It is for this reason that we so often say 'as for x' when that isn't how we would say something in English.
  #+BEGIN_QUOTE
  アフリカはライオンはいるがトラはいない
  #+END_QUOTE
  In this sentence we have three は s in a very short space. These are *all* topic markers. The first は is the overall topic marker, it's saying 'speaking of Africa', everything that follows is going to be a comment on the topic of Africa. Everything that follows must be a logical clause, it doesn't matter how small the clause is, but is must be a logical clause. What we have in this example is a sentence consisting of two logical clauses, each of which contains a 'sub-topic'. Each logical clause also has a topic statement preceding it. In full:
  #+BEGIN_QUOTE
  アフリカはライオンは[∅が]いるがトラは[∅が]いない
  #+END_QUOTE
  Note how there is the contrastive conjunction は used in this sentence. You can tell that it is this が and not the other because it follows a verb (いる) and the logical particle が can only mark nouns.

  Why are they doing this?

  It is because は is used to distinguish things.
  #+BEGIN_QUOTE
  アフリカはライオンはいるがトラはいない - Speaking of Africa, speaking of lions, they exist but speaking of tigers, they don't exist.
  #+END_QUOTE
  We would never say something like this in English, because the topic marker は is very /agile/, but the methods of introducing a topic in English are not, so they seem forceful or cumbersome.

  When we introduce something using は we are implicitly saying that the comment on the new topic is different from the comment on the old topic. If we wanted to say that the comment is the same we would use the topic marker も.

*** も /mo/ topic inclusive (also)
    も is another non-logical topic-marking particle. も marks the topic of the sentence in the same way that は does. The difference is that while は can mark the topic of the sentence and *can* also change the topic of the sentence, も declares the topic of the sentence but can *only* change the topic of the sentence. We cannot use も unless we are changing the topic of the sentence.

    For context, up until this point the topic of our conversation has been the rabbit, now we are switching to talk about Alice.
    #+BEGIN_QUOTE
    アリス​*も*​ ウサギの 穴に とび こんだ。 - Alice also jumped into the rabbit hole.
    #+END_QUOTE

    When we change topic with も we're saying that the comment about the previous topic (the rabbit and that it jumped) is the same as our new topic (Alice). When we change the topic with は we are doing the opposite, we are drawing a distinction between the two.

   も = as-much-as:
   #+BEGIN_QUOTE
   いちま円もかかた掛かる - He took as much as 10,000 yen
   #+END_QUOTE
   #+BEGIN_QUOTE
   ケエキを食べてもいい - Is it alright if I eat this cake? lit. If I go as far as to eat the cake is that alright?
   #+END_QUOTE

    In English 'as much as' can also be said as 'even'. The same is true in Japanese.
    - 誰もない - Not even someone
    - 何もない - Not even something
    - 少しもない - Not even a little

    See also /でも/ ([[でも]]).
*** より /yori/ from (comparison)
    <<より>>
    「より」 is a non-logical particle (it doesn't have to be attached to a noun). It can go after just about anything, a complete logical clause, a noun, an adjective, whatever. It's most basic meaning is 'from':
    #+BEGIN_QUOTE
    さくらより - From Sakura
    #+END_QUOTE

    「より」 means 'from', we already have another word meaning 'from', 「から」. The difference between the two is that 「から」 marks the 'A' in 'A from B' in such a way that it is treating 'A' as the starting point, or point of origin:
    #+BEGIN_QUOTE
    日本からきました - I came/come from Japan - Japan is my point of origin
    #+END_QUOTE
    This often gains the metaphorical meaning of 'because', as 'some event' is the point of origin for 'some other event':
    #+BEGIN_QUOTE
    さむいからコートをきる - Because it's cold I wear a coat
    #+END_QUOTE

    「より」 means 'from' in a very different sense. The directional metaphor is concentrating not on the origin of 'A from B' but in the distance/difference of 'A from B'.
    #+BEGIN_QUOTE
    さくらはメアリよりきれいだ - From Mary, Sakura is pretty - Distinguished from Mary, Sakura is pretty
    #+END_QUOTE
    We are still using 「メアリ」 as the 'base point', the point of comparison, and because of this comparative nature we're *not* saying that 'Sakura is pretty while Mary isn't', we're saying that 'taking Mary as the point of comparison, Sakura is pretty (therefore more pretty i.e. prettier)'. Notice how this has the same meaning as the original sentence 「マアリ*より*さくら*のほう*がきれいだ」 without needing to use 「ほう」.

    We can also use 「より」 in other contexts:
    #+BEGIN_QUOTE
    今年の冬はいつもより寒い - Comparing from always, this year's winter is cold - This year's winter is colder than usual.
    #+END_QUOTE
    - Note: 'always' is a kind of hyperbole in a way

    #+BEGIN_QUOTE
    さくらは人より傾い - Sakura is clever compared to people - Sakura is clever compared to (most) people - Sakura is smarter than most
    #+END_QUOTE
** Alogical particles
*** と (/to/) - And (exclusive)
    <<と and>>
    Alogical particles aren't simply markers. The と particle 'ands' two nouns together. It is therefore doing something in the sentence, it is joining a noun to another noun and inheriting its logical particle, but the と particle has no function of its own.
    #+BEGIN_QUOTE
    さくら​*と*​メイリー​*が*​あるいていた - Sakura *and* Mary were walking
    #+END_QUOTE

*** や (/ya/) - And (inclusive)
    When putting two clauses together we use the て-form as an equivalent to 'and'. When putting two things together we can use the と (exclusive 'and') and や (non-exclusive 'and') particles. や lists things but not exhaustively, there may be more: 'fish and chips (and stuff)'.

    #+BEGIN_QUOTE
    ぎっしり ならんだ とだな や 本だな だった。- tightly lined-up cupboards-and bookshelves-was
    #+END_QUOTE
*** と (/to/) - Quotation
    # TODO Is this the right place for this particle?
    #+BEGIN_QUOTE
    「おもしろい ことが ない」​*と*​ アリスは 言った - Nothing interesting is happening said Alice
    #+END_QUOTE

    #+BEGIN_QUOTE
    おもしろい ことが ない- No interesting thing (abstract thing) exists - Nothing interesting is going on here
    #+END_QUOTE
    #+BEGIN_QUOTE
    アリスは 言った - Alice said
    #+END_QUOTE
    The と particle marks a quotation. When we quote someone as saying something or as thinking something we use this と particle. We also use these square brackets which are the equivalent of English quotation marks, but in speech we cannot see these, so we also use と (and clearly use と in writing regardless also).

    What と does structurally, is it takes whatever it marks which could be a simple word or phrase, to a whole paragraph, to anything with all sorts of grammar going on, and turns what it is marking it into a single noun. This is used not only to mark things people say and people think, but to mark all sorts of things. This と structure can therefore make a quotation act as a modifier to whatever follows, in the previous example it is modifying 言う (to say), or to think or feel, but could be many things:
    #+BEGIN_QUOTE
    ホッとする
    #+END_QUOTE
    Note 「ホッ」 is the sound effect for a sigh of relief. We aren't saying here that someone breathed a sigh of relief. What we're saying is that they /enacted what was expressed by the sound effect/ i.e. They were relieved. In 「山にのぼろうとする」 we're enacting the feeling of setting out to climb the mountain.

    #+BEGIN_QUOTE
    でも ウサギは ピョンピョン​*と*​ はしり つづけた。 - But as for the rabbit, (it) kept on running in a /pyonpyon/ manner
    #+END_QUOTE
    「ピョンピョン」 - The sound of a small thing jumping along (an onomatopoeia hence katakana). Once again we're using the quotation particle と to describe the way in which the rabbit ran, it ran in the way it sounds, it ran like a small thing jumping along (Note there are no quotation marks around onomatopoeia).

     The most basic thing that can follow と is 言う in which case it can be used as a literal quotation of something that's been said (as we've already seen) but can also be used as a way of saying how something is said or what it's called:
     #+BEGIN_QUOTE
     ふしぎの国のアリスという本 - The book called 「ふしぎの国のアリス」
     #+END_QUOTE
     Note: という is usually written in Kana when it precedes something

     <<って>>
     という can be reduced down as far as just って. という -> っていう -> って:
     #+BEGIN_QUOTE
     ふしぎの国のアリスっていう本 - The book called 「ふしぎの国のアリス」
     #+END_QUOTE
     #+BEGIN_QUOTE
     ふしぎの国のアリスって本 - The book called 「ふしぎの国のアリス」
     #+END_QUOTE


**** とする - Trying to do something, how we regard something, as something, as subject
     <<Trying to do something>>
     #+BEGIN_QUOTE
     山にのぼろうとする - Try to climb the mountain
     #+END_QUOTE
     Note: に is normal here because we are climbing to the /target/ of the summit.

     See again how we're using the と quotation particle once again. と is encapsulating, not the words or thoughts of someone, but the meaning of 「山にのぼろう」 and putting that meaning into action (する). Why does this mean 'try'? A precise translation may be derived from 「のぼろう」 - have the will to climb, and 「する」 to do. I have the will to climb the mountain, and I will do it, (but I may not have the ability). Hence, /try/.

     <<Regard something>>
     #+BEGIN_QUOTE
     ∅が さくらを *日本人と* する - We Sakura "Japanese person" enact - We assume/take Sakura to be Japanese
     #+END_QUOTE
     We are thinking/acting according what is expressed by the quote.

     #+BEGIN_QUOTE
     かばんを *まくらと* する - Use bag as a pillow
     #+END_QUOTE
     Not literally: turn bag into a pillow.

     <<As something>>
     #+BEGIN_QUOTE
     会長*として* - As President...
     #+END_QUOTE
     The closest equivalent to this in English is 'as'. i.e. 'My opinion /as/ a private person'.

     We can also use it as 'for':
     #+BEGIN_QUOTE
     アメリカジン*として*小さい - She's small for an American. (As an American, she's small).
     #+END_QUOTE

     <<As subject>>
     Remember the は particle is the topic marking particle:
     #+BEGIN_QUOTE
     さくらは ∅が 日本人だ - As for Sakura, (she) is a Japanese person
     #+END_QUOTE
     #+BEGIN_QUOTE
     さくらって ∅が 日本人だ - Speaking of Sakura, (she) is a Japanese person
     #+END_QUOTE
     This is a very casual use, we can't use 「という」 in place of は but we can use って. The point is that this is still very logical.

*** と (/to/) - Conditional
  <<と conditional>>
  A /conditional/ is a statement like 'if' or 'when'. In Japanese there are many conditionals. We've already covered と as the /exclusive-and/ particle ([[と and]]). This is exactly the same と as is used for conditionals. It's not the same と as the quotation-particle, but knowing that it is the same と as the exclusive-and particle makes understanding the conditional grammar much clearer.

  と is a particle, but it's not a logical particle. It's also not a non-logical particle. Remember that it is an /a-logical/ particle, meaning that it carries the meaning of the logical particle attached to the second of the two nouns it connects. In the case of conditionals however, と doesn't attach to a noun, but to a logical clause.
  #+BEGIN_QUOTE
  冬になる*と*寒くなる - When it becomes winter it becomes cold
  #+END_QUOTE
  Why is this connected by と? We're saying that when/if something happens, there is only one result.

  と can also be used in a hyperbolic fashion.
  #+BEGIN_QUOTE
  (∅が)それを食べる*と*病気になる - Eat that and (you'll) get sick
  #+END_QUOTE
  It is possible that someone might not get sick, but this is a hyperbole, we're trying to say to someone that 'if you eat that you *will* get sick'. 'If you keep playing those games you *will* fail the exam'.

  We can also use this と to indicate that something is necessary:
  #+BEGIN_QUOTE
  行かない*と*ダメ - If I don't go it will be bad
  #+END_QUOTE
  #+BEGIN_QUOTE
  勉強しないといけない - If I don't study it won't go - If I don't study it won't do - I must study
  #+END_QUOTE

  We may even here the 'if' on it's own without the 'then':
  #+BEGIN_QUOTE
  逃げないと! - If we don't run... (something bad will happen) - We must run! - Run!
  #+END_QUOTE

  Because と is exclusive, it's a bit more absolute and also a bit more colloquial than other conditionals like ば ([[ば conditional]]).

** TODO Sentence ender particles
** ても/でも
   も = as-much-as i.e. 'even though'. The て-form + topic-marker combination forms a complete logical clause that is subordinate to (requiring comment from) the following clause.

   「ても」 doesn't indicate a positive result or a negative result, it indicates a contrasting result:
   #+BEGIN_QUOTE
   雨が 降っ​*ても*​ ∅が こうえんい 行く - Even though it's raining we can still go to the park
   #+END_QUOTE

   <<でも>>
   This is where 「でも」 itself, rightly translated as 'but', comes from; 「でも」 wraps up whatever came before it literally meaning 'as much as [that] is [so]...'. 「でも」 is the all purpose 「ても」 contrast marker. The で in 「でも」 is the て form of だ and it is attached to も, the inclusive /and/ particle and the reverse subject particle of は:
   #+BEGIN_QUOTE
   ∅が 空っぽの びんでも - It empty jar-is as-much-as
   #+END_QUOTE

   As we know だ (the copula) couples together two nouns. What is it coupling? It is couple the sentence that came before it and the ∅ pronoun (it). So 誰でも doesn't mean 'everyone', it means anyone.
   - 誰でも - Anyone - 誰でもできろ - Even if it's anyone, they can do it - Anyone can do it
   - 何でも - Anything - 何でもいい - Even if it's anything, it's good - Anything is good
   - どうでも - However (Whatever way) - どうでもいい - Whatever way is fine

** ては/では (ちゃ/じゃ)
   While も is the additive, including particle, は is the subtractive, excluding particle. So, while も means 'as much as', は means 'as little as'. We tend to use 「でも」 in positive contexts, and 「では」 in negative contexts. Often this 「ては」 gets contracted into just ちゃ/じゃ.

   We can use 「ては」 as the connector between two clauses, and it implies that the second clause is unwanted:
   #+BEGIN_QUOTE
   雨が 降っ​*ては*​ ∅が こうえんい 行けない - Rain falls and (negative comment expected) we park-to can-go-not
   #+END_QUOTE
   This is much the same as how も is followed by a comment, here we follow は with a comment explaining why the rain falling is a bad thing.
   #+BEGIN_QUOTE
   [∅が] いもうとと けんかし​*ては*​ ははに しかられた - I sister-with quarrelled-and (negative result) : mother-by scolded-got
   #+END_QUOTE

** だって - Somebody said, because, but, even
   「だって」 is usually translated as 'because' and 'but' and 'even' and 'somebody said'. The reason for these myriad definitions is that 「だって」 isn't really a word. 「だって」 is simply the copula だ, and って. This is not the て-form of だ, it is the same って as the contraction of the quotation particle 「という」 ([[って]]).

   <<Somebody said>>
   #+BEGIN_QUOTE
   [∅が] 明日は [∅が] 晴れだ って(という) - (Someone/forecast/people) as for tomorrow (it) fine will-be says
   #+END_QUOTE

   <<But>>
   #+BEGIN_QUOTE
   1. さくらがきれいだね - Sakura's pretty isn't she
   2. だって 頭が 弱い - But she's not very smart (lit: head is weak)
   #+END_QUOTE
   Why does this mean 'but'? What we're doing is taking the thing that was just said and adding だ to it. Then quoting what they just said: 「だって」 - You say that (Sakura is pretty), and the implication is that something contradictory will follow. This usage usually has a childish, or somewhat argumentative tone.

   <<Because>>
   Just as we can use 「だって」 as 'You say a thing is so, but...' We can also use 「だって」 as 'You say a thing is so, this is because (some explanation)'.

   What both of these phrases are saying is 'You have said something, and I don't dispute it, but here's something we can add to it that undermines the narrative that you're trying to put forward'. This is the same in both cases, it's only the translation to English that mandates a distinction.

   <<Even>>
   When we say 「だって」 to mean 'even' we're not using だ to refer back to the previous statement. We are usually attaching it to something in particular within the statement we're making.
   #+BEGIN_QUOTE
   1. さくらができる - Sakura can do that
   2. わたしだって - Say (it) is me - I can do that
   #+END_QUOTE
   This has a different implication to わたしもできる which just means 'I can do that too', 「わたしだって」, because it is associated with the phrases above carries the /tone/ of '/even I/ can do that'.

   #+BEGIN_QUOTE
   わたしだってホトケーキがつくられる - Even I can make hot cakes
   #+END_QUOTE
   In this example we aren't saying anything contradictory to someone else but it still has the implication of /even/.

** か
   <<か>>
   As covered in the last lesson か turns the statement it is attached to into an hypothesis or question. か can also, and especially in colloquial usage turn things into a negative. This is also done in English:
#+BEGIN_QUOTE
Do you think I'm going to do that? - I'm not going to do that!
#+END_QUOTE


** Extra: Sentence ender particles
*** ね
   ね is a marker for information that the speaker assume the listener to know already. It is the marker for shared information/feelings.

*** よ
    よ is the opposite of ね. ね marks information that one assumes the listener to already know, よ marks information that one assumes the listener doesn't already know.

    よ can be assertive, and can be used to contradict, but most of the time it's a friendly particle that introduces some information the listener doesn't know but you think they will be interested in.

*** よね
    This might seem a little confusing at first, notice however it's よね, you can't say ねよ. The reason for this is that you're introducing the listener to something that they don't know, and then immediately treating that information as shared.

*** な
    な is not really a particle in terms of Japanese grammar, it's /technically/ an exclamation, but it functions in much the same way. In a previous lesson many sentence-enders involving な were discussed, in each of these cases な was the connective for of だ. This な is different.

    While ね marks information known to the listener, よ marks information unknown to the listener, な marks a remark that is addressed to oneself.
    #+BEGIN_QUOTE
    暑いな - Gosh it's hot
    #+END_QUOTE
    One may be intending to share this statement with someone else.

    な can also be used within a sentence, hence why even though technically an exclamation it functions like a particle, marking that something is directed at oneself.

    There are also occasions where men will use な where women would use ね. In these cases the difference in meaning is 'You agree with me don't you' for ね and 'Well that's what I think and I don't care if you agree with me or not' for な.

*** かな
    See: ([[かな]])

*** かい
   かい is simply a softened and colloquial form of か. In casual speech we don't use か as a sentence-ender question marker very often (though we do use it in other positions). Usually we will just use a rising intonation (or a question mark on its own in typed speech), we may use の (which is ambiguous because it can mark a question or an explanation), but we can occasionally use かい. かい is a predominantly masculine (though older women may use it) and rather 'folksy' way of marking a question.

*** だい
   だい is just だ+かい. This is the form of かい we use in copula-ending sentences. Everything about かい applies to だい except a particularly common colloquialism which is 「どうだい」 meaning 'how is [something]'.

*** ちょうだい
   This isn't related to かい or だい but is an informal equivalent to ください, so usually it is added to the て-form of a verb to ask someone to do something. It is slightly feminine but not exclusively.

*** Emphasisers
   - せ - verbal exclamation mark that adds force - masculine - far more common in anime and manga than in real life
   - そ - verbal exclamation mark that adds force - masculine - far more common in anime and manga than in real life
   - さ - more common verbal exclamation mark, slightly masculine but not exclusively. Very likely to hear in real life

*** pseudo-sentence enders
   Often sentences end in conjunctions. This has been covered previously.

   # There are some notes here about how kara can add force

   し is very similar to から, it's most common and regular use is to combine reasons. There is an example here, it essentiall goes: reason a し reason b し therefore... you can therefore use し with only one reason to imply that there are other reasons also. し has the effect of softening a reason, so saying something like 'because riding a bike is forbidden here' + し sounds a bit friendlier. This tactic of 'vaguing' things up is common in English using words like 'like' and 'kinda'
*** Particle combinations
  There's really no such thing as double particles or particle combinations as such, the particles are really just doing what they do all the time.

  It is important to remember the distinction between logical and non-logical particles.

  You can't combine any of the logical particles with any of the others, because logical particles mark nouns with their function in the sentence. What you can combine them with is the non-logical particles, notably the two non-logical topic markers は and も. Combining in this way doesn't clash at all logically as は and も don't tell us anything about what a noun is doing in the sentence.

  The two primary logical particles が and を don't combine with the non-logical particles because any sentence that is directly transitive, that is a sentence where the actor acts upon an object directly. 'I eat' for example is intransitive, but 'I eat bread' is intransitive.

  # There are some notes here on English propositions and other examples

  Any sentence with the を particle is directly transitive, the use of any other particle i.e. と or に is indirectly transitive.

  Because of the directness of が (the thing acting) and を (the thing being acted upon) they can't have a non-logical particle appended to them. If you wanted to attach a non-logical particle you would simply leave the logical particle out, and because が and を are so fundamental they would be understood by the hearer in Japanese.

  We can pair the remaining logical particles with any non-logical particle, the reason for which isn't to make any kind of unusual pair-combination, but to simply use the functions of both particles at the same time.
  #+BEGIN_QUOTE
  ∅が冬には雪だるまを作る - As for in the winter, we make snowman
  #+END_QUOTE
  We don't need this は, but we can choose to use it to make 'in winter' the subject of the sentence. は also differentiates winter from the other seasons, implying we only make snowmen then.
  #+BEGIN_QUOTE
  ∅が春にも雪だるまを作る - We make a snowman in the spring as well
  #+END_QUOTE
  We do need に so that the topic is about *in* winter.

  #+BEGIN_QUOTE
  学校には行く - Going to school
  #+END_QUOTE
  This sentence carries the implication that we're going to school but not going somewhere else (because of the exclusiveness of the は particle).
* Tense
  In Japanese the tenses are not the same past, present and future tenses we're familiar with from English.

** Non-past (future) tense
   The basic, dictionary-form of verbs are in the /non-past/ tense. The Japanese non-past tense is very similar to the English non-past tense. What is the /English/ non-past tense? It is again the plain dictionary form of a verb: /eat/, /run/, /walk/ etc. It is unnatural in English to say 'I eat cake', to mean 'I am eating cake'. It is natural however to use the non-past tense to say 'Sometimes I eat cake' or, in the explicitly future tense 'I will eat cake'. Japanese is just the same as English in this way. It is rare we use this form for talking about things actually happening right now, except in cases like literary descriptions.

   Just as the ∅ pronoun ([[∅ pronoun]]) defaults to 'I', the non-past tense defaults to the future.
   #+BEGIN_QUOTE
   さくらが歩く - Sakura will walk
   #+END_QUOTE
   #+BEGIN_QUOTE
   犬がたべる - Dog will eat
   #+END_QUOTE
   'Sakura walks' is possible, but isn't the most natural way.

** Present (continuous)
   <<Present continuous>>
   In order to say something like 'Sakura is walking' we need to combine the verb 「歩く」 - /to walk/ with the verb 「いる」 -  /to be/. This is done by putting the verb into the て-form ([[*て-form]]).
   #+BEGIN_QUOTE
   さくらが歩いている - Sakura is walking
   #+END_QUOTE
   #+BEGIN_QUOTE
   犬がたべている - Dog is eating
   #+END_QUOTE
   The core sentence here is 'Sakura is existing', the て-form verb, what we shall call a /secondary engine/ which modifies the main engine. In what state is Sakura existing? She is existing in the state of eating.

   # TODO Add a link here to the expanded secondary engine write-up (if one gets written)

** Past
   <<Verb past>>
   To form the past tense of a verb we need to take the verb stem([[*Verb stems]]) and add た for ichidan and った for godan.
   #+BEGIN_QUOTE
   犬がたべた - The dog ate
   #+END_QUOTE

   <<Adjective past>>
   If we want to put an adjective into the past tense we drop the い and add かった.
   #+BEGIN_QUOTE
   こわい ー> こわかった - Was scary
   #+END_QUOTE

** Negatives
   Because 「ない」 is also an adjective, the past tense of it is just 「なかった」.

   | Non-past             | Past                     |          |
   |----------------------+--------------------------+----------|
   | さくらがはしる       | さくらがはしった         | Positive |
   | さくらがはし*ら*ない | さくらがはし*ら*なかった | Negative |

   As we know 「さくらがはしる」 is not very natural Japanese, instead we would say 「さくらがはしっている」. For this, all we need to do is put the 「いる」 into the past tense:
   #+BEGIN_QUOTE
   さくらがはしっている -> さくらがはしっていた - Sakura was running
   #+END_QUOTE

** Time expressions
   If we want to make it clear that we are talking about a future event we can add a time expression. By prefixing a sentence with あした (tomorrow), we can make it clear that what we will be doing, we will be doing tomorrow.
   #+BEGIN_QUOTE
   あした[∅が]ケーキをたべる - Tomorrow I will eat cake
   #+END_QUOTE
   Note how we simply preface the sentence with 'tomorrow', just like we would in English. This is the case with all /relative-time nouns/, 'yesterday', 'tomorrow', 'the day after tomorrow', 'next week', next month', 'next year'.

   For /non-relative/, i.e. /absolute/ time expressions we must use the に-particle:
   #+BEGIN_QUOTE
   火曜日​*に*​[∅が]ケーキをたべる - On Tuesday I will eat cake
   #+END_QUOTE
   We must attach に in all the same places we would attach on/in/at in English. 'On Tuesday', 'in March', 'at 12 o'clock'. Fortunately in Japanese we only need to use the one particle.

   #+BEGIN_QUOTE
   そのとき、白い ウサギが とおり すぎた。
   #+END_QUOTE
   「そのとき」 - That time. In this sentence it is used to mean 'just at that moment' (just as Alice said that)

* て-form
  The て-form of a verb is its /connective form/.

** Constructing the て-form
   Japanese verbs fall into three groups: /Ichidan/, /Godan/, and /irregular/

   The first group are /ichidan/ (lit: one level) verbs. Morphing these verbs is easy, we simply remove the る and add our new ending. Ichidan verbs can only end in either いる or える (phonetically).

   The second group is by far the largest, the /godan/ (lit: five level) verbs. This group contains verbs that end in all of the possible verb endings: う つ る - ぬ ぶ む - く ぐ - す. Each of these ending groups has its own way of being morphed, though although they're 'five level' verbs, two of the groups use the same method so we only need to learn 4 methods. Confusingly this means that godan verbs can end in いる or える, most of these will still be /ichidan/ verbs, and fortunately even if a verb is morphed incorrectly, you will probably still be understood.
   - う つ る -> って
   - ぬ ぶ む -> んで
   - く/ぐ -> いて/いで (Note: this is the combined group)
   - す -> して

   There are only two irregular verbs, くる and する. いく, is partly irregular, but not completely.
   - くる -> きて
   - する -> して
   - いく -> いって (+いいて+)
   These are the only exceptions

** て-form connecting two verbs
*** ている
    See: present continuous tense ([[Present continuous]])

*** くれる/あげる
    #+BEGIN_QUOTE
    あそんで くれなかった - (She) didn't play with Alice (didn't play for Alice's benefit).
    #+END_QUOTE
    あそぶ is to play. This has been put into the て-form. 「くれる」 means to 'give downwards' i.e. as Japanese is so polite we place ourselves below others, so someone else is giving us something. 「あげる」 to contrast is to 'give upwards' i.e. to give to someone else. What is being given? In this case the thing being given is what is attached to it via the て form, i.e. 'playing'. Specifically, (she) is not giving the act of playing to Alice. In Japanese we frequently use 'give' for actions, for doing something for our benefit as well as for literally 'giving' nouns. If someone does something for our benefit, we turn that action to the て-form, and attach it to 「くれる」. If we do something for someone else's benefit, we turn that action to the て-form, and attach it to 「あげる」.

** て-form as clause-connector
   #+BEGIN_QUOTE
   おねえちゃんは つまらない 本を よんで いて あそんで くれなかった。
   #+END_QUOTE
   「よむ」 (read) -> 「よんでいる」 (reading) -> 「よんでい​*て*​」 - We have put the 「いる」 into the て-form, why have we done this?
   #+BEGIN_QUOTE
   おねえちゃんは つまらない 本を よんで いる - Big sister is reading an uninteresting book.
   #+END_QUOTE
   This by itself is a complete clause (sentence), by turning the engine of the sentence (いる) into the て form we're saying that something else is going to follow this clause, i.e. 'and'.
   #+BEGIN_QUOTE
   おねえちゃんは つまらない 本を よんで いて - Big sister is reading an uninteresting book and...
   #+END_QUOTE

   Note the ends of the two clauses:
   #+BEGIN_QUOTE
   おねえちゃんは つまらない 本を よんで いて
   #+END_QUOTE
   #+BEGIN_QUOTE
   あそんで くれなかった
   #+END_QUOTE
   For the first clause we do not know what in what tense the action is taking place. In English we would place the tense marker on both clauses, in Japanese we only do this at the end. よんで いて could mean 'is reading' and it could mean 'was reading'. Because くれなかった is in the past tense, then the entire sentence is in the past tense.

** て-form of だ
   See: /copula て-form/ ([[Copula て-form]]).
** て-みる 'try doing'
   #+BEGIN_QUOTE
   まずは、下を 見てみた - First (she) tried looking down
   #+END_QUOTE

   「見てみた」: When we add みる to the て-form of another verb we're saying to 'try' doing something. We're literally saying 'do it and see'. 「食べてみろ」 = Try eating (it) and see. 「やってみろ」 = do and see (give it a try). 「見てみた」 = Take a look and see.

   See also: /Trying to do something with と/ ([[Trying to do something]]).

** て-ある
   <<てある>>
   The て-form of a verb + 「いる」 meaning to be in the state of doing that verb. 「てある」 also means to be in the state of that verb, however there is a difference:

   #+BEGIN_QUOTE
   窓が開いている - The window is open
   #+END_QUOTE
   #+BEGIN_QUOTE
   窓が開けてある - The window is open
   #+END_QUOTE
   What is the difference? 「いる」 simply means is open, however 「ある」 carries another implication. Notice the use of the other-move verb in 「ある」 and the self-move verb in 「いる」. 「開けてある」 therefore signals that the window is open *because* someone opened it.

   Notice how we're using いる, the verb for animate objects to describe the openness of an inanimate object. Because we have used the self-move verb the inanimate object is an honorary 'willed being' with a state of its own. In the example with ある the state has been caused externally, and so the window maintains its inanimateness.

** て-おく
   「ておく」 is in a sense the second half of 「てある」 ([[て-ある]]):
   #+BEGIN_QUOTE
   窓が開けてある - Exist in the state of having been made open
   #+END_QUOTE
   #+BEGIN_QUOTE
   窓を開けてあく - Open the window so that it remains in the state of openness. Establish the window as being in the state of openness
   #+END_QUOTE
   In many cases this is used to mean 'doing something in advance' but it is not the only meaning, as we see here. What is literally means is putting the action in place.

* Negative nouns
    The fundamental basis of negatives is the adjective 「ない」. This adjective means 'non-exist'. The word for exist (for any inanimate thing) is ある. If we want to say that something exists:
    #+BEGIN_QUOTE
    ぺんがある
    #+END_QUOTE
    But if we want to say that something doesn't exist we say:
    #+BEGIN_QUOTE
    ぺんがない
    #+END_QUOTE
    Now, why do we use a verb for being, and an adjective for non-being? This is something that happens all throughout Japanese, when we do something we use a verb, but when we don't do something we attach ない and are therefore using an adjective as the engine of the sentence. This has a very logical reason, when we *do* something, an action is taking place, and so we use a verb, but when we *don't do* it we are describing a state of non-action, so that's an adjective.

    Above we have said 'There is no pen', how do we say 'This is not a pen'?
    #+BEGIN_QUOTE
    これはぺんがある - As for this, it's a pen
    #+END_QUOTE
    #+BEGIN_QUOTE
    これはぺんではない - As for this, as for being a pen, it's not. (Note: で is the て-form of だ)
    #+END_QUOTE

    # TODO Add link to jyanai secrion
* Verbs (transitive and intransitive)
  <<other-move>>
  /Transitive/ and /intransitive/ are better thought of as /Self-move/ and /Other-move/.

  In japanese, a move-word 「動詞」 (どうし) is a word that denotes an action or a movement. So a self-move verb is a verb that moves itself. If I 'stand-up' that's a self-move action. But throwing a ball is an 'other-move' action, one is not throwing themselves, they are throwing a ball. It's as simple as that.

  Japanese has a lot of pairs of words, these could be called forms, or just closely related words, that give the self-move and other-move variations of the verb. For example:
  - 「出る」 (でる) - leave, exit, come out - Self-move
  - 「出す」 (だす) - take out, bring out - Other-move

  Most of the time we can tell which is a self-move word and which is an other-move word by following a few simple rules.

  The first thing to know is that there is a root word for self-move and a root word for other-mode:
  - ある (to be) - Self-move
  - する (to do) - Other-move

  Knowing this there are three laws of move-word pairs.
  1. す and せる (え-stem) ending verbs are other-move
  2. あ-stem + る (aru) ending verbs are self-move
  3. え-stem + る (eru) flip self/other-move either way

  Honorary members of the す family:
  - む -> める is always other-move
  - ぶ -> べる is always other-move
  - つ -> てる is always other-move

  The only wildcards left are:
  - く/ぐ -> ける/げる
  - う ー> える
  - Some る-ending verbs not covered by the first two laws

  Is there anything we can do to simplify this: える version have the opposite of the standard word.

There is a group of verbs in Japanese that are defined by their English translations, but the definition isn't real. These are the 'become' verbs:
- 濡れる - Do (state of) wet (become wet)
- 濁る - Do (state of) cloudy/muddy (become cloudy/muddy)

* Verb stems
   Note: these stems apply to godan verbs. For ichidan verbs just drop the る.

    Every verb ends in one of the う-row kana. Here is the kana-grid (う-row kana that aren't used as verb endings have been removed), presented on its side.
    | あ | い | *う* | え | お |
    | か | き | *く* | け | こ |
    | さ | し | *す* | せ | そ |
    | た | ち | *つ* | て | と |
    | な | に | *ぬ* | ね | の |
    | ば | び | *ぶ* | べ | ぼ |
    | ま | み | *む* | め | も |
    | ら | り | *る* | れ | ろ |
    As we can see there are four other ways in which the verb could end. These are the verb stems. For now we're only looking at the あ-stem as this is the one we need for the negative.

    To form the あ-stem we simply shift the final kana from the う-row to the あ-row. There is one only exception and this is the only exception in the entire stem system. This exception is that う itself does not become あ but わ. This is because, take for example a verb like 「かう」, 「かあ」 would not be as easy to say as 「かわ」. Every other う-row kana is simply changed to its あ-row equivalent.
    | **わ** | い | *う* | え | お |
    | *か*   | き | *く* | け | こ |
    | *さ*   | し | *す* | せ | そ |
    | *た*   | ち | *つ* | て | と |
    | *な*   | に | *ぬ* | ね | の |
    | *ば*   | び | *ぶ* | べ | ぼ |
    | *ま*   | み | *む* | め | も |
    | *ら*   | り | *る* | れ | ろ |

** い-stem
   The い-stem of a verb is what we might call the 'pure-stem' of a verb. In Japanese this is called 「連用形」(れんようけい) which means 'connective-use form'.

   #+BEGIN_QUOTE
   そのとき、白い ウサギが とおり すぎた。 - At that moment a white rabbit passed by
   #+END_QUOTE
   「とおりすぎる」 is attaching the い-stem of one verb 「とおる」 - 'pass through', to another verb 「すぎる」 - 'exceed'/'go beyond' to give it extra meaning. We will see this a lot throughout Japanese. Connecting とおる and すぎる, 'pass through' and 'go beyond' means 'passing by'.

   #+BEGIN_QUOTE
   はしり だした - Run + Take out = Broke into a run (started to run).
   #+END_QUOTE
    In this sense だした means modifies the verb to mean the action 'erupted'.

    #+BEGIN_QUOTE
    でも ウサギは ピョンピョンと はしりつづけた。 - But as for the rabbit, (it) kept on running in a /pyonpyon/ manner
    #+END_QUOTE
    「はしりつづけた」 = 「はしる」 + 「つづける」 = Continued running (running continued).

    See also /い-stem + そう/ ([[い-stem + そう]])

* Negative verbs
   To make a verb negative we must attach 「ない」 to the あ-stem of the verb ([[*Verb stems]]).
   #+BEGIN_QUOTE
   かう ー> かわない
   #+END_QUOTE
   #+BEGIN_QUOTE
   はなす ー> はなさない
   #+END_QUOTE

   Remember for ichidan verbs we don't need to form a stem and just drop the る:
   #+BEGIN_QUOTE
   たべる ー> たべない
   #+END_QUOTE

* Adjectives
   Japanese adjectives are not the same as English adjectives. As we have learned Japanese sentences come in three kinds, depending on the type of engine they have. All three of these engines can be used like adjectives.
   - Verb ([[*Verb-adjectives]]) - A *does* B
   - だ-marked noun ([[*Noun-adjectives]]) - A *is* B
   - い-"Adjective" ([[*い-adjectives]]) - A *is* B

** い-adjectives
  Let's start with the first one, the one we refer to as an adjective in English, the い-engine:
  #+BEGIN_QUOTE
  ぺんがあかい - Pen is red
  #+END_QUOTE
  An important note, 「あかい」 does not mean 'red', it means 'is red'. 「あか」 means red.

  If we swap the order of 「ぺんが」 and 「あかい」 then we can take this い-engine, and now use it not as the primary engine, but as a secondary engine. This would not be a complete sentence however without a new engine, for example, a new (primary) い engine.
  #+BEGIN_QUOTE
  あかいぺんがちいさい - Red pen is small
  #+END_QUOTE

  With a true adjective we also use the て-form ([[て-form]]) of the adjective
  #+BEGIN_QUOTE
  さくらが美しくてやさしい - Sakura is beautiful and kind
  #+END_QUOTE

** Verb-adjectives
   Any verb in any tense can be used like an adjective:
   #+BEGIN_QUOTE
   しょうじょがうたった - Girl sang
   #+END_QUOTE
   #+BEGIN_QUOTE
   うたったしょうじょが... - The girl who sang... (Note: this sentence is not yet complete, it lacks a primary engine).
   #+END_QUOTE
   #+BEGIN_QUOTE
   うたったしょうじょがねている - The girl who sang is sleeping
   #+END_QUOTE

   #+BEGIN_QUOTE
   ある 日 アリスは 川の そばに いた。- On a certain day, alice was beside a river.
   #+END_QUOTE
   ある means 'exists' (of inanimate things) or, more accurately in English: 'a certain'. ある日 therefore means 'on a certain day'. Note also that this is the same as how we use might use Today, Yesterday, Tomorrow etc. but not how we might use 'On Saturday' ([[*Time expressions]]).

   Verbal adjectives can create very complex sentences in which we can use entire other-sentences (clauses) in an adjectival manner.
   #+BEGIN_QUOTE
   しゃべる ウサギを 見た ことが ない。
   #+END_QUOTE
   Here 「しゃべる」 is being used as an adjective just as any verb can be. 「しゃべるウサギ」 - Talkative/talking rabbit. 「見た」 is the past tense of 「見る」 to see. It is modifying 「こと」, an abstract thing, meaning 'The fact of having seen'. 「見たことがない」 means 'The fact of having seen doesn't exist'. The talking rabbit is the object of the engine of the sentence, 'The fact of having seen'. So: 'The fact of having seen a talking rabbit doesn't exist' -> (Alice) had never seen a talking rabbit. This is another example of the un-egocentric ([[Egocentrism]]) nature of Japanese; Alice is not the actor of this sentence, it is the 'thing' that does not exist.

** Noun-adjectives
  <<な-adjectives>>
  #+BEGIN_QUOTE
  いぬがやんちゃだ - The dog is naughty
  #+END_QUOTE
  We can turn 「やんちゃ」 into an adjective too, but there is one important thing to note. Just as we have to add だ to a noun to use it as an engine, here we must add な to the noun to use it as an adjective. な is in fact the connective form of だ. Don't be fooled by so-called 'な-adjectives', they're simply nouns! /Adjectival/ nouns.
  #+BEGIN_QUOTE
  やんちゃ​*な*​いぬが... - The dog who is naughty... (Note: this sentence is not yet complete, it lacks a primary engine).
  #+END_QUOTE
  #+BEGIN_QUOTE
  やんちゃ​*な*​いぬがねている - The dog who is naughty is sleeping
  #+END_QUOTE

  An important note is that we cannot do this with /all/ nouns, only nouns which are frequently used in an adjectival way. This group of nouns is what are referred to as 'な-adjectives'. We can use all nouns as adjectives, but for the rest we need to use a different technique, /の-adjectives/ ([[の-adjectives]]).
  # TODO use org's duplication function here for の-adjectives

** なる & たる 'adjectives'
   #+BEGIN_QUOTE
   華麗なる探偵 - Magnificent detectives
   #+END_QUOTE
   「華麗」 is an adjectival noun so it could've been used with な, but the author has chosen to use 「なる」 instead. 「なる」 is not the same 「なる」 that means 'become', it is a contraction of 「のある」.
   # TODO: Watch が particle become の video
   #+BEGIN_QUOTE
   華麗がある探偵 -> 華麗のある探偵 -> 華麗なる探偵 - Detectives possessing magnificence lit: Magnificence exists detectives
   #+END_QUOTE
   What does the choice of 「なる」 over な actually mean? In modern texts the only reason to choose 「なる」 over な is just that it sounds a bit more old-fashioned or a bit more literary.

   「たる」 is a contraction of 「とある」, meaning that the 「ある」 is belonging to the thing that is being described, rather than the thing describing it.
   #+BEGIN_QUOTE
   らんらんたる目 - Blazing eyes
   #+END_QUOTE
   The subtle difference is that 「なる」 means 'is magnificent', whereas 「たる」 means 'in a blazing manner'.

* Adjective stem, adjective て-form, negative adjectives
  <<Negative adjectives>>
  The adjective stem is simple, just drop the い and add く. This is how we make the て form, 「あかい」 ー> 「あかくて」, and it's also the way we make the negative, 「あかい」 ー> 「あかくない」.

  # Add link here
  The only exception (besides ます) is いい (is good), which has an older form, which is still widely used in よい. When we morph いい it becomes よい again:
  #+BEGIN_QUOTE
  いい ー> よくない - Not-good
  #+END_QUOTE
  #+BEGIN_QUOTE
  いい ー> よかった - Was-good
  #+END_QUOTE
  Note: 「よかった」 is a common phrase: 「∅がよかった」 - /It was good (That went well, it turned out great etc.)/

  # TODO: Rename this section to adjectives as nouns?
  <<Becoming an adjective>>
  If we want to say 'Sakura became beautiful' we can't use に because 「うつくしい」 isn't a noun ([[*Logical particles]]), it's an engine. To use 「うつくしい」 as a noun we must convert it to its stem 「うつくしく」.
  #+BEGIN_QUOTE
  さくらがうつくしくなった - Sakura became beautiful
  #+END_QUOTE

* Adverbs
  #+BEGIN_QUOTE
  ウサギは 早く 走る
  #+END_QUOTE
  「早い」 is an adjective. If we want to say the rabbit is fast we simply say 「ウサギが早い」. But if we want to say that the rabbit's *movement* is fast we must use an adverb. In Japanese we can turn any adjective into an adverb by simply removing the い and replacing it with く. 「早い」 -> 「早く」.

  # TODO stuff about に

  Adverbial nouns can make に or と disappear when used as an adverb. Often (but not always) these nouns end in り.

  As we know, any noun that can be used adverbially can be done so using the particle に. 「しずかにする」 - Act quietly. With an adverbial noun we don't need the に:
  #+BEGIN_QUOTE
  ゆっくりにする - Act leisurely
  #+END_QUOTE
  #+BEGIN_QUOTE
  ゆっくりする - Act leisurely
  #+END_QUOTE

  「あまり」 is a noun that means 'excess'. We can use it in a literal sense: 「ごはんのあまり」 - The excess rice.
  #+BEGIN_QUOTE
  悲しみのあまりに泣いた - From sadness's excess, cried
  #+END_QUOTE
  #+BEGIN_QUOTE
  悲しみのあまり泣いた - From sadness's excess, cried
  #+END_QUOTE
  #+BEGIN_QUOTE
  あまり勉強しない - lit: (I) don't study too much. read: (I) don't study /very/ much
  #+END_QUOTE
  Note: This under-exaggeration is another case of hyperbole (or rather inverse-hyperbole).

  「ずいぶん」 means 'sufficiently'. In English 'sufficiently' isn't a noun, but in Japanese it is. Like 「あまり」 is often used with some inverse-hyperbole i.e. sufficiently = more than sufficient.
* Helper adjectives
** ない - Negative
   See: /negative nouns/ ([[*Negative nouns]]), /negative verbs/ ([[*Negative verbs]]) and /negative adjectives/ ([[Negative adjectives]]).
** たい - Desire (to do something)
   :PROPERTIES:
   :Keywords: want, desire
   :END:
   For desire to have something see 「ほしい」 ([[ほしい]]).
   Remember: 「たい」 can only be used with respect to ourselves ([[がる]]).

   To express that we want to do something, we must add the /helper adjective/ 「たい」 to the い-stem of the verb ([[*Verb stems]]). 「たい」 doesn't mean 'want' in the English sense, it can't, again, because 'want' is a *verb*, and 「たい」 is an *adjective*.
   #+BEGIN_QUOTE
   (わたしは)クレープガたべたい
   #+END_QUOTE
   The common English translation for this is 'I want to eat crepes', but as the pattern is just the same as with 「ほじい」 ([[ほしい]]), the desire-ability of the crepes is not a verb, it is an adjective.

   There is no truly good translation of this into English. We shouldn't be thinking in terms of 'awkward English' or 'natural English' when it comes to constructing and understanding these sentences. We should be thinking in terms of Japanese.

   What if we took this sentence, 「わたしはクレープガたべたい and removed the optional parts so that we just had 「たべたい」? In this case, the meaning of the sentence would be what the common English translation is. ∅ defaults to 'I', and so the translation is 'I eat-wanting am' -> 'I am wanting to eat' -> 'I want to eat'. Because there is no eat-inducing subject here, the want to eat is attributed directly to I.

   # TODO Reference this section from elsewhere
   So what is 「たい」? Is it an adjective describing the /condition of something/ making you want to do something, or is it an adjective describing /my desire/? Well, it can be either. This is very common throughout Japanese. 「こわい」 can mean scared or scary:
   #+BEGIN_QUOTE
   おばけがこわい - Ghosts are scary
   #+END_QUOTE
   #+BEGIN_QUOTE
   ∅がこわい - I am scared
   #+END_QUOTE
   This isn't confusing because が tells us what to do.

   We cannot use these adjectives of desire (or any emotion) about anyone other than ourselves. If we say 「たべたい」 and there is no context to give the subject, then we must be talking about ourselves, and never the person we are speaking to or anyone else. Japanese simply doesn't allow us to use 「たい」 or 「こわい」 or 「ほしい」 or anything else about anyone other than ourselves ([[がる]]).

** らしい - Subjective impression (seems)
   <<らしい>>
   # TODO Move this chunk somewhere a little more relevant
   らしい is a /helper adjective/. Adjectives that end in しい we can consider a sub-class of adjectives that on the whole express subjectivities. That is to say, they are adjectives not describing an inherent property of something, but a (possible) human perspective on it:
   - かなしい - Sad
   - うれしい - Happy
   - むずかしい - Difficult
   - やさしい - Easy

   Like 「そう」 ([[そう]]), 「らしい」 can be attached either to an individual word or to a complete logical clause/sentence. We don't need to change anything about the word, just attach 「らしい」 to it. As with 「そう」, if we attach 「らしい」 to a single word, we are talking about our (subjective) impression of that action or state.

   And again as with 「そう」, if we attach 「らしい」 to a sentence we're indicating that the statement itself is subjective, i.e. a deduction/hearsay/conjecture.

   There is a difference however:
   #+BEGIN_QUOTE
   あの動物はウサギだ*そうだ* - I heard that animal is a rabbit
   #+END_QUOTE
   #+BEGIN_QUOTE
   あの動物はウサギだ*らしい* - It seems that animal is a rabbit
   #+END_QUOTE
   These two /can/ mean the same thing, but not always. 「そう」 is specific to 'I heard', whereas 「らしい」 means that from the available evidence, which /could/ be what somebody said, or could be something else, it /seems/ to be a rabbit.

   When it comes to the difference between 「そう」 and 「らしい」 with respect to a single word, the main difference is that we can't apply 「そうだ」 to a regular noun. We can only apply it to an adjectival noun. 「らしい」 can be applied to any noun, adjectival or otherwise.

   「らしい」 has the ability to liken one thing to another:
   #+BEGIN_QUOTE
   あの動物はウサギだ*らしい* - That animal is rabbit like
   #+END_QUOTE
   らしい is not-necessarily conjecturing that something is something else, we may merely be saying that it is like that thing.
   #+BEGIN_QUOTE
   男らしい男 - Manly man
   #+END_QUOTE
   #+BEGIN_QUOTE
   さくら先生は先生らしくない - Sakura-sensei is not like (does not have the qualities of) a teacher
   #+END_QUOTE
   #+BEGIN_QUOTE
   それはさくらしくない - That wasn't like (you) Sakura
   #+END_QUOTE

** っぽい - らしい (more casual)
   #+BEGIN_QUOTE
   こどもっぽい - Childish
   #+END_QUOTE
   「っぽい」 works very much like 「らしい」 ([[らしい]]) and is also a /helper adjective/ but is much more casual than 「らしい」.

   「っぽい」 cannot be used on the end of a completed clause, it can only be attached to a word.

   「らしい」 tends to imply that the quality is something that the thing ought to have, 「っぽい 」 often tends to imply the opposite. This is not an absolute rule, just a tendency.
   #+BEGIN_QUOTE
   こどもらしい - Childlike
   #+END_QUOTE
   #+BEGIN_QUOTE
   こどもっぽい - Childish
   #+END_QUOTE

* Helper verbs
** がる - Seems/appears
   <<がる>>
   Because Japanese is such a logical language it doesn't allow us to say something that we cannot know for sure. One thing that we cannot know for sure is someone's inner feelings. We might think that Sakura wants to eat cake, but we can't know for sure. So if I want to talk about her desire to eat cake, we can't just use 「たい」. We need to add to 「たい」 (or 「こわい」, or 「ほしい」 or anything else) the helper verb がる.

   To do this we take the い off of the adjective and add the helper verb 「がる」.
   - たがる
   - こわかる
   - ほしがる

   「がる」 means 'to show signs of', 'to look as if it's the case'.
    #+BEGIN_QUOTE
    さくらがケーキをほしがる - Sakura is showing signs of wanting cake
    #+END_QUOTE
    Even if Sakura has actually told me she wants cake, we must still use 「がる」. All I know is what she's said, I still don't know her feelings absolutely.

    Why do we use a verb for other people and an adjective for ourselves? I can't describe someone-else's feelings because I don't know about them, I can only describe their actions, and their actions are a verb.

    See also: /そう/ ([[そう]])

** る/られる - Potential (Able to do)
   :PROPERTIES:
   :Keywords: can, able
   :END:
   The potential helper verb has two forms, for godan verbs 「る」, and for ichidan verbs 「られる」.

   The potential helper-verb which attaches to the え-stem of a verb ([[*Verb stems]]):
   | あ | い | *う* | *え* | お |
   | か | き | *く* | *け* | こ |
   | さ | し | *す* | *せ* | そ |
   | た | ち | *つ* | *て* | と |
   | な | に | *ぬ* | *ね* | の |
   | ば | び | *ぶ* | *べ* | ぼ |
   | ま | み | *む* | *め* | も |
   | ら | り | *る* | *れ* | ろ |

   There are only two exceptions, 「くる」 and 「する」.
   #+BEGIN_QUOTE
   くる -> こられる
   #+END_QUOTE
   #+BEGIN_QUOTE
   する ー> できる
   #+END_QUOTE

   #+BEGIN_QUOTE
   わたしは(optional)ほんがよめる - As for me, the book is readable
   #+END_QUOTE
   A common translation of this would be 'I can read the book', however again the が is on the book, not on I. If we wanted to say 'I can read the book', the book would need to be marked by を as it is the target of our reading, and 'I' would have to be marked by が as I is the actor.
   #+BEGIN_QUOTE
   わたしがほんをよめる - I can read the book
   #+END_QUOTE
   This is perfectly fine, but it's not what is usually done. Remember, Japanese is not /ego-centric/.

   As we're using a helper-verb, the past, non-past, negative-past and negative-non-past conjugation rules are the same as regular verbs, for 「あるける」 (can walk):
   - あるける - non-past - can walk
   - あるけた - past - could walk
   - あるけない - negative-non-past - can't walk
   - あるけなっかた - negative-past - couldn't walk

** れる/られる - Receptive (passive)
   The real name for the 'passive conjugation' is the /Receptive helper verb/. The receptive helper verb is 「れる」 for godan verbs and 「られる」 for ichidan verbs, and attaches to the あ-stem of another verb ([[*Verb stems]]).
   | *あ* | い | *う* | え | お |
   | *か* | き | *く* | け | こ |
   | *さ* | し | *す* | せ | そ |
   | *た* | ち | *つ* | て | と |
   | *な* | に | *ぬ* | ね | の |
   | *ば* | び | *ぶ* | べ | ぼ |
   | *ま* | み | *む* | め | も |
   | *ら* | り | *る* | れ | ろ |
   Remember! う becomes わ, not あ.

   The receptive helper verb means /receive/ or /get/, we're receiving/getting the action that the helper verb is attached to
   #+BEGIN_QUOTE
   さくらがしかられた - Sakura scolded-got - Sakura got scolded/Sakura received a scolding
   #+END_QUOTE

   Note, the receptive helper verb and the modified verb have different actors. The sentence is not Sakura scolds, someone else (we don't know who) is scolding Sakura, but Sakura is the one in the act of receiving the scolding. This is not the same with all helper verbs.

   The receiver is not always a person:
   #+BEGIN_QUOTE
   水がのまれた - Water got drunk
   #+END_QUOTE
   Even if we add a doer of the drinking, the water is still the actor of the sentence.
   #+BEGIN_QUOTE
   水がいぬにのまれた - Water got drunk by (a) dog
   #+END_QUOTE
   Why is the dog being marked by に? Let's look at a larger sentence:
   #+BEGIN_QUOTE
   さくらは だれかに かばんが ぬす*ま* れた - As for Sakura, someone-by bag stolen-got - As for Sakura, (her) bag got stolen by someone
   #+END_QUOTE
   Who is the actor? It's not Sakura, she's marked by は. It's not the 'someone' as they're marked by に. The bag is the actor of the sentence, the bag /did/ 'got'.

   What is に doing here? に marks the ultimate target of an action. So what is the target of getting stolen? To whom is the stolen item going? It is the 'someone' who stole it.

   # TODO Investigate the nuisance receptive (lesson 13) for further notes
   #+BEGIN_QUOTE
   さくらが だれかに かばんを ぬすまれた
   #+END_QUOTE
   Here the core of the sentence is now 'Sakura got'. What did she get? She got the unfortunate nuisance action of だれかに かばんを ぬすむ, someone stealing (her) bag. /Sakura got her bag stolen by someone/ *not* /Sakura's bag got stolen by someone/.

** せる/させる - Causative
    <<causative>>
   The /causative helper verb/ indicates that we are causing someone to do the verb to which is is attached. The causative helper verb is 「せる」 for Godan verbs and attaches to the あ-stem of a verb ([[*Verb stems]]):
   | *わ* | い | *う* | え | お |
   | *か* | き | *く* | け | こ |
   | *さ* | し | *す* | せ | そ |
   | *た* | ち | *つ* | て | と |
   | *な* | に | *ぬ* | ね | の |
   | *ば* | び | *ぶ* | べ | ぼ |
   | *ま* | み | *む* | め | も |
   | *ら* | り | *る* | れ | ろ |

   For ichidan verbs 「させる」.

   #+BEGIN_QUOTE
   ∅が 犬を 食べ させた - I caused the dog to eat (causative)
   #+END_QUOTE
   - Core action: verb 「させる」 (cause), actor ∅ (I)
   - Secondary action: verb 「たべる」 (eat), actor 「犬」 (dog)
   - Implicit sub-clause: 「犬が 食べた」

   「せる」/「させる」 can mean to /compel/make/force/, or it can mean to /allow/. But it can also mean neither of those. The best way to translate it is with the rather non-native sounding 'cause'. 'I caused the dog to eat' doesn't mean 'I forced the dog to eat', it just means that I did something that had the result of the dog eating, whether that be intentional, accidental, or forceful.

   Sometimes the person or thing we are causing to do something can be marked by を and sometimes it can be marked by に. Remember the particles are always consistent. If we are forcing someone to do something, then we're treating them like an object (を), if we're treating them as a target, then this is more mutual and goes with /allowing/ over /compelling/ and so に.

   That said the use of を and に is not the main indicator of if we mean allowing or compelling. There is no precise English analogy with the causative helper verb, so trying to determine if it means exactly cause or exactly allow is misguided, remember, it can mean neither. It's sort of a sliding scale between the two, more subtle. Beyond that, when the action that is being compelled has itself an を marked object we can see that in the sub(ordinate) sentence the meat is the object of the dog's action, and the dog is the thing that is being caused to do the action:
   #+BEGIN_QUOTE
   ∅が犬に にくを 食べ させた - I caused the dog to eat meat
   #+END_QUOTE
   - Core action: verb 「させる」 (cause), actor ∅ (I)
   - Secondary action: verb 「たべる」 (eat), actor 犬 (dog)
   - Implicit sub-clause: 「犬が にくを 食べた」

   に expresses relation to core clause. を expresses relation to sub clause.

   In these types of sentences Japanese does not allow us to use the を particle twice. If we could use を twice then in some sentences we might end up with some doubt as to which を marks the object associated with 「食べる」 and which を marks the object associated with 「せる」/「させる」.


** Causative receptive
   Causative-receptive (what most call the causative passive) means to get made to do. Remembering that helper verbs are ichidan verbs, to add the receptive helper verb to the causative helper verb we simple remove the る and add 「られる」:
   - せる/させる - る + られる = せられる/させられる

   We now have three verbs in a sentence:
   #+BEGIN_QUOTE
   わたしは ∅が ブロコリを 食べ(1) させ^2 られた^2 - I got^3 compelled^2 to eat^1 broccoli
   #+END_QUOTE
   - Core action: verb 「られる」 (get), actor ∅ (I)
   - Secondary action: verb 「させる」 (compel), actor unspecified
   - Tertiary action: verb 「食べる」 (eat), actor ∅ (I)

   Note: The first and third actor are always the same. The second actor always different.
** ます - Polite
   See /です/ます form/ ([[Polite]])
** う/よう - Volitional
   The volitional form is one of the few uses of the お-stem. The godan volitional helper is just う, attached to the お stem it simply lengths the お sound. The ichidan form is to as usual remove the る, and add よう.

   The volitional form of 「ます」 and 「です」 are 「ましょう」 and 「でしょう」.

   | あ | い | *う* | え | *お* |
   | か | き | *く* | け | *こ* |
   | さ | し | *す* | せ | *そ* |
   | た | ち | *つ* | て | *と* |
   | な | に | *ぬ* | ね | *の* |
   | ば | び | *ぶ* | べ | *ぼ* |
   | ま | み | *む* | め | *も* |
   | ら | り | *る* | れ | *ろ* |

   Volition means will, the volitional form expresses or invokes the will of the speaker. The most usual use of it is setting the will of a group of people in a particular direction.
   #+BEGIN_QUOTE
   いきましょう - Let's go.
   #+END_QUOTE

   There are many uses of the volitional form in combination with various particles but they will be covered in due time. One of note for now is the volitional copula 「だろう」/「でしょう」 which when added to any ordinary sentence adds the extra meaning of /probably/, i.e. it adds doubt/conjecture.
   #+BEGIN_QUOTE
   赤いでしょう - Probably red
   #+END_QUOTE
   #+BEGIN_QUOTE
   さくらがくるでしょう - Sakura's probably coming.
   #+END_QUOTE

* です/ます form
  <<Polite>>
  # TODO Add the bit from notes 'the only exceptions'
  「ます」 is a (helper) verb that attaches to the い-stem  ([[*Verb stems]]) of another verb. It doesn't change the meaning of the verb in anyway, it just makes it formal. 「ます」 is highly irregular:
  - The past tense is normal, it ends just like any す verb - 「ました」
  - The negative is not 「ませない」, it is 「ません」 - This is the only verb that does this in modern Japanese
  - The negative past is 「ませんでした」

  「です」 is the formal version of だ and works exactly the same aside from one quirk, unlike with だ which we do not attach to adjectives, we do attach 「です」 in formal speech. It doesn't mean or do anything, but it's done all the same.

  A useful note, we can use ません and ないです interchangeably:
  - 「さくらが話しません」
  - 「さくらが話しないです」

* TODO Adjectival nouns
  # This all needs compiling
#+BEGIN_QUOTE
穴の 中は たて穴 だった。 アリスは すぐ下に 落さた。- The inside of the hole was a vertical hole. Alice fell straight (directly) down the hole.
#+END_QUOTE

#+BEGIN_QUOTE
でも、 おどろいたことに ゆっくり ゆっくり 落さた。 - But, the surprising thing was that she slowly slowly fell/ But, surprisingly she fell slowly.
#+END_QUOTE
- おどろいたこと doesn't mean 'A surprised thing', it means 'the surprising thing' (surprisingly). The に attached is again to turn it into an adverb. So: 'She fell surprisingly'. Of course, it isn't surprising that she fell, but it is surprising that she fell ゆっくり ゆっくり (slowly slowly).
- ゆっくり is slightly unusual in that it is fundamentally a noun, but we can use it as an adjective without adding に to it. We will see ゆっくり very often.

* こ/そ/あ/ど directional words
  <<kosoado>>
  こ, そ, あ, ど words in their most basic sense simply mark physical locations, but expand to have more subtle and metaphorical uses. This is common because all languages use physical metaphors to express abstract concepts.

  The most basic meaning:
  | ここ           | そこ                              | あそこ     | どこ   |
  | Here (near me) | There (near you/a little way off) | Over there | Where? |
  Often ここ means the speaker's place and そこ means the listener's place, and あそこ means away from both the speaker and the listener

** れ-group (nouns)
   The れ group act as nouns.

   | これ | それ | あそれ             | どれ         |
   | This | That | That (other there) | Which thing? |
   These can get confused with the の-group as in English we use the same word for both of these types of words.

   れ means a being, it refers to a thing.
   #+BEGIN_QUOTE
   これは [∅が] ペンだ - As for here-thing (it) pen-is - The thing here is a pen
   #+END_QUOTE

** の-group (adjectivals)
   The の group act as adjectives.

   | この                 | その                  | あその                       | どの           |
   | This-something       | That-something        | That-something (other there) |                |
   | described as near me | described as near you | described as over there      | how-described? |

   の is used to make adjectivals and descriptors:
   #+BEGIN_QUOTE
   この ペンは [∅が] 赤い - Here's pen as for (it) red-is - The pen that is here is red
   #+END_QUOTE

** な-group (real adjectives)
   The な-group act as real adjectives

   | こな      | そな      | あそな    | どな       |
   | Like this | Like that | Like that | Like what? |

   The な used for adjectival nouns descriptive of a thing's qualities. Distance is often conceptual, not physical i.e. How far the thing is from what we're talking about or the present-circumstance.
   #+BEGIN_QUOTE
   こんあ食べ物 - Food like this
   #+END_QUOTE
   #+BEGIN_QUOTE
   そんあことがひどい - A thing like that is cruel
   #+END_QUOTE

   These are essentially comparing-adjectives. Saying that something is like something either in physical space or in a conceptual way.

** う/あ-group
   Lengthening the final sound of こ/そ/あ/ど is talking about the way something is/happens.

   #+BEGIN_QUOTE
   [∅が]そうです - It (the fact/situation) is that way = That's right
   #+END_QUOTE
   #+BEGIN_QUOTE
   そうせる - Do like that
   #+END_QUOTE
   #+BEGIN_QUOTE
   こうせる - Do like this
   #+END_QUOTE
   #+BEGIN_QUOTE
   どうせる - Do it like how?
   #+END_QUOTE

   #+BEGIN_QUOTE
   どうすればいい - In what way if I act will be good?
   #+END_QUOTE
   # TODO add this link
   Note: すれば is the conditional form of する ([[*Conditionals]])

   #+BEGIN_QUOTE
   そういうこと - That way say matter (condition/thing) - Thus-described matter - That kind of thing
   #+END_QUOTE
   #+BEGIN_QUOTE
   どういうこと - What way said matter (condition/thing) - What is going on here?
   #+END_QUOTE
   The 「いう」 here is not referring to the fact we've said anything. The いう refers to the description of the thing.
* かもしれない - Perhaps
  #+BEGIN_QUOTE
  かもしれません - Perhaps
  #+END_QUOTE
  - か - Makes a question of whatever came before
  - も - Even/As much as
  - 知れ - Potential form of know
  - ない/ません - Can't know (don't have the potential to know)
  #+BEGIN_QUOTE
  かもしれません - As to whether that is true or not I can can't go as far as to know
  #+END_QUOTE
* TODO だから
   #+BEGIN_QUOTE
   (...)だから - From that (what you/I just said) - Therefore; as above.
   #+END_QUOTE

* そう - Likeness and Hearsay
  <<そう>>
** そう for likeness
  「そう」 is a /helper noun/ that can mean either 'likeness', or 'hearsay'.

  「そう」 is the same 「そう」 as in the こう/そう/ああ/どう group we ([[kosoado]]). 「そう」 can be used with any of the three engines: verbs, adjectives or だ-marked nouns. Simply remove the final kana and add 「そう」 for 'seems like' meaning. In the case of だ the engine must be an adjectival noun (な-adjective) ([[な-adjectives]]). Remember that each of the three engines can be moved behind other cars to turn them into adjectives ([[*Adjectives]]).

  Once そう has been attached to an engine, the engine becomes a new adjectival noun.
  #+BEGIN_QUOTE
  元気だ -> 元気そう - Is healthy -> Seems healthy
  #+END_QUOTE
  #+BEGIN_QUOTE
  元気な学生 -> 元気そう学生 - Healthy student -> Healthy looking student
  #+END_QUOTE
  #+BEGIN_QUOTE
  おもしろい -> おもしろそうだ - Is interesting -> Seems interesting
  #+END_QUOTE
  Note: Logically だ must always be used with 「そう」, but colloquially it is often left off.

  Remember, in Japanese we can only say things that we actually know for ourselves ([[がる]]), so unless we have read/tasted/experienced/whatever that thing which the other person is describing, we must say 「そう」 as we cannot *know* that is is the way that they say.

  <<い-stem + そう>>
  For verbs, in the case of ichidan we just remove る as usual, and in the case of godan we use the い-stem ([[*Verb stems]]) of the verb.
  #+BEGIN_QUOTE
  泣きそうだ - Seems about to cry
  #+END_QUOTE
  Note: Again; logically だ must always be used with そう, but colloquially it is often left off.

** Hearsay
  The 「そう」 used for likeness is a /suffix/, it is joined to other words in order to form a new word. Whatever the word was to start with, once 「そう」 is attached, it becomes an adjectival noun. This is not what happens with hearsay.

  When talking about hearsay we use 「そうだ」/「そうです」 after the entire, complete sentence. Back to the train metaphor, the entire logical sentence becomes the main car at the core of a new sentence being pulled by a だ-engine.

  #+BEGIN_QUOTE
  さくらが日本人だ -> さくらが日本人だそうだ - Sakura is Japanese -> Sakura is Japanese I hear
  #+END_QUOTE
  So simply put 「そうだ」 at the end of any full statement.

* ようだ、 ように and みたい - Metaphors and similes
  「ようだ」 forms the far end of a sliding scale of 'likeness' expressions:
  | Objectivity        |                                | Subjectivity    |
  | そうだ             | らしい ([[らしい]])            | ようだ + みたい |
  | Hearsay/conjecture | Observation/quality comparison | Pure simile     |

  Each of these expressions can be placed at the end of a complete logical sentence to express that the sentence is either something we've heard or some conjecture from the information available:
  - そうだ - Conjecture of what the quality of something is: 「おいしいそうだ」 - It looks delicious
  - らしい - Has a much greater degree of subjectivity. 「らしい」 overlaps with 「そうだ」 in many respects but it can also do things that 「そうだ」 cannot. 「らしい」 can compare things to other things that we know they aren't: 「ウサギらしい」 - Rabbit-like (even though we know it isn't a rabbit). 「こどもらしい」 - Childlike (whether they are a child or not)
  - ようだ - 「ようだ」 can be much more subjective still, going as far as a /metaphor/ or /simile/

  <<ようだ>>
  #+BEGIN_QUOTE
  山のようだ - Like a mountain
  #+END_QUOTE
  #+BEGIN_QUOTE
  風のように走る - Runs like the wind
  #+END_QUOTE

  Often when 「ようだ」 is being used as a metaphor/simile it is used alongside 「まるで」 meaning 'roundly' or 'wholly'
  #+BEGIN_QUOTE
  まるで風のように走た - Wholly like the wind ran
  #+END_QUOTE
  Note that this is hyperbole. Hyperbole in this fashion is common in many languages. In English: 'I /literally/ froze to death'. We really mean: 'I /figuratively/ froze to death'; The hyperbole is to give emphasis.

  We *cannot* use 「まるで」 with 「そうだ」 and we *shouldn't* use it with 「らしい」.
  - のよう*だ* - Clause-end adjectival
  - のよう*な* - Pre-noun adjectival
  - のよう*に* - Adverb ([[*Adverbs]])

  「ようだ」 has a special usage that the other likening phrases don't have. As with the other two we can attach it to the end of a sentence with the meaning of 'seems/appears'. We can also attach it to a complete sentence for another purpose. We can use 「ようだ」 to turn an entire sentence into a simile:
  #+BEGIN_QUOTE
  まるで^{1}ゆうれいを見た^{2}か^{3}のような^{4}顔をした^{5} - Did (had) a face^{5} exactly^{1} as^{4} if^{3} (she) saw a ghost^{2} - She made a face exactly as if she'd seen a ghost
  #+END_QUOTE
  # TODO Add a link here for the potentials (not potential form the か and stuff)
  Note that [2] is an entire sentence being used as a simile for (her) face. We start with 「まるで」 indicating that we are going to use a simile. Then we make our completed statement. か turns our statement into a question, it gives us our 'if', she hasn't actually seen a ghost, it's a potentiality, so it's an 'if'. 「のように」 takes this and turns it into a simile 'as' i.e. 'as strong as...', 'as if...'. Finally we are describing her face we use the な connective form.

  Using か in this way is something we can't do this with any of the other likening phrases. Even 「みたい」 which can do most of the things that 「のよう」 can do, can't do this.

  「みたい」 is the less formal cousin of 「よう」 and means 'looks like...', 'looks' not necessarily referring to solely literal vision:
  #+BEGIN_QUOTE
  山みたいだ - Like a mount
  #+END_QUOTE
  #+BEGIN_QUOTE
  山みたいな人 - A mountain-like person
  #+END_QUOTE
  #+BEGIN_QUOTE
  風みたいに走る - Runs like the wind
  #+END_QUOTE
  「みたい」 can also make true similes using 「まるで」 just like 「ように」. The main things to remember about 「みたい」 vs. 「ようだ」 is that 「みたい」 is less formal, and that we *can't* use it with a completed sentence. We *can* use it with a complete sentence for /conjecture/, but not to create a simile.

  Because 「みたい」 is so casual, often the だ or 「です」 gets left off the sentence.

* ようになる, ようにする, ことになる, ことにする
  <<ようになる>>
  When we use a noun followed by 「になる」 we mean that something turns into that noun:
  #+BEGIN_QUOTE
  さくらは∅がかえるになった - Sakura became a from
  #+END_QUOTE

  「よう」 indicates a likeness to something ([[ようだ]]):
  #+BEGIN_QUOTE
  山のようだ - Like a mountain
  #+END_QUOTE

  When we use 「ようになる」 and the other phrases we don't add them to a noun, but to a complete logical clause:
  #+BEGIN_QUOTE
  (∅が)[かれを信じる]ようになった - (I) came to [believe him] - I became the state of believing him
  #+END_QUOTE

  This is often used with the potential helper verb:
  #+BEGIN_QUOTE
  日本語のマンガが読*める*ようになった - Japanese manga became readable to me
  #+END_QUOTE

  In both cases the state of something is changing. (My) state of not believing became a state of believing, the manga's state of being unreadable became a state of being readable.

  <<ようにする>>
  「ようにする」 is the /other-move/([[other-move]]) version of the 「なる」 construction, to make something enter a state:
  #+BEGIN_QUOTE
  まじょがさくらをかえるにした - Witch sakura frog-into did - Witch /turned/ Sakura into a frog
  #+END_QUOTE
  #+BEGIN_QUOTE
  よく見えるようにする - Make (someone/something) look good
  #+END_QUOTE

  「ようにする」 also has an extended use meaning 'make sure':
  #+BEGIN_QUOTE
  ドアにかぎをかけるようにしてください - Please make it so that (you) lock the door
  #+END_QUOTE
  Related to this is saying something about something that oneself does regularly:
  #+BEGIN_QUOTE
  毎日歩くようにする - (I) try to make it so that (I) walk every day
  #+END_QUOTE
  Unlike 「ことにする」 ([[ことにする]]) 「ようにする」 leaves a little wiggle-room or doubt. It's not something guaranteed, but it is the intent, hence 'try to'.

  「ように」 can also be used as a conjunction to show /cause-and-effect/. This isn't a separate grammatical usage, it only seems that way from the English translation:
  #+BEGIN_QUOTE
  よく見えるように口べにをつける - Look better, in order that, apply lipstick - Apply lipstick in order to look better
  #+END_QUOTE
  In 「よく見えるようにする」 we're saying to make someone look better without specifying the means, we're just using the catch-all verb 「する」. In the conjunction example, the second clause is simply replacing the catch-all 「する」 with the actual means by which the first clause was accomplished.

  One final note is that sometimes ように can be seen on the end of a sentence:
  #+BEGIN_QUOTE
  日本に行けますように - I wish (someone) could go to Japan
  #+END_QUOTE
  This is most typically seen with 「ます」 sentences, and particularly in prayers or petitions. This is a shortening of 「ようにする」 or 「ようにしてください」.

  <<ことになる>>
  As we know 「こと」 refers to an /abstract/ thing i.e. a situation or circumstance.
  #+BEGIN_QUOTE
  (∅が)(∅を)けっこんすることにした - (It) became the thing of getting married
  #+END_QUOTE
  What is 'it'? It is the same thing it might be in English, the situation/circumstance in which getting married is the thing.

  We have to use 「こと」 here because we cannot attach the logical particle に (or any logical particle) to anything but a noun. So we use 「けっこんする」 as a modifier for 「こと」 in order to give a noun for the situation/circumstance of getting married.

  What does this really mean?
  #+BEGIN_QUOTE
  (∅が)(∅を)けっこんすることにした - We decided to get married - We brought about the situation of getting married - We brought about the situation in which getting married was the thing
  #+END_QUOTE

  <<ことにする>>
  #+BEGIN_QUOTE
  (∅が)フランスで留学する(∅が)ことになった - (I) France study (it) thing-in turned into - It became the thing of studying in France - It came about that I studied in France
  #+END_QUOTE
  Because 「ことにする」 is a deliberate act, it is taken in many cases to imply a deliberate decision. Notice however there is no actual decision being made by anyone. 「ことになる」 on the other hand implies that something came about without our control:
  #+BEGIN_QUOTE
  (∅が)(∅を)けっこんすることになた - (It) came about that we're getting married
  #+END_QUOTE

  #+BEGIN_QUOTE
  (∅が)たいへんあことになった - (It) became a terrible thing
  #+END_QUOTE
  This time 「ことに」 is not being used on a logical clause, just a single word and so does not carry the implication of a decision being made anywhere, as there is no action to be decided on.

* Lesson 33: Japanese limiting terms: だけ, しか, ばかり, のみ
** だけ - Limit (only)
   「だけ」 means 'limit'. Often this is translated as 'only' and in it's most basic form 'only' is what we'd say in English, however it's important to realise that in order to understand some of its other uses, it really means 'limit'.
   #+BEGIN_QUOTE
   1000 円だけ持っている - (I) hold limit-of 1000 yen - I have only 1000 yen
   #+END_QUOTE
   Note: Implication neutral. 「だけ」 functions essentially as a noun. In the set uses given here its particle (in this case を) can be dropped. In many other uses it takes a particle like any other noun.

   #+BEGIN_QUOTE
   できるだけ勉強します - To the limit of the possibility I will study - I will study if I can/as much as I can
   #+END_QUOTE
   At this point if we think of 「だけ」 as 'only' we will begin to get confused. 「できろだけ」 means 'to the limit of possibility'.

   #+BEGIN_QUOTE
   留学しただけあって英語はうまい - Because of the limit of the fact (I) studied abroad, (my) English is excellent.
   #+END_QUOTE
   This 「あって」 is the connective (て-form) form of 「ある」. The because in the sentence being the て form which remember often implies the cause of the following effect. A common translation of 「だけあって」 is 'not for nothing' but what's actually being said here is 'precisely because and only because (I) studied abroad (my) English is excellent'.

   #+BEGIN_QUOTE
   安いだけあってすぐに壊れちゃった - Because of the limit of it being cheap it quickly broke - Precisely because it was cheap, it broke quickly
   #+END_QUOTE
   「だけ」 is being used for its ability to limit something down to something precise. Out of all the possible reasons that it could've broken, it is the reason that it is cheap. We have limited the possibilities down to just one. Again, 'only'.
   #+BEGIN_QUOTE
   留学しただけあって英語はうまい - Only by studying abroad did I get that good at English
   #+END_QUOTE
   #+BEGIN_QUOTE
   留学しただけあって英語はうまい - Only something really cheap would break that quickly
   #+END_QUOTE

** しか - More than
   「しか」 is often confusing because people are given the impression that it means more or less the same thing as 「だけ」.
   #+BEGIN_QUOTE
   1000 円だけ持っいない - (I) don't hold more than 1000 ten
   #+END_QUOTE
   「しか」 means 'more than', so long as we understand this it is very simple. 「しか」 is only ever used in negative sentences, there is always a 「ない」 or an 「ありません」 when we use 「しか」, so it ends up saying 'not more than'.

   「だけ」 doesn't imply that 1000 yen is a lot or a little, it only says that that is what we have and nothing else. 「しか」 implies that the 1000 yen we hold is not enough. 'I don't have any more than 1000 yen' places emphasis on the 1000 yen and it being too little or that if someone wants more they aren't going to get it.

   #+BEGIN_QUOTE
   にげるしかない - There's noting more (we can do) than run - There's nothing for it but to run - There's no other action but to run
   #+END_QUOTE

** ばかり
   「ばかり」 and 「だけ」 have the same *literal* meaning (only/just) but as we learned in the lesson on ばかり, it's a hyperbole, we don't literally mean it only sells bread. Just that it sells bread far more than anything else.

  「ばかり」 is essentially a noun, it is used with だ and as we know we can only use だ with nouns, although we will find that sometimes the だ/です is left off in casual speech.

  「ばかり」 simply means 'just' or 'nothing but'. One of the most common uses is to place it after a past-tense statement to say that something has 'just' taken place. This is just the same as in English.
  #+BEGIN_QUOTE
  来たばかり(だ) - I just came
  #+END_QUOTE
  Why do we use the word 'just' in this way (in English and in Japanese)? It's another case of /hyperbole/, just like in the last lesson. When we say 'just' we mean 'nothing else can have happened in so short a time', obviously this isn't literally true.

  We can only attach 「ばかり」 to past-tense actions because in order for something to have 'just' happened it must have well, happened.

  The next use of 「ばかり」 expresses that there is a great deal of something. Is this 'opposite' use just random? Once again we do the same thing in English.

  We can say that someone or something does 'nothing but' an action by adding 「ばかり」 to the て-form of the word.
  #+BEGIN_QUOTE
  泣い^{1}て^{2}ばかり^{3} - do^{2} nothing but^{3} cry^{1}
  #+END_QUOTE
  This example could be literal. It could also be exclusively figurative:
  #+BEGIN_QUOTE
  ゴルフをしてばかり - Only plays golf - Just plays golf (In reality they play an awful lot but not /only/)
  #+END_QUOTE

  「ばかり」 can also function as a conjunction:
  #+BEGIN_QUOTE
  ∅がうたったばかりかおどった - (∅) not only [Sentence 1] but also [Sentence 2]
  #+END_QUOTE
  There is a sense of unexpected or impressive positive or negative cumulation here.

  The only only extra thing to understand here is the use of the か-particle. Sometimes we put か after something to say that it isn't the case ([[か]]).
  #+BEGIN_QUOTE
  ∅がうたったばかりかおどった - (They) sing just don't, (also) dance. - They don't just sing (but also) dance. - Not only do they sing, they also dance.
  #+END_QUOTE

  # TODO List all ways of saying because
  <<Because>>
  The other common conjunction made with 「ばかり」 is 「ばかりに」. に itself can something be added to form a conjunction, like with 「のに」. 「ばかりに」 is an /explanatory/ conjunction. It says 'something happened because...'. The most common explanatory conjunctions are 「から」 and 「ので」 but 「ばかりに」 has a special implication, it's not simply saying that one thing happened because of something, it's saying that something happened *just* because of something.
  #+BEGIN_QUOTE
  みみか大きいばかりに誰もあそんでくれない - Just because my ears are big no one will play with me
  #+END_QUOTE

** のみ
   「のみ」 is just 「だけ」 in its simplest sense i.e. 'only'.
   #+BEGIN_QUOTE
   あのお店はパンのみうる - The shop only sells bread
   #+END_QUOTE
   「のみ」 is typically used in polite or formal contexts, otherwise 「だけ」 is used.

* のに、 なのに - Opposing conjunction (but)
   「のに」 and 「なのに」 are often used as a sentence ending as well as a conjunction.

   「のに」 is a conjunction, something that joins two clauses, each of which could be a complete sentence in of themselves, to form one compound sentence. 「のに」 is an /opposing conjunction/, the main /opposing conjunction/ in English is 'but'. We use an opposing conjunction when the second clause stands in opposition to the first clause. The other opposing conjunctions in Japanese are 「けど」 and 「が」.
   # TODO けど and か
   #+BEGIN_QUOTE
   お店に行った​*が/けど*​パンがなかった - I went to the shops but there was no bread.
   #+END_QUOTE

   「のに」 is a bit different to these two as it tends to (but doesn't always) imply that the second clause is unsatisfactory, and personally disappointing to the speaker.
   #+BEGIN_QUOTE
   パンがおいしいのにお客さんが來ない - Even though the bread is delicious, the customers don't come.
   #+END_QUOTE

   How does this conjunction become a sentence ender? Grammatically speaking it doesn't. 「のに」 is still always a conjunction, but sometimes the second clause isn't given. These are called /trailing statements/, statements that leave the conclusion unstated (but implied). These are very common in casual speech. Similarly we may often see sentences end with the て-form, grammatically this is wrong as the て-form is also a conjunction, but it's often done nonetheless.
   #+BEGIN_QUOTE
   赤ちゃんがうるさくて - The baby is/was noisy and so...
   #+END_QUOTE
   What this means exactly depends on context, it may mean that we couldn't sleep, or it was embarrassing.

   #+BEGIN_QUOTE
   さくらが約束したのに - Even though Sakura promised... (she hasn't done something)
   #+END_QUOTE

   What about 「なのに」? The reason sentences end in 「なのに」is that when we use の we have to use the conjunctive form of だ or 「です」. So when that first clause ends in だ, we have to change it to な in order to put a の after it.
   #+BEGIN_QUOTE
   ∅が晴れた日曜日*だ* - It is a sunny Sunday (lit: it is a sunday that became sunny)
   #+END_QUOTE
   #+BEGIN_QUOTE
   ∅が晴れた日曜日*な*のに - It is a sunny Sunday but... (I can't go outside etc.) - Even though it is a sunny Sunday (I need to finish my homework etc.)
   #+END_QUOTE
* Conditionals
** と
  See と-conditional ([[と conditional]]).

** ば/れば conditional helpers
   <<ば conditional>>
   The と conditional's particular characteristic was its exclusiveness, in many cases we can use the conditionals interchangeably without much changing in terms of meaning, but each conditional does still have its own unique qualities.

   The special characteristic of ば/れば ([[ば conditional]]) is that is used for /hypotheticals/. They always mean 'if' and can't ever mean 'when', because we never know for sure if the condition will take place. Consequently, if we use it about something that happened in the past it has to be something that didn't happen, because if it had happened we wouldn't be dealing with a hypothetical.

   The ば/れば conditional is a helper that attached to the え-stem of a verb ([[Verb stems]]):
   | あ | い | *う* | *え* | お |
   | か | き | *く* | *け* | こ |
   | さ | し | *す* | *せ* | そ |
   | た | ち | *つ* | *て* | と |
   | な | に | *ぬ* | *ね* | の |
   | ば | び | *ぶ* | *べ* | ぼ |
   | ま | み | *む* | *め* | も |
   | ら | り | *る* | *れ* | ろ |

   For adjectives remove the い and add the helper 「ければ」. 「ない」 -> 「なければ」.

   This hypothetical nature allows ば/れば to be used in many common Japanese expressions:
   #+BEGIN_QUOTE
   どうすればいい？ - How if I act will be good? How act if good? <-> Good if act how?
   #+END_QUOTE
   - Note: the most apt translation of する most of the time is really 'act', not 'do':
   #+BEGIN_QUOTE
   しずかにする - Act quietly
   #+END_QUOTE

   #+BEGIN_QUOTE
   かさを持ってくればよかった - If I had brought an umbrella, that would've been good - I should have brought an umbrella
   #+END_QUOTE

   #+BEGIN_QUOTE
   勉強しなければいけない - If I don't study it won't go/it won't do - I must/should study
   #+END_QUOTE
   - Note: There isn't actually a word for 'must' in Japanese, so we always use this 'If I don't do x it will be bad' construction.

   Because this is a long winded way of saying something it often gets cut down:
   #+BEGIN_QUOTE
   。。。しなければ
   #+END_QUOTE
   #+BEGIN_QUOTE
   。。。しなけば
   #+END_QUOTE
   Even in very casual speech it is still often said in full to emphasise the 'must':
   #+BEGIN_QUOTE
   なぜいかなければいけない - Why must I come?
   #+END_QUOTE

** たら/だら conditional
   The 「たら/だら」 conditional is particularly easy to form, all we do is form a verb or an adjective into its 「た/だ」 past form and add ら. 「たら/だら」 is the only conditional that can be used about past events. Of course, if we are referring to something in the past it's not really a conditional. We aren't saying 'if' here, we're saying 'when'. We know that the condition has been fulfilled because it's already happened. What 「たら」 does is show that the event that happened in the past was unexpected or surprising. This is because, rather than using one of the more regular means of showing that one event followed another such as using the て-form or 「から」, we're using an /if-type conditional/. We're stressing the fact that what did happen might well not have happened, and that the thing not having happened might've been more inline with what we'd have expected.
   #+BEGIN_QUOTE
   家に帰ったらさくらがいた - When I returned to the house, Sakura was there (surprisingly). (She doesn't even have a key, she must've climbed in through the window. Sakura does that kind of thing from time to time y'know)
   #+END_QUOTE

   We can also use 「たら」 on future events. Doing so tends to add stress on what will happen if the condition is fulfilled, as opposed to 「れば」 which poses more stress onto whether or not the condition will be fulfilled, or even the fact that it wasn't fulfilled. Again, 「たら」 is more 'when' than 'if'.

   Sometimes the forms 「ったら」 and 「ってば」 to indicate exasperation.
   #+BEGIN_QUOTE
   さくらったら
   #+END_QUOTE
   #+BEGIN_QUOTE
   さくらってば
   #+END_QUOTE
   What this literally means is a contraction of 「といたら」 or 「といえば」, in other words: 'When you speak of Sakura' i.e. 'Oh you Sakura...', 'When it's Sakura it's always like this...'. It's not flattering, it is critical, but it's not very strongly so. It can be quite humorous or joking. 「ってば」 is more likely to express real exasperation and can be put onto more things than just a person's name.
   #+BEGIN_QUOTE
   もう言ったってば - I've already said that haven't I?...
   #+END_QUOTE

** なら conditional
   「なら」 is an easy to use particle like helper. All we do is put なら after what we say, which turns it into a conditional. We can put it after nouns and complete logical clauses. If used after a noun we don't need to use the copula (だ) probably because the な of 「なら」 has its roots in the copula itself.

   「なら」 can be used on present and future conditionals that aren't in any real doubt at all. For example, if Sakura is worried that something may not be possible to her, we might say:
   #+BEGIN_QUOTE
   さくらなら、できる - If it's Sakura, it will be possible
   #+END_QUOTE
   Of course we know it's Sakura, we're talking to Sakura. So what we're really saying is 'Since it's Sakura, it will be possible'.
   #+BEGIN_QUOTE
   Q. 駅はどこですか - Where is the station
   A. 駅なら、 あそくです - If it's the station you're asking for, it's over there
   #+END_QUOTE
   Of course there isn't any real doubt that it's the station that we're asking for, so again, 'since'.

* TODO (Bring in other conjunctions) Conjunctions
  Sentences where there is more than one logical clause *must* be contain some kind of conjunction. There are many kinds of conjunction, many we have covered already:
  - If/When ~ たら、 なら、 ば
  - And/but ~ そして、 けど
  - Because ~ から、 ので

  We also need to look out for the verb/adjective clause conjunctions:
  - て-form
  - い-stem

  Remember the い-stem of a verb is the main conjunctive stem out of the four verb stems. It can connect nouns to verbs, other verbs to verbs, and various helpers to verbs. It can also connect one logical clause to another.

  # There's a lot of reiteration about が being invisible here

  In Japanese a sentence has to end with an engine:
  - う (A verb)
  - い (an adjective)
  - だ (the copula, can't be な because then it's modifying a noun, not powering a sentence)

  The sentence will always end with an engine except for if there are one or two /sentence ender particles/ (They are not part of the logical sentence).

  How do we find, or how do we eliminate the possibility of a compound sentence? Just as before, a logical clause must end with an engine, and if the sentence is compound it must end also with a connector.

** が (Conjunction)
As we know the が particle is in every japanese sentence, whether we can see it or not.

There is a second が, which functions as a (usually contrastive) clause connector:
#+BEGIN_QUOTE
お店に行った*が*パンがなかった - I went to the shops *but* there wasn't any bread.
#+END_QUOTE

It isn't possible to confuse these two が s because the particle が can only ever mark a noun, and the clause connector が can only mark a complete clause (which cannot end in a noun).

が doesn't have to be contrastive, most of the time it is, but it can be used just as a regular, non-contrastive conjunction.

Also: sometimes this が will be used at the end of a sentence to soften a request.
#+BEGIN_QUOTE
コーヒーがほしいが - I'd like some coffee - I'd like some coffee but (if it's any trouble it's not necessary)
#+END_QUOTE

** に
に is the targeting particle. There is also another に that functions the same as と (and). This に is more prevalent in older Japanese texts.

It is further used in certain expressions like 「それに」 (furthermore) leveraging the 'and' quality of に to be a clause connector.

* ほう (comparison)
  「ほう」 is quite different from 「より」 ([[より]]) and 「から」. It's not a particle, it is a noun, hence 「のほう」. It's literal meaning is 'direction' or 'side'. When it means 'side' it means 'side' in the sense of direction, not in the sense of 'edge'.

  The idea of 'side' isn't limited to physical spaces, but concepts as well. Also, by nature of there being 'a' side it is implied that there is another side to contrast with. Two sides of a coin and all that.

  「ほう」 can follow a noun as in 「さくらのほう」 or we can put it after a verb or adjective, in which case the verb/adjective is describing 「ほう」.
  #+BEGIN_QUOTE
  Q. メアリがきれいだと思う？ - Do you think Mary is pretty
  A. さくらの*ほう*がきれいだ。- The side of Sakura is pretty - I think Sakura is prettier
  #+END_QUOTE
  Once again this is a /comparative/ structure, we're *not* saying that Sakura is pretty and Mary isn't, only that 'the side of' Sakura is prettier than 'the side of' Mary.

  Notice again how we don't need 「より」 here, just as before we didn't need 「ほう」 to express the same thing.

  A lot of the time 「より」 and 「ほう」 will be used individually. When they're being used together it's usually either formal or adding emphasis.

** いっぽう 一方
   Another use of 「ほう」 is in the expression 「いっぽう」 which means 'one side' or 'one direction'. Often we see this in narrative, sometimes at the very start of a sentence, or even the start of a paragraph or entire chapter.

   What 「いっぽう」 is doing is essentially the same as the English 'meanwhile'. 「いっぽう」 does *not* mean 'meanwhile' because it doesn't. 'Meanwhile' is a /time-expression/ meaning 'at the same time'. 「いっぽう」 while performing the same function does it quite differently. It's really saying, 'All that (the previous sentence/paragraph/chapter) was one side, now we're going to look at the other side'.

   Just like 「でも」 it wraps up whatever came before it with で which is the て-form of 「です」 (all that was existing), with the contrastive function of も to give 'but'. 「いっぽう」 often drops the copula で however.

   #+BEGIN_QUOTE
   この辺りは静かな一方で不便だ - It's quiet around here, but it's inconvenient - On one hand it's quiet, but on the other it's inconvenient
   #+END_QUOTE
   - Note: Remember な is the connective form of だ.

   Another use of 「いっぽう」 is that it can also be used after a complete verbal clause to show that something that is happening is continuing in one direction.
   #+BEGIN_QUOTE
   この村の人口が減る一方 - This village's population is declining (and declining and declining) - This village's population just keeps on declining
   #+END_QUOTE

* ところ - The Japanese concept of place
  「ところ」 means 'place'. It means a literal place and also takes on slightly metaphorical uses like: 「わたしのところ」 - my place - my apartment (etc.).

  In japanese the /figurative/ sense of place goes a lot further than it does in english. for example
  #+begin_quote
  さくらのどこが好きなの？ - lit: Sakura's where do (you) like - what place of sakura do (you) like?
  #+end_quote
  An appropriate answer to this might be 「やさしだ」 - 'she's gentle' i.e. 'the place that i like about her is that she's gentle', '(one of) sakura's good places is that she's gentle'. 'Place' here doesn't mean anything at all like a physical location, it means an aspect of something, even if that aspect is very abstract.

  #+begin_quote
  Q. わかりましたか？ - did you understand it?
  A. 分かるところがあったが分からないところもありました - there were places i understood and places i didn't understand
  #+end_quote
  Notice that this is closer to a usage of 'place' we have in english. Don't get mixed up however, we aren't saying 'there were times i didn't understand', we're saying 'there were aspects/subtleties i didn't understand'.

  Place is also often used to mean a place not in space but in time. We can use 「ところ」 with 'a does b' sentences in all three tenses.
  #+begin_quote
  昼ごはんを食べるところだ - i'm just about to eat lunch - (it (the present time) is) (i'm) just about to eat lunch place.
  #+end_quote
  Note: this is an 'a is b' sentence with a だ-engine, but the original sentence the construction comes from is an 'a does b' sentence 「∅が昼ごはんを食べる」

  #+begin_quote
  昼ごはんを食べているところだ - I'm eating lunch right now
  #+end_quote
  #+begin_quote
  昼ごはんを食べたところだ - I just ate lunch
  #+end_quote
  Note: in all of these examples the 「ところだ」 is adding an immediateness to the place in time something is/will/was happening. I *just* ate, I'm eating *right now*, i'm *just about to* eat.

  We could easily also say:
  #+begin_quote
  昼ごはんを食べたばかりだ - i just ate lunch
  #+end_quote

  Sometimes a few corners of this structure are cut. As with many regular set expressions 「だ」 can be cut off. 「ところ」 can also be shortened to just 「とこ」.
  #+begin_quote
  なごやに着陸したとこ - i just landed at nagoya
  #+end_quote

  Remember: even though we've been covering examples of time, 「ところ」 does still mean place.
  #+begin_quote
  いいところに来たね! - you came to a good place didn't you!
  #+end_quote
  But it can mean either:
  #+begin_quote
  いいところに来たね! - you came at a good time didn't you!
  #+end_quote

* じゃない, ではない
  Japanese often contains what appears to be negative statements, when what is meant are really positive statements. For example:
  #+BEGIN_QUOTE
  さくらじゃない - That isn't Sakura
  #+END_QUOTE
  Really this means:
  #+BEGIN_QUOTE
  さくらじゃない - That's Sakura isn't it? - That *is* Sakura
  #+END_QUOTE

  What is 「じゃない」?  「じゃない」 is a contraction of 「ではない」 which is the negative of the copula (だ).
  #+BEGIN_QUOTE
  これは(∅が)ペンではない - As for this, as for being a pen (ペンだ), isn't
  #+END_QUOTE

  So, grammatically 「さくらじゃない」 is in fact a negative statement. Negative questions are used in most languages:
  #+BEGIN_QUOTE
  Nice day, *isn't* it?
  #+END_QUOTE

  A question like 'Are you Sakura', is neutral, there is no suggestion of whether we expect them to or not to be Sakura. 'You're Sakura aren't you?' however shows that we expect the person to be in fact Sakura.

  The confusing part is that only in formal speech would we explicitly mark the question i.e:
  #+BEGIN_QUOTE
  さくらじゃないですか
  #+END_QUOTE
  か is not used as a sentence-ending question marker in this way in non-formal Japanese.

  「さくらじゃない」therefore has three possible meanings, a statement, a question, or a third meaning, each indicated by tone.
  #+BEGIN_QUOTE
  さくらじゃない - Not Sakura
  #+END_QUOTE
  #+BEGIN_QUOTE
  さくらじゃない - Sakura isn't it?
  #+END_QUOTE
  #+BEGIN_QUOTE
  さくらじゃない - If it isn't Sakura!
  #+END_QUOTE
  This use of tone (./?/!) is just the same in English.

  「じゃない」 can also be used as a negative-question sentence-ender in a similar sense as ね:
  #+BEGIN_QUOTE
  暑いじゃない - It's hot isn't it (expecting agreement)
  #+END_QUOTE
  #+BEGIN_QUOTE
  暑いね - It's hot isn't it (expecting agreement)
  #+END_QUOTE
  - Note: 「暑いじゃない」 is not the negative of 「暑い」 which is 「暑くない」

  「じゃない」 can also be used after verbs:
  #+BEGIN_QUOTE
  もう言ったじゃない - I already said that didn't I?
  #+END_QUOTE

  「じゃない」 itself is often reduced to just 「じゃん」
  #+BEGIN_QUOTE
  寒いじゃん - It's cold isn't it
  #+END_QUOTE

  All of these expressions are very colloquial and aren't in fact grammatically correct. Remember, 「じゃない」 = 「ではない」 which is the negative form of the copula だ, and だ can only be used with nouns.

  There are of course more formal ways of using 「ではない」 as a positive statement but these of course tidy up the grammar
  #+BEGIN_QUOTE
  その理論が間違っている*の*ではないでしょうか - Might that theory not be in error?
  #+END_QUOTE
  - Note: This may be used as an assertion. Once we have definitively proven something, we may finish with this as a short of challenge.

* Questions
  か is used to mark questions, but not what we might usually think of as a question. For example
  #+BEGIN_QUOTE
  さくらが来るかわからない - I don't know if Sakura will come - Sakura will come? I don't know
  #+END_QUOTE
  #+BEGIN_QUOTE
  さくらが来るか知っていますか - Do you know if Sakura is coming?
  #+END_QUOTE

  か displaces logical particles much of the time:
  Normal structure:
  - XX が分からない
  - XX を知っています
  Logical particles displaced by か:
  - XX か分からない
  - XX か知っています

  か is also used in the common expression 「かどうか」 which means 'whether or not':
  #+BEGIN_QUOTE
  さくらが来るかどうか分からない - I don't know whether Sakura's coming or not
  #+END_QUOTE
  Precisely 「かどうか」 means '...? how? ...' i.e. 「さくらが来るかどうか分からない」 - I don't know if Sakura's coming or how it will be.

  From this usage we can see how we can use か to mean 'or':
  #+BEGIN_QUOTE
  お茶かコーヒーどちらがいい？ - Which is good, tea or coffee?
  #+END_QUOTE

** かもしれない - Maybe
   - XX か - The question/proposition XX
   - も - As much as
   - しれ - え-stem of 知る (know) indicating potential (lesson 10)
   - ない - Negative helper adjective
   - The question of XX, I cannot go so far as to know = Maybe XX

** かな - I wonder
   <<かな>>
   #+BEGIN_QUOTE
   さくらが来るかな - I wonder if Sakura will come
   #+END_QUOTE
   - か bundles the question
   - な address the question to oneself

** か is a nominaliser
   #+BEGIN_QUOTE
   まるで[ゆうれいを見た]*かの*ような顔をした - A face as if one had seen a ghost
   #+END_QUOTE
   Notice how か has turned 「ゆうれいを見た」 into a quasi-noun that can take の.

** もんか & ものですか
   In certain expressions か calls into question (denies) a proposition
   #+BEGIN_QUOTE
   格好に行くもんか - I'm not going to school
   #+END_QUOTE

   「ものですか」 and 「もんか」 literally mean 'Is that a thing', this is the same kind of negativising question we have in English i.e. 'Do you think I'm going to do that?'

   Note how this is one of the few uses of か as a sentence ending question marker in non-formal speech. This is because of it's purposefully rough nature.
   # Possible elaborate on this some time

   Another place we often see か as a negativising question marker is in 「どころか」. Remember 「どころ」is a form of 「ところ」 and means place/time/circumstance/condition. When said as 「どころ」it's usually negative.
   #+BEGIN_QUOTE
   漢字が読めるどころかひらがなも読めない - Far from kanji being possible (for me) to read, even hiragana isn't read-possible - Not only can't I read kanji, I can't even read hiragana
   #+END_QUOTE
   What is 「どころ」 doing here? It's dealing with the concept of reading kanji and negativising it. 'The circumstances in which I could read kanji aren't', 'Not only has the situation not reached this far place, it hasn't even read this near place'.
* まま
  「まま」 is a noun. What 'thing' is it? It's an unchanged condition:
  #+BEGIN_QUOTE:
  自然のままの森 - Nature's unchanged-condition's forest - A forest in its natural state
  #+END_QUOTE
  #+BEGIN_QUOTE:
  そのままで食べられるの？ - That unchanged state-being, eat-able-does? - Can you eat them just as they are?
  #+END_QUOTE
  Note: This で is the copula (だ)
  #+BEGIN_QUOTE:
  そのまま食べられるの？ - That unchanged state-being, eat-able-does? - Can you eat them just as they are?
  #+END_QUOTE
  Note: we can drop the で see the previous lesson

  「まま」 being an unchanged state, in cases where the state could change (like uncooked food becoming cooked) we're essentially using as a time period. Therefore we can ignore the copula like a time expression:
  #+BEGIN_QUOTE:
  そのまま食べられるの？ - While they're uncooked, can they be eaten?
  #+END_QUOTE

  #+BEGIN_QUOTE:
  パジャマのまま朝ごはんを食べる - Pyjama's unchanged state eat breakfast - Eat breakfast while still in pyjamas
  #+END_QUOTE

  #+BEGIN_QUOTE:
  いつまでも若いままでいたい - Forever young unchanged-state-be exist-desire - I'd like to stay young forever
  #+END_QUOTE
  Notice how the adjective 「わかい」 is modifying 「まま」 (because it's a noun).

  「思いのまま」 and 「心のまま」 are common uses of 「まま」. What this means is 'The unchanged condition that's in our thoughts/heart'. This phrase is always applied to something outside of our thoughts/heart (i.e. not imaginary), and expresses that that thing is the same as how we 'think/feel'. What this means therefore is making the outside world conform to our thoughts/desires.
  #+BEGIN_QUOTE:
  思いのままに動けない - In unchanged state of my thoughts, move-possible-not - I cannot move in the way I think I should
  #+END_QUOTE
  Remember: Sometimes 「思い」 does imply desire:
  #+BEGIN_QUOTE:
  片思い - One-sided-thought (unrequited love)
  #+END_QUOTE

* Chau, Chatta, ちゃう、 ちゃった
  「ちゃう」 and 「ちゃった」 are contractions of the verb 「しまう」 meaning to finish/complete:
  。。。てしまう -> ちゃう
  。。。 てしまった -> ちゃった

  「しまう」 can be formed into the い-stem 「しまい」 making it a noun, meaning 'the finish'/'the ending'. This past tense of this is 「しまった」 which can be used all on its own as an expression meaning 'something's gone very wrong'​/'this is not at all satisfactory'.

  We can use this expression as a helper verb that we can attach to the て-form of another verb. This て + 「しまった」 gets contracted to ちゃった. If the て-form is で instead of て then 「ちゃった」 becomes 「じゃった」 just as 「では」 becomes 「じゃ」.

  This can be used for a much wider range of things than just regret. To help understand all the varies uses of this expression, think of the English word 'totally.

  We also use this about future things, with a similar feeling as 'done' is used for the past.

* Japanese word order
  As sentences become more and more complex, understanding word order becomes more necessary to understand what is going on.

  English is a Subject-Verb-Object (SVO) language. 'Susan hit Mary' does not have the same meaning as 'Mary hit Susan'. In Japanese the question of who did what to whom is answered by the logical particles, not by the order of the words in the sentence.

  As we have learned however there are still rules about what order words must come in Japanese sentences. This order is according to two simple rules:
  1. The 'engine' always goes at the end of the sentence
     a. any engine that does not come at the end of a sentence must be modifying a noun
  2. Anything that modifies any thing (noun or head-verb) always comes before it

  Point 2 is similar to English in simple cases. 'Warm day', 'nice dress', but in complex cases the modifier comes after the noun: '(the) dress I bought on Saturday'. In Japanese the modifiers *always* come before the noun.

  Point 1a:
  #+BEGIN_QUOTE
  いちばで(∅が)青いドレスを買った - I bought a blue dress at the market
  #+END_QUOTE
  We know this is a complete logical clause because of rule 1.

  #+BEGIN_QUOTE
  いちばで(∅が)買ったドレス - The dress that I bought at the market...
  #+END_QUOTE
  Not a logical clause, but a modified noun

  #+BEGIN_QUOTE
  (∅が)ドレスを買ったいちばで - The market at which I bought the dress...
  #+END_QUOTE
  Again, not a logical clause but a modified noun

  If the が marked A isn't visible, then there is nothing modifying it (sounds obvious but this hadn't clicked until it had been said).

  The structure of every sentence, in order goes:
  1. Modifiers of the A car (optional (if there is a visible A car))
  2. The A car (may not be visible)
  3. Modifiers of the B engine (optional)
  4. The B engine


  Remember: the 4 logical particles aside from が (に、 で、 を、 へ) all modify the B engine, if we see them before the A car, then they must be part of a clause modifying the A car.
  # Is this strictly true?
  Remember: modifiers can be entire clauses in their own right.

* もらう
  # TODO Notes on kureru and ageru?
  「もらう」 means to 'download'. When used with a noun it does not imply a giver of the thing we are receiving, unlike kureru and ageru which are bound to a particular giver and receiver. When used with a verb, kureru implies that the giver took the initiative, whereas morau implies that the receiver took the initiative.

  Even though no giver is implied, when a giver is mentioned, the giver is marked by に, this is the same as the receptive helper verb れる/られる, もらう like the receptive helper verb are 'pull' actions rather than 'pull' actions, in a push sentence the に marks the indirect object, the ultimate receiver of the action, whereas in a pull sentence the に marks the source of the action.
  #+BEGIN_QUOTE
  ∅がメイリーにボールを投げた - I threw the ball *at* Mary
  #+END_QUOTE
  Note: に marks the target of が-marked subject's action.
  #+BEGIN_QUOTE
  ∅がメイリーにボールを投げられた - I throw-received the ball *from* Mary
  #+END_QUOTE
  Note: に marks the source of が-marked subject's action.

  #+BEGIN_QUOTE
  ∅がお医者さんに見てもらう - (I) will have a doctor see me
  #+END_QUOTE
  The Doctor does seeing and the が-marked actor does receiving.

  #+BEGIN_QUOTE
  散髪をしてもらう - Receive a haircut
  #+END_QUOTE
  No implication of from whom.

  The person もらう-ing does not have to be the speaker:
  #+BEGIN_QUOTE
  散髪をしてもらったほうがいい - (You) should get your haircut
  #+END_QUOTE
  Kureru cannot be used for someone other than oneself/one's group, but もらう can.

  The polite form of もらう is いただく (or as this is polite speech is usually used with ます so) いただきます. We are used to this phrase before eating, but what it really means is something like 'I humbly receive'.

** させてもらう
   See also: /causative helper verb/ ([[causative]])
#+BEGIN_QUOTE
聞か-せて-もら-え-ます-か - hear-cause-receive-possible-formal-question - Is it possible to receive (your) causing (me) to hear, kind sir? (Can you tell me?)
#+END_QUOTE

#+BEGIN_QUOTE
学生でも下宿させてもらえませんか - Student even-if, caused-to-lodge receive-possible is not, good madam? Even if one is a student, is it not possible to receive being caused to lodge here? (Do you take students?)
#+END_QUOTE

#+BEGIN_QUOTE
∅がメガネを合わせてもらった - (I) glasses caused-to-fit received (I was fitted for glasses)
#+END_QUOTE

Sometimes this can mean 'allow':
#+BEGIN_QUOTE
帰らせてもらいます - (I) will receive (your) allowing (me) to go home
#+END_QUOTE

* TODO Irregularities in Japanese (Lesson 54)
* もの and こと secrets
When first introduced もの and こと where explained as being for tangible, and abstract things separately. This is a good explanation for an early learner, but is not the whole picture:
#+BEGIN_QUOTE
愛はすばらしいいものだ - Love is a wonderful thing
#+END_QUOTE
Obviously love is abstract, so why are we using もの? もの is used for /nouns/. A noun representing a physical thing or a noun representing an abstract thing.

#+BEGIN_QUOTE
日本に行ったことがある - (I) have been to Japan
#+END_QUOTE
Notice how this is a very different statement to 'I went to Japan'. 'I went' speaks of one particular instance, whereas 'I have' could mean once, or many times. It is the general fact of having been. '(As for me) the thing (the activity/the fact) of 'went to Japan' exists'.
#+BEGIN_QUOTE
日本に行くことがある - The fact of my *going* to Japan exists - I sometimes go to Japan
#+END_QUOTE

#+BEGIN_QUOTE
どんな人にも失敗することがある - Everybody sometimes makes mistakes - Whatever kind of person it may be, the fact of making mistakes exists.
#+END_QUOTE

** TODO (Move this) もの as a sentence ender
Sometimes もの is used in a way that looks like a sentence-ender. The first way is when ものだ is added to a complete logical clause. What this means, is that, the logical clause that we're speaking about, as a generalisation, is reality (is a thing).
#+BEGIN_QUOTE
冬は寒いものだ - Winter is cold, and that's just a thing (fact)
#+END_QUOTE

# There are some notes here on the strict grammaticality of this construction.

#+BEGIN_QUOTE
子供のころには、よくこちらに来たものだ - When I was a child, coming here was a thing.
#+END_QUOTE
Note that such a statement has a nostalgic ring to it, and a sense of personalness. As well as an implicit statement that we no longer come.

What is the difference between:
#+BEGIN_QUOTE
日本に行ったことがある - (I) have been to Japan
#+END_QUOTE
#+BEGIN_QUOTE
日本に行ったものだ - (I) used to go to Japan
#+END_QUOTE
Note the latter is far more emotional.

** TODO (Move this) こと as a sentence ender
こと is used as a sentence ender for lists of rules. Even a single statement, if followed by こと shows that that thing is a rule/regulation. こと shows that the statement is a decision that has been made. Refer to lessons 28 and 29.
