# ∅
* Core sentence
   Every sentence is formed of two elements, they are the が-marked noun and the /engine/.

   In all languages there are only two kinds of sentence:
   - A *is* B i.e. Sakura is Japanese
   - A *does* B i.e. Sakura Walks

   #+BEGIN_QUOTE
   さくらが日本人だ - Sakura is Japanese
   #+END_QUOTE
   #+BEGIN_QUOTE
   さくらが歩く - Sakura walks
   #+END_QUOTE

   There are three possible engines:
   - Verb - A does B
   - だ-marked noun - A is B
   - い-"Adjective" ([[*Adjectives]]) - A is B

   The engine *always* comes at the end of the sentence (with the exception of sentence ender particles ([[*Sentence ender particles]]).

   <<Invisible が>>
   The が-marked noun is not always visible in the sentence. It is still present as part of the core of the sentence however. The closest English equivalent to this invisible が is 'it'. Take this example English sentence:
    #+BEGIN_QUOTE
    The ball rolled down the hill. When the ball got to the bottom the ball hit a sharp stone and the ball was punctured and all the air came out of the ball.
    #+END_QUOTE
    This is not a sentence we would ever say in English, once we have established that we are talking about 'the ball' we would instead refer to the ball by 'it':
    #+BEGIN_QUOTE
    The ball rolled down the hill. When it got to the bottom it hit a sharp stone and it was punctured and all the air came out of it.
    #+END_QUOTE
    If we were to completely omit 'it' the sentence would still be easy to understand, we don't *need* to use this it marker each time, but English grammar *demands* it. Japanese does not, hence the 'invisible' が carriage.

    <<∅ pronoun>>
    'It' by itself doesn't really mean anything, we know what it means from context. All of the pronouns I/it/we/he/they can be replaced by an invisible logical particle ([[*Logical particles]]) (most often が) marked /∅ pronoun/. It is important to remember that the が-marked noun *is still there*.

   #+BEGIN_QUOTE
   [∅が]さくらだ - (I) am Sakura
   #+END_QUOTE
    By default 'I' is the default value of this ∅ pronoun. However, if someone were introducing their daughter and said 「さくらだ」 we would understand from context that ∅ meant this/she.

   #+BEGIN_QUOTE
   [∅が]土曜日だ - (Today) is Saturday
   It is Saturday - (Today) is Saturday
   #+END_QUOTE
   From context it is clear that ∅ and 'it' mean 'today'.

* Particles
  No particles other than が and だ can ever be part of the core sentence ([[*Core sentence]]) and only が is present in every sentence (even if invisible ([[Invisible が]]).

** Logical particles
   A logical particle tells us how the sentence logically holds together. It tells us who does what to whom with what, when and where.

   All logical particles attach to nouns, they *cannot* attach to anything but nouns. If we see a logical particle attached to anything else then we know that that word is functionally a noun.

   The noun and the particle attached to it are an inseparable pair. We must view the two together, they are a question and an answer which form a fundamental unit of the Japanese sentence.

   There cannot be a sentence without が, even if sometimes you can't see it. が can work in A is B sentences, as well as A does B sentences. The other particles can *only* work in A does B sentences i.e. that is sentences with a verb engine.
   - が - Who (or what) did it?
   - を - Whom was it done to?
   - に - Where did they go?/Where are they?
   - へ - What direction?
   - で - Where was it done? With what was it done?

*** TODO が (/ga/) - Subject <<が>>
# I may need to dig out the episode to cover this particle
*** TODO だ (/da/) - Copula <<だ>>
*** を (/o/wo/) - (Direct) Object
    The を particle marks the object of the sentence, the /thing/ that some verb (the engine) is being done to. が marks the thing that is doing the verb.
    #+BEGIN_QUOTE
    わたし​*が*​ケエキ​*を*​たべる - I eat cake
    #+END_QUOTE
    The core sentence here is 'I eat'. The extra を particle marked noun, is telling us more about the engine (eat). /What/ are we eating? We are eating cake.

    #+BEGIN_QUOTE
    わたしがぼーる​*を*​なげる - I threw the ball
    #+END_QUOTE
    The core sentence is 'I threw', and the extra を particle marked noun tells us what we threw i.e. the ball.

*** に (/ni/) - Target (Indirect Object)
    The に-particle marks the target (indirect object) of an engine. Along with が and を:
    - が tells us who does the doing
    - を tells us what it is done to
    - に tells us what the ultimate target of that doing

    #+BEGIN_QUOTE
    わたしがぼーるをさくら​*に*​なげる - I threw the ball at/to Sakura
    #+END_QUOTE
    Sakura is the destination, the target. It is important to note here that the logical particles tell us what happened. The order of the words doesn't really matter the way it does in English.

    #+BEGIN_QUOTE
    わたし​*に*​さくらがぼーるをなげる - Sakura threw the ball at/to me.
    #+END_QUOTE
    #+BEGIN_QUOTE
    ぼーるがわたし​*に*​さくらをなげる - The ball throws Sakura at me
    #+END_QUOTE
    Obviously this final example doesn't make any sense (although we might want to say something nonsensical like this in a fantasy novel or something) but we can say whatever we like in Japanese so long as we use the right logical particles.

    If we are going somewhere, or sending something somewhere, or putting something somewhere, we use に.
    #+BEGIN_QUOTE
    [∅が]みせ​*に*​いく - (I) will go to the shop
    #+END_QUOTE

    に gives us the target of an action in the literal sense, and also the target in a volitional sense, i.e. the aim of our action.
    #+BEGIN_QUOTE
    [∅が]みせ​*に*​たまごをかい*に*いく - (I) will go to the shop to buy eggs
    #+END_QUOTE
    かい is the い stem of かう, to buy ([[*Verb stems]]). The logical particles can only mark nouns. The い-stem of a verb is the equivalent noun form of it. Just as in English 'I like swimming', /swimming/ is a noun, 'I go to the shop for the purpose of buying eggs', this /buying/ is also a noun.

    As well as identifying a place we will go to, に can also specify a place we are currently at:
    #+BEGIN_QUOTE
    ∅がみせ​*に*​いる - (I) am/is at the shop
    #+END_QUOTE
    This に is still marking a target, just not a future target. In order for something to be somewhere it must've gotten there, and so に specifies the target of some past action. We can also use this for inanimate objects:
    #+BEGIN_QUOTE
    ほんは∅がテーベルのうえ​*に*​ある - As for the book, (it) exists/is on/at the table.
    #+END_QUOTE
    This use of に also applies to times as well as places, see: /time expressions/ ([[*Time expressions]]).

    Finally, に can also mark a transformation. If /a/ becomes /b/, then に also marks /b/, the thing a is becoming.
    #+BEGIN_QUOTE
    さくらは∅がかえる*に*なった - Sakura became a frog
    #+END_QUOTE
    Of course this example is a bit of a joke, but there are of course various every day things that become other things. This form of expression is also used much more often in Japanese than in English.
    #+BEGIN_QUOTE
    ことし∅が十八さいになる - This year (I) become 18 years old
    #+END_QUOTE
    #+BEGIN_QUOTE
    あとで∅がくもりになる - Later (it (the weather) will) become cloudy
    #+END_QUOTE
    See also how to use 「なる」 with adjectives ([[Becoming an adjective]])

*** の (/no/) - Possessive
    The の particle, or the /possessive particle/ functions just like the English /'s/.
    #+BEGIN_QUOTE
    さくら​*の*​はな - Sakura's nose
    #+END_QUOTE
    #+BEGIN_QUOTE
    わたし​*の*​はな - Me's (my) nose
    #+END_QUOTE
    Luckily in Japanese we don't have to worry about his/her/my/their, we just use の.

    <<の-adjectives>>
    Because this is the /possessive particle/ we can use this in another slightly different way. 「あか」 has an /adjectival/ form in 「あかい」, but not all colours have this form. The Japanese for pink, 「ピンクいる」 (lit: pink-colour) doesn't have an adjectival form in 「ピンクいろい」, nor can we use it as a secondary engine with な. So what are we to do? Well we can use the の-particle:
    #+BEGIN_QUOTE
    ピンクいる​*の*​どれすが - The pink dress (literally: The dress belonging to the class of pink things)
    #+END_QUOTE
    #+BEGIN_QUOTE
    うさぎ​*の*​OSCAR - Oscar the rabbit (literally: Oscar belonging to the class of rabbit)
    #+END_QUOTE

*** へ (/e/) - Direction
    This is a very simple particle, it duplicates a single use of に. When we say /a is going to b/ we can freely substitute に with へ. This is *all* is can do, it cannot even mark the case where something /is/, only where it is /going/.
*** で (/de/) - Means
    #+BEGIN_QUOTE
    [∅が]こうえんにいく - I go to the park
    #+END_QUOTE
    If we say 'I went by bus' or 'I ate with chopsticks' we use で for the thing we did it with, the means by which we performed the action.
    #+BEGIN_QUOTE
    [∅が]バス​*で*​こうえんにいく - I go to the park by bus
    #+END_QUOTE

** Non-logical particles
   Non-logical particles are not part of the logical structure of a sentence. They are neither the thing we are saying something about, nor what we are saying about it. They also do not tell us more about the engine of the sentence as the other logical particles do.

*** は /wa/
    The は-particle can be thought of as a /flag/. It simply marks something as the topic of the sentence, but doesn't say anything about it.

    An exact translation of the は particle would be 'As for /x/'. 「わたしは」 therefore means 'As for me', *not* 'I am' (わたしが).

    A commonly mistranslated sentence is:
    #+BEGIN_QUOTE
    わたし​*は*​日本人だ - +I am Japanese+
    #+END_QUOTE
    Referring back to the core sentence ([[*Core sentence]]) we can see that the が-marked noun so we don't actually know who or what the subject is. One may ask /'well why don't we just treat the は particle as if it is marking the subject'/. In this example it is obvious that the topic marked by は is the same as the subject marked by が, but there are many more cases where this is not true, leading to much confusion down the road. Let's look at a similar sentence. You are at a restaurant, the waitress is asking what you would like:
    #+BEGIN_QUOTE
    わたし​*は*​うなぎだ - +I am an eel+
    #+END_QUOTE
    Treating は as 'I am' doesn't work. As we now know the default value of the ∅ pronoun is 'I', but in this context it's clear that we're talking instead about /what/ we want to eat. 「わたしはうなぎだ」 therefore means 'As for me, eel'.
    #+BEGIN_QUOTE
    わたし​*は*​[∅が]日本人だ - As for me, (I) am Japanese
    #+END_QUOTE
    #+BEGIN_QUOTE
    わたし​*は*​[∅が]うなぎだ - As for me, (what I would like to order) is eel
    #+END_QUOTE

    #+BEGIN_QUOTE
    わたし​*は*​[∅が]さくらにぼーるをなける - As for me, (I) threw the ball at Sakura
    #+END_QUOTE
    #+BEGIN_QUOTE
    ぼーる​*は*​わたしがさくらに[∅を]なける - As for the ball, I threw (it) at Sakura
    #+END_QUOTE
    This time the を marked noun (not the が marked noun) has become invisible([[Invisible が]]), because what we're throwing is now marked by the は particle, ∅ here has taken the value of 'it'. Even without は we might already know what 'it' was that was thrown from context. The important thing to understand here is that as we change the logical particles from one noun to another we change the meaning of the sentence, but when we change the non-logical particle は from one noun to another it makes no difference to the logic of the sentence. It may make some difference to the emphasis, but it makes no difference to who is doing what or what they're doing it to.

** Alogical particles
*** と (/to/) - And
    Alogical particles aren't simply markers. The と the particle 'ands' two nouns together. It is therefore doing something in the sentence, it is joining a noun to another noun and inheriting its logical particle, but the と particle has no function of its own.
    #+BEGIN_QUOTE
    さくら​*と*​メイリー​*が*​あるいていた - Sakura *and* Mary were walking
    #+END_QUOTE

** TODO Sentence ender particles
* Tense
   In Japanese the tenses are not the same past, present and future tenses we're familiar with from English.

*** Non-past (future) tense
    The basic, dictionary-form of verbs are in the /non-past/ tense. The Japanese non-past tense is very similar to the English non-past tense. What is the /English/ non-past tense? It is again the plain dictionary form of a verb: /eat/, /run/, /walk/ etc. It is unnatural in English to say 'I eat cake', to mean 'I am eating cake'. It is natural however to use the non-past tense to say 'Sometimes I eat cake' or, in the explicitly future tense 'I will eat cake'. Japanese is just the same as English in this way. It is rare we use this form for talking about things actually happening right now, except in cases like literary descriptions.

    Just as the ∅ pronoun ([[∅ pronoun]]) defaults to 'I', the non-past tense defaults to the future.
    #+BEGIN_QUOTE
    さくらが歩く - Sakura will walk
    #+END_QUOTE
    #+BEGIN_QUOTE
    犬がたべる - Dog will eat
    #+END_QUOTE
    'Sakura walks' is possible, but isn't the most natural way.

*** Present (continuous)
    In order to say something like 'Sakura is walking' we need to combine the verb 「歩く」 - /to walk/ with the verb 「いる」 -  /to be/. This is done by putting the verb into the て-form ([[*て-form]]).
    #+BEGIN_QUOTE
    さくらが歩いている - Sakura is walking
    #+END_QUOTE
    #+BEGIN_QUOTE
    犬がたべている - Dog is eating
    #+END_QUOTE
    The core sentence here is 'Sakura is existing', the て-form verb, what we shall call a /secondary engine/ which modifies the main engine. In what state is Sakura existing? She is existing in the state of eating.

    # TODO Add a link here to the expanded secondary engine write-up (if one gets written)

*** Past
    <<Verb past>>
    To form the past tense of a verb we need to take the verb stem([[*Verb stems]]) and add た.
    #+BEGIN_QUOTE
    犬がたべた - The dog ate
    #+END_QUOTE

    <<Adjective past>>
    If we want to put an adjective into the past tense we drop the い and add かった.
    #+BEGIN_QUOTE
    こわい ー> こわかった - Was scary
    #+END_QUOTE

*** Negatives
    Because 「ない」 is also an adjective, the past tense of it is just 「なかった」.
    | Non-past             | Past                     |          |
    |----------------------+--------------------------+----------|
    | さくらがはしる       | さくらがはしった         | Positive |
    | さくらがはし*ら*ない | さくらがはし*ら*なかった | Negative |

    As we know 「さくらがはしる」 is not very natural Japanese, instead we would say 「さくらがはしっている」. For this, all we need to do is put the 「いる」 into the past tense:
    #+BEGIN_QUOTE
    さくらがはしっている -> さくらがはしっていた - Sakura was running
    #+END_QUOTE

*** Time expressions
    If we want to make it clear that we are talking about a future event we can add a time expression. By prefixing a sentence with あした (tomorrow), we can make it clear that what we will be doing, we will be doing tomorrow.
    #+BEGIN_QUOTE
    あした[∅が]ケーキをたべる - Tomorrow I will eat cake
    #+END_QUOTE
    Note how we simply preface the sentence with 'tomorrow', just like we would in English. This is the case with all /relative-time nouns/, 'yesterday', 'tomorrow', 'the day after tomorrow', 'next week', next month', 'next year'.

    For /non-relative/, i.e. /absolute/ time expressions we must use the に-particle:
    #+BEGIN_QUOTE
    火曜日​*に*​[∅が]ケーキをたべる - On Tuesday I will eat cake
    #+END_QUOTE
    We must attach に in all the same places we would attach on/in/at in English. 'On Tuesday', 'in March', 'at 12 o'clock'. Fortunately in Japanese we only need to use the one particle.

* て-form
    Japanese verbs fall into three groups: /Ichidan/, /Godan/, and /irregular/

    The first group are /ichidan/ (lit: one level) verbs. Morphing these verbs is easy, we simply remove the る and add our new ending. Ichidan verbs can only end in either いる or える (phonetically).

    The second group is by far the largest, the /godan/ (lit: five level) verbs. This group contains verbs that end in all of the possible verb endings: う つ る - ぬ ぶ む - く ぐ - す. Each of these ending groups has its own way of being morphed, though although they're 'five level' verbs, two of the groups use the same method so we only need to learn 4 methods. Confusingly this means that godan verbs can end in いる or える, most of these will still be /ichidan/ verbs, and fortunately even if a verb is morphed incorrectly, you will probably still be understood.
    - う つ る -> って
    - ぬ ぶ む -> んで
    - く/ぐ -> いて/いで (Note: this is the combined group)
    - す -> して

    There are only two irregular verbs, くる and する. いく, is partly irregular, but not completely.
    - くる -> きて
    - する -> して
    - いく -> いって (+いいて+)
    These are the only exceptions
* Negative nouns
    The fundamental basis of negatives is the adjective 「ない」. This adjective means 'non-exist'. The word for exist (for any inanimate thing) is ある. If we want to say that something exists:
    #+BEGIN_QUOTE
    ぺんがある
    #+END_QUOTE
    But if we want to say that something doesn't exist we say:
    #+BEGIN_QUOTE
    ぺんがない
    #+END_QUOTE
    Now, why do we use a verb for being, and an adjective for non-being? This is something that happens all throughout Japanese, when we do something we use a verb, but when we don't do something we attach ない and are therefore using an adjective as the engine of the sentence. This has a very logical reason, when we *do* something, an action is taking place, and so we use a verb, but when we *don't do* it we are describing a state of non-action, so that's an adjective.

    Above we have said 'There is no pen', how do we say 'This is not a pen'?
    #+BEGIN_QUOTE
    これはぺんがある - As for this, it's a pen
    #+END_QUOTE
    #+BEGIN_QUOTE
    これはぺんではない - As for this, as for being a pen, it's not. (Note: で is the て-form of だ)
    #+END_QUOTE

    # TODO Add link to jyanai secrion
* Verb stems
   Note: these stems apply to godan verbs. For ichidan verbs just drop the る.

    Every verb ends in one of the う-row kana. Here is the kana-grid (う-row kana that aren't used as verb endings have been removed), presented on its side.
    | あ | い | *う* | え | お |
    | か | き | *く* | け | こ |
    | さ | し | *す* | せ | そ |
    | た | ち | *つ* | て | と |
    | な | に | *ぬ* | ね | の |
    | ば | び | *ぶ* | べ | ぼ |
    | ま | み | *む* | め | も |
    | ら | り | *る* | れ | ろ |
    As we can see there are four other ways in which the verb could end. These are the verb stems. For now we're only looking at the あ-stem as this is the one we need for the negative.

    To from the あ-stem we simply shift the final kana from the う-row to the あ-row. There is one only exception and this is the only exception in the entire stem system. This exception is that う itself does not become あ but わ. This is because, take for example a verb like 「かう」, 「かあ」 would not be as easy to say as 「かわ」. Every other う-row kana is simply changed to its あ-row equivalent.
    | **わ** | い | *う* | え | お |
    | *か*   | き | *く* | け | こ |
    | *さ*   | し | *す* | せ | そ |
    | *た*   | ち | *つ* | て | と |
    | *な*   | に | *ぬ* | ね | の |
    | *ば*   | び | *ぶ* | べ | ぼ |
    | *ま*   | み | *む* | め | も |
    | *ら*   | り | *る* | れ | ろ |
* Negative verbs
   To make a verb negative we must attach 「ない」 to the あ-stem of the verb ([[*Verb stems]]).
   #+BEGIN_QUOTE
   かう ー> かわない
   #+END_QUOTE
   #+BEGIN_QUOTE
   はなす ー> はなさない
   #+END_QUOTE

   Remember for ichidan verbs we don't need to form a stem and just drop the る:
   #+BEGIN_QUOTE
   たべる ー> たべない
   #+END_QUOTE

* Adjectives
   Japanese adjectives are not the same as English adjectives. As we have learned Japanese sentences come in three kinds, depending on the type of engine they have. All three of these engines can be used like adjectives.
   - Verb ([[*Verb-adjectives]]) - A *does* B
   - だ-marked noun ([[*Noun-adjectives]]) - A *is* B
   - い-"Adjective" ([[*い-adjectives]]) - A *is* B

*** い-adjectives
   Let's start with the first one, the one we refer to as an adjective in English, the い-engine:
   #+BEGIN_QUOTE
   ぺんがあかい - Pen is red
   #+END_QUOTE
   An important note, 「あかい」 does not mean 'red', it means 'is red'. 「あか」 means red.

   If we swap the order of 「ぺんが」 and 「あかい」 then we can take this い-engine, and now use it not as the primary engine, but as a secondary engine. This would not be a complete sentence however without a new engine, for example, a new (primary) い engine.
   #+BEGIN_QUOTE
   あかいぺんがちいさい - Red pen is small
   #+END_QUOTE

*** Verb-adjectives
   Any verb in any tense can be used like an adjective:
   #+BEGIN_QUOTE
   しょうじょがうたった - Girl sang
   #+END_QUOTE
   #+BEGIN_QUOTE
   うたったしょうじょが... - The girl who sang... (Note: this sentence is not yet complete, it lacks a primary engine).
   #+END_QUOTE
   #+BEGIN_QUOTE
   うたったしょうじょがねている - The girl who sang is sleeping
   #+END_QUOTE

   Verbal adjectives can create very complex sentences in which we can use entire other-sentences (clauses) in an adjectival manner.
   # TODO Show an example

*** Noun-adjectives
   <<な-adjectives>>
   #+BEGIN_QUOTE
   いぬがやんちゃだ - The dog is naughty
   #+END_QUOTE
   We can turn 「やんちゃ」 into an adjective too, but there is one important thing to note. Just as we have to add だ to a noun to use it as an engine, here we must add な to the noun to use it as an adjective. な is in fact the connective form of だ. Don't be fooled by so-called 'な-adjectives', they're simply nouns! /Adjectival/ nouns.
   #+BEGIN_QUOTE
   やんちゃ​*な*​いぬが... - The dog who is naughty... (Note: this sentence is not yet complete, it lacks a primary engine).
   #+END_QUOTE
   #+BEGIN_QUOTE
   やんちゃ​*な*​いぬがねている - The dog who is naughty is sleeping
   #+END_QUOTE

   An important note is that we cannot do this with /all/ nouns, only nouns which are frequently used in an adjectival way. This group of nouns is what are referred to as 'な-adjectives'. We can use all nouns as adjectives, but for the rest we need to use a different technique, /の-adjectives/ ([[の-adjectives]]).
   # TODO use org's duplication function here for の-adjectives

* Adjective stem, adjective て-form, negative adjectives
   The adjective stem is simple, just drop the い and add く. This is how we make the て form, 「あかい」 ー> 「あかくて」, and it's also the way we make the negative, 「あかい」 ー> 「あかくない」.

   # Add link here
   The only exception (besides ます) is いい (is good), which has an older form, which is still widely used in よい. When we morph いい it becomes よい again:
   #+BEGIN_QUOTE
   いい ー> よくない - Not-good
   #+END_QUOTE
   #+BEGIN_QUOTE
   いい ー> よかった - Was-good
   #+END_QUOTE
   Note: 「よかった」 is a common phrase: 「∅がよかった」 - /It was good (That went well, it turned out great etc.)/

   # TODO: Rename this section to adjectives as nouns?
   <<Becoming an adjective>>
   If we want to say 'Sakura became beautiful' we can't use に because 「うつくしい」 isn't a noun ([[*Logical particles]]), it's an engine. To use 「うつくしい」 as a noun we must convert it to its stem 「うつくしく」.
   #+BEGIN_QUOTE
   さくらがうつくしくなった - Sakura became beautiful
   #+END_QUOTE

* TODO です/ます form
   # TODO Add the bit from notes 'the only exceptions'
